// Code generated by ogen, DO NOT EDIT.

package job104

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

func (s *ErrorResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/CodeDescription
type CodeDescription struct {
	Code        OptString `json:"code"`
	Description OptString `json:"description"`
}

// GetCode returns the value of Code.
func (s *CodeDescription) GetCode() OptString {
	return s.Code
}

// GetDescription returns the value of Description.
func (s *CodeDescription) GetDescription() OptString {
	return s.Description
}

// SetCode sets the value of Code.
func (s *CodeDescription) SetCode(val OptString) {
	s.Code = val
}

// SetDescription sets the value of Description.
func (s *CodeDescription) SetDescription(val OptString) {
	s.Description = val
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Message         OptString `json:"message"`
	AdditionalProps ErrorResponseAdditional
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() OptString {
	return s.Message
}

// GetAdditionalProps returns the value of AdditionalProps.
func (s *ErrorResponse) GetAdditionalProps() ErrorResponseAdditional {
	return s.AdditionalProps
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val OptString) {
	s.Message = val
}

// SetAdditionalProps sets the value of AdditionalProps.
func (s *ErrorResponse) SetAdditionalProps(val ErrorResponseAdditional) {
	s.AdditionalProps = val
}

type ErrorResponseAdditional map[string]jx.Raw

func (s *ErrorResponseAdditional) init() ErrorResponseAdditional {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// ErrorResponseStatusCode wraps ErrorResponse with StatusCode.
type ErrorResponseStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorResponseStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorResponseStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// Ref: #/components/schemas/JobDetail
type JobDetail struct {
	Header    JobDetailHeader    `json:"header"`
	Contact   JobDetailContact   `json:"contact"`
	Condition JobDetailCondition `json:"condition"`
	Welfare   JobDetailWelfare   `json:"welfare"`
	JobDetail JobDetailJobDetail `json:"jobDetail"`
	Industry  string             `json:"industry"`
	Employees string             `json:"employees"`
	CustNo    string             `json:"custNo"`
}

// GetHeader returns the value of Header.
func (s *JobDetail) GetHeader() JobDetailHeader {
	return s.Header
}

// GetContact returns the value of Contact.
func (s *JobDetail) GetContact() JobDetailContact {
	return s.Contact
}

// GetCondition returns the value of Condition.
func (s *JobDetail) GetCondition() JobDetailCondition {
	return s.Condition
}

// GetWelfare returns the value of Welfare.
func (s *JobDetail) GetWelfare() JobDetailWelfare {
	return s.Welfare
}

// GetJobDetail returns the value of JobDetail.
func (s *JobDetail) GetJobDetail() JobDetailJobDetail {
	return s.JobDetail
}

// GetIndustry returns the value of Industry.
func (s *JobDetail) GetIndustry() string {
	return s.Industry
}

// GetEmployees returns the value of Employees.
func (s *JobDetail) GetEmployees() string {
	return s.Employees
}

// GetCustNo returns the value of CustNo.
func (s *JobDetail) GetCustNo() string {
	return s.CustNo
}

// SetHeader sets the value of Header.
func (s *JobDetail) SetHeader(val JobDetailHeader) {
	s.Header = val
}

// SetContact sets the value of Contact.
func (s *JobDetail) SetContact(val JobDetailContact) {
	s.Contact = val
}

// SetCondition sets the value of Condition.
func (s *JobDetail) SetCondition(val JobDetailCondition) {
	s.Condition = val
}

// SetWelfare sets the value of Welfare.
func (s *JobDetail) SetWelfare(val JobDetailWelfare) {
	s.Welfare = val
}

// SetJobDetail sets the value of JobDetail.
func (s *JobDetail) SetJobDetail(val JobDetailJobDetail) {
	s.JobDetail = val
}

// SetIndustry sets the value of Industry.
func (s *JobDetail) SetIndustry(val string) {
	s.Industry = val
}

// SetEmployees sets the value of Employees.
func (s *JobDetail) SetEmployees(val string) {
	s.Employees = val
}

// SetCustNo sets the value of CustNo.
func (s *JobDetail) SetCustNo(val string) {
	s.CustNo = val
}

type JobDetailCondition struct {
	WorkExp   OptString         `json:"workExp"`
	Edu       OptString         `json:"edu"`
	Major     []string          `json:"major"`
	Specialty []CodeDescription `json:"specialty"`
}

// GetWorkExp returns the value of WorkExp.
func (s *JobDetailCondition) GetWorkExp() OptString {
	return s.WorkExp
}

// GetEdu returns the value of Edu.
func (s *JobDetailCondition) GetEdu() OptString {
	return s.Edu
}

// GetMajor returns the value of Major.
func (s *JobDetailCondition) GetMajor() []string {
	return s.Major
}

// GetSpecialty returns the value of Specialty.
func (s *JobDetailCondition) GetSpecialty() []CodeDescription {
	return s.Specialty
}

// SetWorkExp sets the value of WorkExp.
func (s *JobDetailCondition) SetWorkExp(val OptString) {
	s.WorkExp = val
}

// SetEdu sets the value of Edu.
func (s *JobDetailCondition) SetEdu(val OptString) {
	s.Edu = val
}

// SetMajor sets the value of Major.
func (s *JobDetailCondition) SetMajor(val []string) {
	s.Major = val
}

// SetSpecialty sets the value of Specialty.
func (s *JobDetailCondition) SetSpecialty(val []CodeDescription) {
	s.Specialty = val
}

type JobDetailContact struct {
	HrName OptString `json:"hrName"`
	Email  OptString `json:"email"`
	Reply  OptString `json:"reply"`
}

// GetHrName returns the value of HrName.
func (s *JobDetailContact) GetHrName() OptString {
	return s.HrName
}

// GetEmail returns the value of Email.
func (s *JobDetailContact) GetEmail() OptString {
	return s.Email
}

// GetReply returns the value of Reply.
func (s *JobDetailContact) GetReply() OptString {
	return s.Reply
}

// SetHrName sets the value of HrName.
func (s *JobDetailContact) SetHrName(val OptString) {
	s.HrName = val
}

// SetEmail sets the value of Email.
func (s *JobDetailContact) SetEmail(val OptString) {
	s.Email = val
}

// SetReply sets the value of Reply.
func (s *JobDetailContact) SetReply(val OptString) {
	s.Reply = val
}

type JobDetailHeader struct {
	JobName    string `json:"jobName"`
	CustName   string `json:"custName"`
	CustUrl    string `json:"custUrl"`
	AppearDate string `json:"appearDate"`
	IsSaved    bool   `json:"isSaved"`
	IsApplied  bool   `json:"isApplied"`
}

// GetJobName returns the value of JobName.
func (s *JobDetailHeader) GetJobName() string {
	return s.JobName
}

// GetCustName returns the value of CustName.
func (s *JobDetailHeader) GetCustName() string {
	return s.CustName
}

// GetCustUrl returns the value of CustUrl.
func (s *JobDetailHeader) GetCustUrl() string {
	return s.CustUrl
}

// GetAppearDate returns the value of AppearDate.
func (s *JobDetailHeader) GetAppearDate() string {
	return s.AppearDate
}

// GetIsSaved returns the value of IsSaved.
func (s *JobDetailHeader) GetIsSaved() bool {
	return s.IsSaved
}

// GetIsApplied returns the value of IsApplied.
func (s *JobDetailHeader) GetIsApplied() bool {
	return s.IsApplied
}

// SetJobName sets the value of JobName.
func (s *JobDetailHeader) SetJobName(val string) {
	s.JobName = val
}

// SetCustName sets the value of CustName.
func (s *JobDetailHeader) SetCustName(val string) {
	s.CustName = val
}

// SetCustUrl sets the value of CustUrl.
func (s *JobDetailHeader) SetCustUrl(val string) {
	s.CustUrl = val
}

// SetAppearDate sets the value of AppearDate.
func (s *JobDetailHeader) SetAppearDate(val string) {
	s.AppearDate = val
}

// SetIsSaved sets the value of IsSaved.
func (s *JobDetailHeader) SetIsSaved(val bool) {
	s.IsSaved = val
}

// SetIsApplied sets the value of IsApplied.
func (s *JobDetailHeader) SetIsApplied(val bool) {
	s.IsApplied = val
}

type JobDetailJobDetail struct {
	JobDescription OptString         `json:"jobDescription"`
	JobCategory    []CodeDescription `json:"jobCategory"`
	Salary         OptString         `json:"salary"`
	SalaryMin      OptInt            `json:"salaryMin"`
	SalaryMax      OptInt            `json:"salaryMax"`
	JobType        OptInt            `json:"jobType"`
	AddressRegion  OptString         `json:"addressRegion"`
	AddressDetail  OptString         `json:"addressDetail"`
	ManageResp     OptString         `json:"manageResp"`
	NeedEmp        OptString         `json:"needEmp"`
	// Null for non-remote postings, not just absent. `type` matches the `remoteWork` request values (1 =
	// Fully remote, 2 = Partial/hybrid remote).
	RemoteWork OptNilJobDetailJobDetailRemoteWork `json:"remoteWork"`
}

// GetJobDescription returns the value of JobDescription.
func (s *JobDetailJobDetail) GetJobDescription() OptString {
	return s.JobDescription
}

// GetJobCategory returns the value of JobCategory.
func (s *JobDetailJobDetail) GetJobCategory() []CodeDescription {
	return s.JobCategory
}

// GetSalary returns the value of Salary.
func (s *JobDetailJobDetail) GetSalary() OptString {
	return s.Salary
}

// GetSalaryMin returns the value of SalaryMin.
func (s *JobDetailJobDetail) GetSalaryMin() OptInt {
	return s.SalaryMin
}

// GetSalaryMax returns the value of SalaryMax.
func (s *JobDetailJobDetail) GetSalaryMax() OptInt {
	return s.SalaryMax
}

// GetJobType returns the value of JobType.
func (s *JobDetailJobDetail) GetJobType() OptInt {
	return s.JobType
}

// GetAddressRegion returns the value of AddressRegion.
func (s *JobDetailJobDetail) GetAddressRegion() OptString {
	return s.AddressRegion
}

// GetAddressDetail returns the value of AddressDetail.
func (s *JobDetailJobDetail) GetAddressDetail() OptString {
	return s.AddressDetail
}

// GetManageResp returns the value of ManageResp.
func (s *JobDetailJobDetail) GetManageResp() OptString {
	return s.ManageResp
}

// GetNeedEmp returns the value of NeedEmp.
func (s *JobDetailJobDetail) GetNeedEmp() OptString {
	return s.NeedEmp
}

// GetRemoteWork returns the value of RemoteWork.
func (s *JobDetailJobDetail) GetRemoteWork() OptNilJobDetailJobDetailRemoteWork {
	return s.RemoteWork
}

// SetJobDescription sets the value of JobDescription.
func (s *JobDetailJobDetail) SetJobDescription(val OptString) {
	s.JobDescription = val
}

// SetJobCategory sets the value of JobCategory.
func (s *JobDetailJobDetail) SetJobCategory(val []CodeDescription) {
	s.JobCategory = val
}

// SetSalary sets the value of Salary.
func (s *JobDetailJobDetail) SetSalary(val OptString) {
	s.Salary = val
}

// SetSalaryMin sets the value of SalaryMin.
func (s *JobDetailJobDetail) SetSalaryMin(val OptInt) {
	s.SalaryMin = val
}

// SetSalaryMax sets the value of SalaryMax.
func (s *JobDetailJobDetail) SetSalaryMax(val OptInt) {
	s.SalaryMax = val
}

// SetJobType sets the value of JobType.
func (s *JobDetailJobDetail) SetJobType(val OptInt) {
	s.JobType = val
}

// SetAddressRegion sets the value of AddressRegion.
func (s *JobDetailJobDetail) SetAddressRegion(val OptString) {
	s.AddressRegion = val
}

// SetAddressDetail sets the value of AddressDetail.
func (s *JobDetailJobDetail) SetAddressDetail(val OptString) {
	s.AddressDetail = val
}

// SetManageResp sets the value of ManageResp.
func (s *JobDetailJobDetail) SetManageResp(val OptString) {
	s.ManageResp = val
}

// SetNeedEmp sets the value of NeedEmp.
func (s *JobDetailJobDetail) SetNeedEmp(val OptString) {
	s.NeedEmp = val
}

// SetRemoteWork sets the value of RemoteWork.
func (s *JobDetailJobDetail) SetRemoteWork(val OptNilJobDetailJobDetailRemoteWork) {
	s.RemoteWork = val
}

// Null for non-remote postings, not just absent. `type` matches the `remoteWork` request values (1 =
// Fully remote, 2 = Partial/hybrid remote).
type JobDetailJobDetailRemoteWork struct {
	Type        OptInt    `json:"type"`
	Description OptString `json:"description"`
}

// GetType returns the value of Type.
func (s *JobDetailJobDetailRemoteWork) GetType() OptInt {
	return s.Type
}

// GetDescription returns the value of Description.
func (s *JobDetailJobDetailRemoteWork) GetDescription() OptString {
	return s.Description
}

// SetType sets the value of Type.
func (s *JobDetailJobDetailRemoteWork) SetType(val OptInt) {
	s.Type = val
}

// SetDescription sets the value of Description.
func (s *JobDetailJobDetailRemoteWork) SetDescription(val OptString) {
	s.Description = val
}

// Ref: #/components/schemas/JobDetailResponse
type JobDetailResponse struct {
	Data JobDetail `json:"data"`
}

// GetData returns the value of Data.
func (s *JobDetailResponse) GetData() JobDetail {
	return s.Data
}

// SetData sets the value of Data.
func (s *JobDetailResponse) SetData(val JobDetail) {
	s.Data = val
}

type JobDetailWelfare struct {
	Welfare OptString `json:"welfare"`
}

// GetWelfare returns the value of Welfare.
func (s *JobDetailWelfare) GetWelfare() OptString {
	return s.Welfare
}

// SetWelfare sets the value of Welfare.
func (s *JobDetailWelfare) SetWelfare(val OptString) {
	s.Welfare = val
}

// Ref: #/components/schemas/JobSummary
type JobSummary struct {
	JobNo         string         `json:"jobNo"`
	JobName       string         `json:"jobName"`
	CustName      string         `json:"custName"`
	CustNo        string         `json:"custNo"`
	Link          JobSummaryLink `json:"link"`
	SalaryHigh    int            `json:"salaryHigh"`
	SalaryLow     int            `json:"salaryLow"`
	JobAddrNoDesc string         `json:"jobAddrNoDesc"`
	AppearDate    string         `json:"appearDate"`
	ApplyCnt      int            `json:"applyCnt"`
	// 0 = not remote; matches the remoteWork request values otherwise. The `remoteWork` request param is a
	// soft filter — check this field per entry if you need a strict result set (see the `remoteWork`
	// parameter description on searchJobs).
	RemoteWorkType int `json:"remoteWorkType"`
	// Matches the `ro` request values (1 = Full-time, 2 = Part-time). The `ro` request param is a soft
	// filter — check this field per entry if you need a strict result set (see the `ro` parameter
	// description on searchJobs).
	JobRo int `json:"jobRo"`
	// Minimum-experience code: 0 = no requirement (經歷不拘), otherwise the posting's minimum years of
	// experience plus one (confirmed against job details: 2 = 1年以上, 4 = 3年以上, 11 =
	// 10年以上). The `jobexp` request buckets group this field (jobexp 1 → period 0-1, 3 → 2-3, 5
	// → 4-5, 10 → 6-10, 99 → 11+). `jobexp` is a soft filter — check this field per entry if you
	// need a strict result set (see the `jobexp` parameter description on searchJobs).
	Period int `json:"period"`
}

// GetJobNo returns the value of JobNo.
func (s *JobSummary) GetJobNo() string {
	return s.JobNo
}

// GetJobName returns the value of JobName.
func (s *JobSummary) GetJobName() string {
	return s.JobName
}

// GetCustName returns the value of CustName.
func (s *JobSummary) GetCustName() string {
	return s.CustName
}

// GetCustNo returns the value of CustNo.
func (s *JobSummary) GetCustNo() string {
	return s.CustNo
}

// GetLink returns the value of Link.
func (s *JobSummary) GetLink() JobSummaryLink {
	return s.Link
}

// GetSalaryHigh returns the value of SalaryHigh.
func (s *JobSummary) GetSalaryHigh() int {
	return s.SalaryHigh
}

// GetSalaryLow returns the value of SalaryLow.
func (s *JobSummary) GetSalaryLow() int {
	return s.SalaryLow
}

// GetJobAddrNoDesc returns the value of JobAddrNoDesc.
func (s *JobSummary) GetJobAddrNoDesc() string {
	return s.JobAddrNoDesc
}

// GetAppearDate returns the value of AppearDate.
func (s *JobSummary) GetAppearDate() string {
	return s.AppearDate
}

// GetApplyCnt returns the value of ApplyCnt.
func (s *JobSummary) GetApplyCnt() int {
	return s.ApplyCnt
}

// GetRemoteWorkType returns the value of RemoteWorkType.
func (s *JobSummary) GetRemoteWorkType() int {
	return s.RemoteWorkType
}

// GetJobRo returns the value of JobRo.
func (s *JobSummary) GetJobRo() int {
	return s.JobRo
}

// GetPeriod returns the value of Period.
func (s *JobSummary) GetPeriod() int {
	return s.Period
}

// SetJobNo sets the value of JobNo.
func (s *JobSummary) SetJobNo(val string) {
	s.JobNo = val
}

// SetJobName sets the value of JobName.
func (s *JobSummary) SetJobName(val string) {
	s.JobName = val
}

// SetCustName sets the value of CustName.
func (s *JobSummary) SetCustName(val string) {
	s.CustName = val
}

// SetCustNo sets the value of CustNo.
func (s *JobSummary) SetCustNo(val string) {
	s.CustNo = val
}

// SetLink sets the value of Link.
func (s *JobSummary) SetLink(val JobSummaryLink) {
	s.Link = val
}

// SetSalaryHigh sets the value of SalaryHigh.
func (s *JobSummary) SetSalaryHigh(val int) {
	s.SalaryHigh = val
}

// SetSalaryLow sets the value of SalaryLow.
func (s *JobSummary) SetSalaryLow(val int) {
	s.SalaryLow = val
}

// SetJobAddrNoDesc sets the value of JobAddrNoDesc.
func (s *JobSummary) SetJobAddrNoDesc(val string) {
	s.JobAddrNoDesc = val
}

// SetAppearDate sets the value of AppearDate.
func (s *JobSummary) SetAppearDate(val string) {
	s.AppearDate = val
}

// SetApplyCnt sets the value of ApplyCnt.
func (s *JobSummary) SetApplyCnt(val int) {
	s.ApplyCnt = val
}

// SetRemoteWorkType sets the value of RemoteWorkType.
func (s *JobSummary) SetRemoteWorkType(val int) {
	s.RemoteWorkType = val
}

// SetJobRo sets the value of JobRo.
func (s *JobSummary) SetJobRo(val int) {
	s.JobRo = val
}

// SetPeriod sets the value of Period.
func (s *JobSummary) SetPeriod(val int) {
	s.Period = val
}

type JobSummaryLink struct {
	// Public job posting URL; the trailing path segment is the job code.
	Job  string `json:"job"`
	Cust string `json:"cust"`
}

// GetJob returns the value of Job.
func (s *JobSummaryLink) GetJob() string {
	return s.Job
}

// GetCust returns the value of Cust.
func (s *JobSummaryLink) GetCust() string {
	return s.Cust
}

// SetJob sets the value of Job.
func (s *JobSummaryLink) SetJob(val string) {
	s.Job = val
}

// SetCust sets the value of Cust.
func (s *JobSummaryLink) SetCust(val string) {
	s.Cust = val
}

// Ref: #/components/schemas/JobsResponse
type JobsResponse struct {
	Data     []JobSummary         `json:"data"`
	Metadata JobsResponseMetadata `json:"metadata"`
}

// GetData returns the value of Data.
func (s *JobsResponse) GetData() []JobSummary {
	return s.Data
}

// GetMetadata returns the value of Metadata.
func (s *JobsResponse) GetMetadata() JobsResponseMetadata {
	return s.Metadata
}

// SetData sets the value of Data.
func (s *JobsResponse) SetData(val []JobSummary) {
	s.Data = val
}

// SetMetadata sets the value of Metadata.
func (s *JobsResponse) SetMetadata(val JobsResponseMetadata) {
	s.Metadata = val
}

type JobsResponseMetadata struct {
	Pagination JobsResponseMetadataPagination `json:"pagination"`
}

// GetPagination returns the value of Pagination.
func (s *JobsResponseMetadata) GetPagination() JobsResponseMetadataPagination {
	return s.Pagination
}

// SetPagination sets the value of Pagination.
func (s *JobsResponseMetadata) SetPagination(val JobsResponseMetadataPagination) {
	s.Pagination = val
}

type JobsResponseMetadataPagination struct {
	CurrentPage int `json:"currentPage"`
	LastPage    int `json:"lastPage"`
	Total       int `json:"total"`
}

// GetCurrentPage returns the value of CurrentPage.
func (s *JobsResponseMetadataPagination) GetCurrentPage() int {
	return s.CurrentPage
}

// GetLastPage returns the value of LastPage.
func (s *JobsResponseMetadataPagination) GetLastPage() int {
	return s.LastPage
}

// GetTotal returns the value of Total.
func (s *JobsResponseMetadataPagination) GetTotal() int {
	return s.Total
}

// SetCurrentPage sets the value of CurrentPage.
func (s *JobsResponseMetadataPagination) SetCurrentPage(val int) {
	s.CurrentPage = val
}

// SetLastPage sets the value of LastPage.
func (s *JobsResponseMetadataPagination) SetLastPage(val int) {
	s.LastPage = val
}

// SetTotal sets the value of Total.
func (s *JobsResponseMetadataPagination) SetTotal(val int) {
	s.Total = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilJobDetailJobDetailRemoteWork returns new OptNilJobDetailJobDetailRemoteWork with value set to v.
func NewOptNilJobDetailJobDetailRemoteWork(v JobDetailJobDetailRemoteWork) OptNilJobDetailJobDetailRemoteWork {
	return OptNilJobDetailJobDetailRemoteWork{
		Value: v,
		Set:   true,
	}
}

// OptNilJobDetailJobDetailRemoteWork is optional nullable JobDetailJobDetailRemoteWork.
type OptNilJobDetailJobDetailRemoteWork struct {
	Value JobDetailJobDetailRemoteWork
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilJobDetailJobDetailRemoteWork was set.
func (o OptNilJobDetailJobDetailRemoteWork) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilJobDetailJobDetailRemoteWork) Reset() {
	var v JobDetailJobDetailRemoteWork
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilJobDetailJobDetailRemoteWork) SetTo(v JobDetailJobDetailRemoteWork) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilJobDetailJobDetailRemoteWork) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilJobDetailJobDetailRemoteWork) SetToNull() {
	o.Set = true
	o.Null = true
	var v JobDetailJobDetailRemoteWork
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilJobDetailJobDetailRemoteWork) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilJobDetailJobDetailRemoteWork) Get() (v JobDetailJobDetailRemoteWork, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilJobDetailJobDetailRemoteWork) Or(d JobDetailJobDetailRemoteWork) JobDetailJobDetailRemoteWork {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSearchJobsArea returns new OptSearchJobsArea with value set to v.
func NewOptSearchJobsArea(v SearchJobsArea) OptSearchJobsArea {
	return OptSearchJobsArea{
		Value: v,
		Set:   true,
	}
}

// OptSearchJobsArea is optional SearchJobsArea.
type OptSearchJobsArea struct {
	Value SearchJobsArea
	Set   bool
}

// IsSet returns true if OptSearchJobsArea was set.
func (o OptSearchJobsArea) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSearchJobsArea) Reset() {
	var v SearchJobsArea
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSearchJobsArea) SetTo(v SearchJobsArea) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSearchJobsArea) Get() (v SearchJobsArea, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSearchJobsArea) Or(d SearchJobsArea) SearchJobsArea {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSearchJobsOrder returns new OptSearchJobsOrder with value set to v.
func NewOptSearchJobsOrder(v SearchJobsOrder) OptSearchJobsOrder {
	return OptSearchJobsOrder{
		Value: v,
		Set:   true,
	}
}

// OptSearchJobsOrder is optional SearchJobsOrder.
type OptSearchJobsOrder struct {
	Value SearchJobsOrder
	Set   bool
}

// IsSet returns true if OptSearchJobsOrder was set.
func (o OptSearchJobsOrder) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSearchJobsOrder) Reset() {
	var v SearchJobsOrder
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSearchJobsOrder) SetTo(v SearchJobsOrder) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSearchJobsOrder) Get() (v SearchJobsOrder, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSearchJobsOrder) Or(d SearchJobsOrder) SearchJobsOrder {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSearchJobsRemoteWork returns new OptSearchJobsRemoteWork with value set to v.
func NewOptSearchJobsRemoteWork(v SearchJobsRemoteWork) OptSearchJobsRemoteWork {
	return OptSearchJobsRemoteWork{
		Value: v,
		Set:   true,
	}
}

// OptSearchJobsRemoteWork is optional SearchJobsRemoteWork.
type OptSearchJobsRemoteWork struct {
	Value SearchJobsRemoteWork
	Set   bool
}

// IsSet returns true if OptSearchJobsRemoteWork was set.
func (o OptSearchJobsRemoteWork) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSearchJobsRemoteWork) Reset() {
	var v SearchJobsRemoteWork
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSearchJobsRemoteWork) SetTo(v SearchJobsRemoteWork) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSearchJobsRemoteWork) Get() (v SearchJobsRemoteWork, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSearchJobsRemoteWork) Or(d SearchJobsRemoteWork) SearchJobsRemoteWork {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSearchJobsRo returns new OptSearchJobsRo with value set to v.
func NewOptSearchJobsRo(v SearchJobsRo) OptSearchJobsRo {
	return OptSearchJobsRo{
		Value: v,
		Set:   true,
	}
}

// OptSearchJobsRo is optional SearchJobsRo.
type OptSearchJobsRo struct {
	Value SearchJobsRo
	Set   bool
}

// IsSet returns true if OptSearchJobsRo was set.
func (o OptSearchJobsRo) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSearchJobsRo) Reset() {
	var v SearchJobsRo
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSearchJobsRo) SetTo(v SearchJobsRo) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSearchJobsRo) Get() (v SearchJobsRo, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSearchJobsRo) Or(d SearchJobsRo) SearchJobsRo {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type SearchJobsArea string

const (
	SearchJobsArea6001001000 SearchJobsArea = "6001001000"
	SearchJobsArea6001002000 SearchJobsArea = "6001002000"
	SearchJobsArea6001003000 SearchJobsArea = "6001003000"
	SearchJobsArea6001004000 SearchJobsArea = "6001004000"
	SearchJobsArea6001005000 SearchJobsArea = "6001005000"
	SearchJobsArea6001006000 SearchJobsArea = "6001006000"
	SearchJobsArea6001007000 SearchJobsArea = "6001007000"
	SearchJobsArea6001008000 SearchJobsArea = "6001008000"
	SearchJobsArea6001010000 SearchJobsArea = "6001010000"
	SearchJobsArea6001011000 SearchJobsArea = "6001011000"
	SearchJobsArea6001012000 SearchJobsArea = "6001012000"
	SearchJobsArea6001013000 SearchJobsArea = "6001013000"
	SearchJobsArea6001014000 SearchJobsArea = "6001014000"
	SearchJobsArea6001016000 SearchJobsArea = "6001016000"
	SearchJobsArea6001018000 SearchJobsArea = "6001018000"
	SearchJobsArea6001019000 SearchJobsArea = "6001019000"
	SearchJobsArea6001020000 SearchJobsArea = "6001020000"
	SearchJobsArea6001021000 SearchJobsArea = "6001021000"
	SearchJobsArea6001022000 SearchJobsArea = "6001022000"
	SearchJobsArea6001023000 SearchJobsArea = "6001023000"
	SearchJobsArea6002001000 SearchJobsArea = "6002001000"
	SearchJobsArea6002002000 SearchJobsArea = "6002002000"
	SearchJobsArea6002003000 SearchJobsArea = "6002003000"
	SearchJobsArea6002004000 SearchJobsArea = "6002004000"
	SearchJobsArea6002005000 SearchJobsArea = "6002005000"
	SearchJobsArea6002006000 SearchJobsArea = "6002006000"
	SearchJobsArea6002007000 SearchJobsArea = "6002007000"
	SearchJobsArea6002008000 SearchJobsArea = "6002008000"
	SearchJobsArea6002009000 SearchJobsArea = "6002009000"
	SearchJobsArea6002010000 SearchJobsArea = "6002010000"
	SearchJobsArea6002011000 SearchJobsArea = "6002011000"
	SearchJobsArea6002012000 SearchJobsArea = "6002012000"
	SearchJobsArea6002013000 SearchJobsArea = "6002013000"
	SearchJobsArea6002014000 SearchJobsArea = "6002014000"
	SearchJobsArea6002015000 SearchJobsArea = "6002015000"
	SearchJobsArea6002016000 SearchJobsArea = "6002016000"
	SearchJobsArea6002017000 SearchJobsArea = "6002017000"
	SearchJobsArea6002018000 SearchJobsArea = "6002018000"
	SearchJobsArea6002019000 SearchJobsArea = "6002019000"
	SearchJobsArea6002020000 SearchJobsArea = "6002020000"
	SearchJobsArea6002021000 SearchJobsArea = "6002021000"
	SearchJobsArea6002022000 SearchJobsArea = "6002022000"
	SearchJobsArea6002023000 SearchJobsArea = "6002023000"
	SearchJobsArea6002024000 SearchJobsArea = "6002024000"
	SearchJobsArea6002025000 SearchJobsArea = "6002025000"
	SearchJobsArea6002026000 SearchJobsArea = "6002026000"
	SearchJobsArea6002027000 SearchJobsArea = "6002027000"
	SearchJobsArea6002028000 SearchJobsArea = "6002028000"
	SearchJobsArea6002029000 SearchJobsArea = "6002029000"
	SearchJobsArea6002030000 SearchJobsArea = "6002030000"
	SearchJobsArea6002031000 SearchJobsArea = "6002031000"
	SearchJobsArea6002032000 SearchJobsArea = "6002032000"
	SearchJobsArea6002033000 SearchJobsArea = "6002033000"
	SearchJobsArea6003001000 SearchJobsArea = "6003001000"
	SearchJobsArea6003002000 SearchJobsArea = "6003002000"
	SearchJobsArea6003003000 SearchJobsArea = "6003003000"
	SearchJobsArea6004001000 SearchJobsArea = "6004001000"
	SearchJobsArea6004002000 SearchJobsArea = "6004002000"
	SearchJobsArea6005001000 SearchJobsArea = "6005001000"
	SearchJobsArea6005002000 SearchJobsArea = "6005002000"
	SearchJobsArea6005003000 SearchJobsArea = "6005003000"
	SearchJobsArea6005004000 SearchJobsArea = "6005004000"
	SearchJobsArea6006001000 SearchJobsArea = "6006001000"
	SearchJobsArea6006002000 SearchJobsArea = "6006002000"
	SearchJobsArea6007001000 SearchJobsArea = "6007001000"
	SearchJobsArea6007002000 SearchJobsArea = "6007002000"
	SearchJobsArea6007003000 SearchJobsArea = "6007003000"
	SearchJobsArea6007004000 SearchJobsArea = "6007004000"
	SearchJobsArea6007005000 SearchJobsArea = "6007005000"
	SearchJobsArea6008001000 SearchJobsArea = "6008001000"
	SearchJobsArea6008002000 SearchJobsArea = "6008002000"
	SearchJobsArea6008003000 SearchJobsArea = "6008003000"
	SearchJobsArea6008004000 SearchJobsArea = "6008004000"
	SearchJobsArea6008005000 SearchJobsArea = "6008005000"
)

// AllValues returns all SearchJobsArea values.
func (SearchJobsArea) AllValues() []SearchJobsArea {
	return []SearchJobsArea{
		SearchJobsArea6001001000,
		SearchJobsArea6001002000,
		SearchJobsArea6001003000,
		SearchJobsArea6001004000,
		SearchJobsArea6001005000,
		SearchJobsArea6001006000,
		SearchJobsArea6001007000,
		SearchJobsArea6001008000,
		SearchJobsArea6001010000,
		SearchJobsArea6001011000,
		SearchJobsArea6001012000,
		SearchJobsArea6001013000,
		SearchJobsArea6001014000,
		SearchJobsArea6001016000,
		SearchJobsArea6001018000,
		SearchJobsArea6001019000,
		SearchJobsArea6001020000,
		SearchJobsArea6001021000,
		SearchJobsArea6001022000,
		SearchJobsArea6001023000,
		SearchJobsArea6002001000,
		SearchJobsArea6002002000,
		SearchJobsArea6002003000,
		SearchJobsArea6002004000,
		SearchJobsArea6002005000,
		SearchJobsArea6002006000,
		SearchJobsArea6002007000,
		SearchJobsArea6002008000,
		SearchJobsArea6002009000,
		SearchJobsArea6002010000,
		SearchJobsArea6002011000,
		SearchJobsArea6002012000,
		SearchJobsArea6002013000,
		SearchJobsArea6002014000,
		SearchJobsArea6002015000,
		SearchJobsArea6002016000,
		SearchJobsArea6002017000,
		SearchJobsArea6002018000,
		SearchJobsArea6002019000,
		SearchJobsArea6002020000,
		SearchJobsArea6002021000,
		SearchJobsArea6002022000,
		SearchJobsArea6002023000,
		SearchJobsArea6002024000,
		SearchJobsArea6002025000,
		SearchJobsArea6002026000,
		SearchJobsArea6002027000,
		SearchJobsArea6002028000,
		SearchJobsArea6002029000,
		SearchJobsArea6002030000,
		SearchJobsArea6002031000,
		SearchJobsArea6002032000,
		SearchJobsArea6002033000,
		SearchJobsArea6003001000,
		SearchJobsArea6003002000,
		SearchJobsArea6003003000,
		SearchJobsArea6004001000,
		SearchJobsArea6004002000,
		SearchJobsArea6005001000,
		SearchJobsArea6005002000,
		SearchJobsArea6005003000,
		SearchJobsArea6005004000,
		SearchJobsArea6006001000,
		SearchJobsArea6006002000,
		SearchJobsArea6007001000,
		SearchJobsArea6007002000,
		SearchJobsArea6007003000,
		SearchJobsArea6007004000,
		SearchJobsArea6007005000,
		SearchJobsArea6008001000,
		SearchJobsArea6008002000,
		SearchJobsArea6008003000,
		SearchJobsArea6008004000,
		SearchJobsArea6008005000,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SearchJobsArea) MarshalText() ([]byte, error) {
	switch s {
	case SearchJobsArea6001001000:
		return []byte(s), nil
	case SearchJobsArea6001002000:
		return []byte(s), nil
	case SearchJobsArea6001003000:
		return []byte(s), nil
	case SearchJobsArea6001004000:
		return []byte(s), nil
	case SearchJobsArea6001005000:
		return []byte(s), nil
	case SearchJobsArea6001006000:
		return []byte(s), nil
	case SearchJobsArea6001007000:
		return []byte(s), nil
	case SearchJobsArea6001008000:
		return []byte(s), nil
	case SearchJobsArea6001010000:
		return []byte(s), nil
	case SearchJobsArea6001011000:
		return []byte(s), nil
	case SearchJobsArea6001012000:
		return []byte(s), nil
	case SearchJobsArea6001013000:
		return []byte(s), nil
	case SearchJobsArea6001014000:
		return []byte(s), nil
	case SearchJobsArea6001016000:
		return []byte(s), nil
	case SearchJobsArea6001018000:
		return []byte(s), nil
	case SearchJobsArea6001019000:
		return []byte(s), nil
	case SearchJobsArea6001020000:
		return []byte(s), nil
	case SearchJobsArea6001021000:
		return []byte(s), nil
	case SearchJobsArea6001022000:
		return []byte(s), nil
	case SearchJobsArea6001023000:
		return []byte(s), nil
	case SearchJobsArea6002001000:
		return []byte(s), nil
	case SearchJobsArea6002002000:
		return []byte(s), nil
	case SearchJobsArea6002003000:
		return []byte(s), nil
	case SearchJobsArea6002004000:
		return []byte(s), nil
	case SearchJobsArea6002005000:
		return []byte(s), nil
	case SearchJobsArea6002006000:
		return []byte(s), nil
	case SearchJobsArea6002007000:
		return []byte(s), nil
	case SearchJobsArea6002008000:
		return []byte(s), nil
	case SearchJobsArea6002009000:
		return []byte(s), nil
	case SearchJobsArea6002010000:
		return []byte(s), nil
	case SearchJobsArea6002011000:
		return []byte(s), nil
	case SearchJobsArea6002012000:
		return []byte(s), nil
	case SearchJobsArea6002013000:
		return []byte(s), nil
	case SearchJobsArea6002014000:
		return []byte(s), nil
	case SearchJobsArea6002015000:
		return []byte(s), nil
	case SearchJobsArea6002016000:
		return []byte(s), nil
	case SearchJobsArea6002017000:
		return []byte(s), nil
	case SearchJobsArea6002018000:
		return []byte(s), nil
	case SearchJobsArea6002019000:
		return []byte(s), nil
	case SearchJobsArea6002020000:
		return []byte(s), nil
	case SearchJobsArea6002021000:
		return []byte(s), nil
	case SearchJobsArea6002022000:
		return []byte(s), nil
	case SearchJobsArea6002023000:
		return []byte(s), nil
	case SearchJobsArea6002024000:
		return []byte(s), nil
	case SearchJobsArea6002025000:
		return []byte(s), nil
	case SearchJobsArea6002026000:
		return []byte(s), nil
	case SearchJobsArea6002027000:
		return []byte(s), nil
	case SearchJobsArea6002028000:
		return []byte(s), nil
	case SearchJobsArea6002029000:
		return []byte(s), nil
	case SearchJobsArea6002030000:
		return []byte(s), nil
	case SearchJobsArea6002031000:
		return []byte(s), nil
	case SearchJobsArea6002032000:
		return []byte(s), nil
	case SearchJobsArea6002033000:
		return []byte(s), nil
	case SearchJobsArea6003001000:
		return []byte(s), nil
	case SearchJobsArea6003002000:
		return []byte(s), nil
	case SearchJobsArea6003003000:
		return []byte(s), nil
	case SearchJobsArea6004001000:
		return []byte(s), nil
	case SearchJobsArea6004002000:
		return []byte(s), nil
	case SearchJobsArea6005001000:
		return []byte(s), nil
	case SearchJobsArea6005002000:
		return []byte(s), nil
	case SearchJobsArea6005003000:
		return []byte(s), nil
	case SearchJobsArea6005004000:
		return []byte(s), nil
	case SearchJobsArea6006001000:
		return []byte(s), nil
	case SearchJobsArea6006002000:
		return []byte(s), nil
	case SearchJobsArea6007001000:
		return []byte(s), nil
	case SearchJobsArea6007002000:
		return []byte(s), nil
	case SearchJobsArea6007003000:
		return []byte(s), nil
	case SearchJobsArea6007004000:
		return []byte(s), nil
	case SearchJobsArea6007005000:
		return []byte(s), nil
	case SearchJobsArea6008001000:
		return []byte(s), nil
	case SearchJobsArea6008002000:
		return []byte(s), nil
	case SearchJobsArea6008003000:
		return []byte(s), nil
	case SearchJobsArea6008004000:
		return []byte(s), nil
	case SearchJobsArea6008005000:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SearchJobsArea) UnmarshalText(data []byte) error {
	switch SearchJobsArea(data) {
	case SearchJobsArea6001001000:
		*s = SearchJobsArea6001001000
		return nil
	case SearchJobsArea6001002000:
		*s = SearchJobsArea6001002000
		return nil
	case SearchJobsArea6001003000:
		*s = SearchJobsArea6001003000
		return nil
	case SearchJobsArea6001004000:
		*s = SearchJobsArea6001004000
		return nil
	case SearchJobsArea6001005000:
		*s = SearchJobsArea6001005000
		return nil
	case SearchJobsArea6001006000:
		*s = SearchJobsArea6001006000
		return nil
	case SearchJobsArea6001007000:
		*s = SearchJobsArea6001007000
		return nil
	case SearchJobsArea6001008000:
		*s = SearchJobsArea6001008000
		return nil
	case SearchJobsArea6001010000:
		*s = SearchJobsArea6001010000
		return nil
	case SearchJobsArea6001011000:
		*s = SearchJobsArea6001011000
		return nil
	case SearchJobsArea6001012000:
		*s = SearchJobsArea6001012000
		return nil
	case SearchJobsArea6001013000:
		*s = SearchJobsArea6001013000
		return nil
	case SearchJobsArea6001014000:
		*s = SearchJobsArea6001014000
		return nil
	case SearchJobsArea6001016000:
		*s = SearchJobsArea6001016000
		return nil
	case SearchJobsArea6001018000:
		*s = SearchJobsArea6001018000
		return nil
	case SearchJobsArea6001019000:
		*s = SearchJobsArea6001019000
		return nil
	case SearchJobsArea6001020000:
		*s = SearchJobsArea6001020000
		return nil
	case SearchJobsArea6001021000:
		*s = SearchJobsArea6001021000
		return nil
	case SearchJobsArea6001022000:
		*s = SearchJobsArea6001022000
		return nil
	case SearchJobsArea6001023000:
		*s = SearchJobsArea6001023000
		return nil
	case SearchJobsArea6002001000:
		*s = SearchJobsArea6002001000
		return nil
	case SearchJobsArea6002002000:
		*s = SearchJobsArea6002002000
		return nil
	case SearchJobsArea6002003000:
		*s = SearchJobsArea6002003000
		return nil
	case SearchJobsArea6002004000:
		*s = SearchJobsArea6002004000
		return nil
	case SearchJobsArea6002005000:
		*s = SearchJobsArea6002005000
		return nil
	case SearchJobsArea6002006000:
		*s = SearchJobsArea6002006000
		return nil
	case SearchJobsArea6002007000:
		*s = SearchJobsArea6002007000
		return nil
	case SearchJobsArea6002008000:
		*s = SearchJobsArea6002008000
		return nil
	case SearchJobsArea6002009000:
		*s = SearchJobsArea6002009000
		return nil
	case SearchJobsArea6002010000:
		*s = SearchJobsArea6002010000
		return nil
	case SearchJobsArea6002011000:
		*s = SearchJobsArea6002011000
		return nil
	case SearchJobsArea6002012000:
		*s = SearchJobsArea6002012000
		return nil
	case SearchJobsArea6002013000:
		*s = SearchJobsArea6002013000
		return nil
	case SearchJobsArea6002014000:
		*s = SearchJobsArea6002014000
		return nil
	case SearchJobsArea6002015000:
		*s = SearchJobsArea6002015000
		return nil
	case SearchJobsArea6002016000:
		*s = SearchJobsArea6002016000
		return nil
	case SearchJobsArea6002017000:
		*s = SearchJobsArea6002017000
		return nil
	case SearchJobsArea6002018000:
		*s = SearchJobsArea6002018000
		return nil
	case SearchJobsArea6002019000:
		*s = SearchJobsArea6002019000
		return nil
	case SearchJobsArea6002020000:
		*s = SearchJobsArea6002020000
		return nil
	case SearchJobsArea6002021000:
		*s = SearchJobsArea6002021000
		return nil
	case SearchJobsArea6002022000:
		*s = SearchJobsArea6002022000
		return nil
	case SearchJobsArea6002023000:
		*s = SearchJobsArea6002023000
		return nil
	case SearchJobsArea6002024000:
		*s = SearchJobsArea6002024000
		return nil
	case SearchJobsArea6002025000:
		*s = SearchJobsArea6002025000
		return nil
	case SearchJobsArea6002026000:
		*s = SearchJobsArea6002026000
		return nil
	case SearchJobsArea6002027000:
		*s = SearchJobsArea6002027000
		return nil
	case SearchJobsArea6002028000:
		*s = SearchJobsArea6002028000
		return nil
	case SearchJobsArea6002029000:
		*s = SearchJobsArea6002029000
		return nil
	case SearchJobsArea6002030000:
		*s = SearchJobsArea6002030000
		return nil
	case SearchJobsArea6002031000:
		*s = SearchJobsArea6002031000
		return nil
	case SearchJobsArea6002032000:
		*s = SearchJobsArea6002032000
		return nil
	case SearchJobsArea6002033000:
		*s = SearchJobsArea6002033000
		return nil
	case SearchJobsArea6003001000:
		*s = SearchJobsArea6003001000
		return nil
	case SearchJobsArea6003002000:
		*s = SearchJobsArea6003002000
		return nil
	case SearchJobsArea6003003000:
		*s = SearchJobsArea6003003000
		return nil
	case SearchJobsArea6004001000:
		*s = SearchJobsArea6004001000
		return nil
	case SearchJobsArea6004002000:
		*s = SearchJobsArea6004002000
		return nil
	case SearchJobsArea6005001000:
		*s = SearchJobsArea6005001000
		return nil
	case SearchJobsArea6005002000:
		*s = SearchJobsArea6005002000
		return nil
	case SearchJobsArea6005003000:
		*s = SearchJobsArea6005003000
		return nil
	case SearchJobsArea6005004000:
		*s = SearchJobsArea6005004000
		return nil
	case SearchJobsArea6006001000:
		*s = SearchJobsArea6006001000
		return nil
	case SearchJobsArea6006002000:
		*s = SearchJobsArea6006002000
		return nil
	case SearchJobsArea6007001000:
		*s = SearchJobsArea6007001000
		return nil
	case SearchJobsArea6007002000:
		*s = SearchJobsArea6007002000
		return nil
	case SearchJobsArea6007003000:
		*s = SearchJobsArea6007003000
		return nil
	case SearchJobsArea6007004000:
		*s = SearchJobsArea6007004000
		return nil
	case SearchJobsArea6007005000:
		*s = SearchJobsArea6007005000
		return nil
	case SearchJobsArea6008001000:
		*s = SearchJobsArea6008001000
		return nil
	case SearchJobsArea6008002000:
		*s = SearchJobsArea6008002000
		return nil
	case SearchJobsArea6008003000:
		*s = SearchJobsArea6008003000
		return nil
	case SearchJobsArea6008004000:
		*s = SearchJobsArea6008004000
		return nil
	case SearchJobsArea6008005000:
		*s = SearchJobsArea6008005000
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type SearchJobsEduItem int

const (
	SearchJobsEduItem1 SearchJobsEduItem = 1
	SearchJobsEduItem2 SearchJobsEduItem = 2
	SearchJobsEduItem3 SearchJobsEduItem = 3
	SearchJobsEduItem4 SearchJobsEduItem = 4
	SearchJobsEduItem5 SearchJobsEduItem = 5
	SearchJobsEduItem6 SearchJobsEduItem = 6
)

// AllValues returns all SearchJobsEduItem values.
func (SearchJobsEduItem) AllValues() []SearchJobsEduItem {
	return []SearchJobsEduItem{
		SearchJobsEduItem1,
		SearchJobsEduItem2,
		SearchJobsEduItem3,
		SearchJobsEduItem4,
		SearchJobsEduItem5,
		SearchJobsEduItem6,
	}
}

type SearchJobsJobexpItem int

const (
	SearchJobsJobexpItem1  SearchJobsJobexpItem = 1
	SearchJobsJobexpItem3  SearchJobsJobexpItem = 3
	SearchJobsJobexpItem5  SearchJobsJobexpItem = 5
	SearchJobsJobexpItem10 SearchJobsJobexpItem = 10
	SearchJobsJobexpItem99 SearchJobsJobexpItem = 99
)

// AllValues returns all SearchJobsJobexpItem values.
func (SearchJobsJobexpItem) AllValues() []SearchJobsJobexpItem {
	return []SearchJobsJobexpItem{
		SearchJobsJobexpItem1,
		SearchJobsJobexpItem3,
		SearchJobsJobexpItem5,
		SearchJobsJobexpItem10,
		SearchJobsJobexpItem99,
	}
}

type SearchJobsOrder int

const (
	SearchJobsOrder1  SearchJobsOrder = 1
	SearchJobsOrder2  SearchJobsOrder = 2
	SearchJobsOrder13 SearchJobsOrder = 13
)

// AllValues returns all SearchJobsOrder values.
func (SearchJobsOrder) AllValues() []SearchJobsOrder {
	return []SearchJobsOrder{
		SearchJobsOrder1,
		SearchJobsOrder2,
		SearchJobsOrder13,
	}
}

type SearchJobsRemoteWork int

const (
	SearchJobsRemoteWork1 SearchJobsRemoteWork = 1
	SearchJobsRemoteWork2 SearchJobsRemoteWork = 2
)

// AllValues returns all SearchJobsRemoteWork values.
func (SearchJobsRemoteWork) AllValues() []SearchJobsRemoteWork {
	return []SearchJobsRemoteWork{
		SearchJobsRemoteWork1,
		SearchJobsRemoteWork2,
	}
}

type SearchJobsRo int

const (
	SearchJobsRo1 SearchJobsRo = 1
	SearchJobsRo2 SearchJobsRo = 2
	SearchJobsRo3 SearchJobsRo = 3
	SearchJobsRo4 SearchJobsRo = 4
)

// AllValues returns all SearchJobsRo values.
func (SearchJobsRo) AllValues() []SearchJobsRo {
	return []SearchJobsRo{
		SearchJobsRo1,
		SearchJobsRo2,
		SearchJobsRo3,
		SearchJobsRo4,
	}
}

type SearchJobsS9Item int

const (
	SearchJobsS9Item1 SearchJobsS9Item = 1
	SearchJobsS9Item2 SearchJobsS9Item = 2
	SearchJobsS9Item4 SearchJobsS9Item = 4
	SearchJobsS9Item8 SearchJobsS9Item = 8
)

// AllValues returns all SearchJobsS9Item values.
func (SearchJobsS9Item) AllValues() []SearchJobsS9Item {
	return []SearchJobsS9Item{
		SearchJobsS9Item1,
		SearchJobsS9Item2,
		SearchJobsS9Item4,
		SearchJobsS9Item8,
	}
}
