// Code generated by ogen, DO NOT EDIT.

package job104

import (
	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s *JobsResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Data == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SearchJobsArea) Validate() error {
	switch s {
	case "6001001000":
		return nil
	case "6001002000":
		return nil
	case "6001003000":
		return nil
	case "6001004000":
		return nil
	case "6001005000":
		return nil
	case "6001006000":
		return nil
	case "6001007000":
		return nil
	case "6001008000":
		return nil
	case "6001010000":
		return nil
	case "6001011000":
		return nil
	case "6001012000":
		return nil
	case "6001013000":
		return nil
	case "6001014000":
		return nil
	case "6001016000":
		return nil
	case "6001018000":
		return nil
	case "6001019000":
		return nil
	case "6001020000":
		return nil
	case "6001021000":
		return nil
	case "6001022000":
		return nil
	case "6001023000":
		return nil
	case "6002001000":
		return nil
	case "6002002000":
		return nil
	case "6002003000":
		return nil
	case "6002004000":
		return nil
	case "6002005000":
		return nil
	case "6002006000":
		return nil
	case "6002007000":
		return nil
	case "6002008000":
		return nil
	case "6002009000":
		return nil
	case "6002010000":
		return nil
	case "6002011000":
		return nil
	case "6002012000":
		return nil
	case "6002013000":
		return nil
	case "6002014000":
		return nil
	case "6002015000":
		return nil
	case "6002016000":
		return nil
	case "6002017000":
		return nil
	case "6002018000":
		return nil
	case "6002019000":
		return nil
	case "6002020000":
		return nil
	case "6002021000":
		return nil
	case "6002022000":
		return nil
	case "6002023000":
		return nil
	case "6002024000":
		return nil
	case "6002025000":
		return nil
	case "6002026000":
		return nil
	case "6002027000":
		return nil
	case "6002028000":
		return nil
	case "6002029000":
		return nil
	case "6002030000":
		return nil
	case "6002031000":
		return nil
	case "6002032000":
		return nil
	case "6002033000":
		return nil
	case "6003001000":
		return nil
	case "6003002000":
		return nil
	case "6003003000":
		return nil
	case "6004001000":
		return nil
	case "6004002000":
		return nil
	case "6005001000":
		return nil
	case "6005002000":
		return nil
	case "6005003000":
		return nil
	case "6005004000":
		return nil
	case "6006001000":
		return nil
	case "6006002000":
		return nil
	case "6007001000":
		return nil
	case "6007002000":
		return nil
	case "6007003000":
		return nil
	case "6007004000":
		return nil
	case "6007005000":
		return nil
	case "6008001000":
		return nil
	case "6008002000":
		return nil
	case "6008003000":
		return nil
	case "6008004000":
		return nil
	case "6008005000":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s SearchJobsEduItem) Validate() error {
	switch s {
	case 1:
		return nil
	case 2:
		return nil
	case 3:
		return nil
	case 4:
		return nil
	case 5:
		return nil
	case 6:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s SearchJobsJobexpItem) Validate() error {
	switch s {
	case 1:
		return nil
	case 3:
		return nil
	case 5:
		return nil
	case 10:
		return nil
	case 99:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s SearchJobsOrder) Validate() error {
	switch s {
	case 1:
		return nil
	case 2:
		return nil
	case 13:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s SearchJobsRemoteWork) Validate() error {
	switch s {
	case 1:
		return nil
	case 2:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s SearchJobsRo) Validate() error {
	switch s {
	case 1:
		return nil
	case 2:
		return nil
	case 3:
		return nil
	case 4:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s SearchJobsS9Item) Validate() error {
	switch s {
	case 1:
		return nil
	case 2:
		return nil
	case 4:
		return nil
	case 8:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
