// Code generated by ogen, DO NOT EDIT.

package remoteok

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetJobs implements getJobs operation.
	//
	// Without `tags`, the window is the ~100 most recent jobs overall. With `tags`, it is the ~100 most
	// recent jobs matching the tag set, which can include jobs older than the unfiltered window — so a
	// job found via a tag search is not guaranteed to appear in the plain dump.
	//
	// GET /api
	GetJobs(ctx context.Context, params GetJobsParams) (Feed, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
