// Code generated by ogen, DO NOT EDIT.

package nvidia

import (
	"math/bits"
	"strconv"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/validate"
)

// Encode implements json.Marshaler.
func (s *AppliedFacets) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *AppliedFacets) encodeFields(e *jx.Encoder) {
	{
		if s.JobFamilyGroup != nil {
			e.FieldStart("jobFamilyGroup")
			e.ArrStart()
			for _, elem := range s.JobFamilyGroup {
				elem.Encode(e)
			}
			e.ArrEnd()
		}
	}
	{
		if s.WorkerSubType != nil {
			e.FieldStart("workerSubType")
			e.ArrStart()
			for _, elem := range s.WorkerSubType {
				elem.Encode(e)
			}
			e.ArrEnd()
		}
	}
	{
		if s.TimeType != nil {
			e.FieldStart("timeType")
			e.ArrStart()
			for _, elem := range s.TimeType {
				elem.Encode(e)
			}
			e.ArrEnd()
		}
	}
	{
		if s.LocationHierarchy2 != nil {
			e.FieldStart("locationHierarchy2")
			e.ArrStart()
			for _, elem := range s.LocationHierarchy2 {
				elem.Encode(e)
			}
			e.ArrEnd()
		}
	}
	{
		if s.LocationHierarchy1 != nil {
			e.FieldStart("locationHierarchy1")
			e.ArrStart()
			for _, elem := range s.LocationHierarchy1 {
				elem.Encode(e)
			}
			e.ArrEnd()
		}
	}
	{
		if s.Locations != nil {
			e.FieldStart("locations")
			e.ArrStart()
			for _, elem := range s.Locations {
				elem.Encode(e)
			}
			e.ArrEnd()
		}
	}
}

var jsonFieldsNameOfAppliedFacets = [6]string{
	0: "jobFamilyGroup",
	1: "workerSubType",
	2: "timeType",
	3: "locationHierarchy2",
	4: "locationHierarchy1",
	5: "locations",
}

// Decode decodes AppliedFacets from json.
func (s *AppliedFacets) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode AppliedFacets to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "jobFamilyGroup":
			if err := func() error {
				s.JobFamilyGroup = make([]AppliedFacetsJobFamilyGroupItem, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem AppliedFacetsJobFamilyGroupItem
					if err := elem.Decode(d); err != nil {
						return err
					}
					s.JobFamilyGroup = append(s.JobFamilyGroup, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"jobFamilyGroup\"")
			}
		case "workerSubType":
			if err := func() error {
				s.WorkerSubType = make([]AppliedFacetsWorkerSubTypeItem, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem AppliedFacetsWorkerSubTypeItem
					if err := elem.Decode(d); err != nil {
						return err
					}
					s.WorkerSubType = append(s.WorkerSubType, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workerSubType\"")
			}
		case "timeType":
			if err := func() error {
				s.TimeType = make([]AppliedFacetsTimeTypeItem, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem AppliedFacetsTimeTypeItem
					if err := elem.Decode(d); err != nil {
						return err
					}
					s.TimeType = append(s.TimeType, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"timeType\"")
			}
		case "locationHierarchy2":
			if err := func() error {
				s.LocationHierarchy2 = make([]AppliedFacetsLocationHierarchy2Item, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem AppliedFacetsLocationHierarchy2Item
					if err := elem.Decode(d); err != nil {
						return err
					}
					s.LocationHierarchy2 = append(s.LocationHierarchy2, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"locationHierarchy2\"")
			}
		case "locationHierarchy1":
			if err := func() error {
				s.LocationHierarchy1 = make([]AppliedFacetsLocationHierarchy1Item, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem AppliedFacetsLocationHierarchy1Item
					if err := elem.Decode(d); err != nil {
						return err
					}
					s.LocationHierarchy1 = append(s.LocationHierarchy1, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"locationHierarchy1\"")
			}
		case "locations":
			if err := func() error {
				s.Locations = make([]AppliedFacetsLocationsItem, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem AppliedFacetsLocationsItem
					if err := elem.Decode(d); err != nil {
						return err
					}
					s.Locations = append(s.Locations, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"locations\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode AppliedFacets")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *AppliedFacets) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *AppliedFacets) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes AppliedFacetsJobFamilyGroupItem as json.
func (s AppliedFacetsJobFamilyGroupItem) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes AppliedFacetsJobFamilyGroupItem from json.
func (s *AppliedFacetsJobFamilyGroupItem) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode AppliedFacetsJobFamilyGroupItem to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch AppliedFacetsJobFamilyGroupItem(v) {
	case AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffaefd46dc7e78:
		*s = AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffaefd46dc7e78
	case AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffcac5bbec7e90:
		*s = AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffcac5bbec7e90
	case AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffc3fc7d8c7e8a:
		*s = AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffc3fc7d8c7e8a
	case AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffc668c6847e8c:
		*s = AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffc668c6847e8c
	case AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffc19725ec7e88:
		*s = AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffc19725ec7e88
	case AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffc8817cf47e8e:
		*s = AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffc8817cf47e8e
	case AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffbd1459047e84:
		*s = AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffbd1459047e84
	case AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffda1e8d447e94:
		*s = AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffda1e8d447e94
	case AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffb5dd06f47e7e:
		*s = AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffb5dd06f47e7e
	case AppliedFacetsJobFamilyGroupItemE8bdc341a93101bd5f4d2b0a1c005e36:
		*s = AppliedFacetsJobFamilyGroupItemE8bdc341a93101bd5f4d2b0a1c005e36
	case AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffbac3680c7e82:
		*s = AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffbac3680c7e82
	case AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffbf4412147e86:
		*s = AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffbf4412147e86
	case AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffb3a6aaac7e7c:
		*s = AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffb3a6aaac7e7c
	case AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffac5fdfac7e76:
		*s = AppliedFacetsJobFamilyGroupItem0c40f6bd1d8f10ae43ffac5fdfac7e76
	default:
		*s = AppliedFacetsJobFamilyGroupItem(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s AppliedFacetsJobFamilyGroupItem) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *AppliedFacetsJobFamilyGroupItem) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes AppliedFacetsLocationHierarchy1Item as json.
func (s AppliedFacetsLocationHierarchy1Item) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes AppliedFacetsLocationHierarchy1Item from json.
func (s *AppliedFacetsLocationHierarchy1Item) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode AppliedFacetsLocationHierarchy1Item to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch AppliedFacetsLocationHierarchy1Item(v) {
	case AppliedFacetsLocationHierarchy1ItemD21cf68980ad0128000fd2c6b107c000:
		*s = AppliedFacetsLocationHierarchy1ItemD21cf68980ad0128000fd2c6b107c000
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea528dce556b3224:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea528dce556b3224
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea5298c9e1f63230:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea5298c9e1f63230
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea529c3b93ba3236:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea529c3b93ba3236
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea529fe151e3323c:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea529fe151e3323c
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52a358b3d53242:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52a358b3d53242
	case AppliedFacetsLocationHierarchy1ItemD21cf68980ad0121a67d319db107a200:
		*s = AppliedFacetsLocationHierarchy1ItemD21cf68980ad0121a67d319db107a200
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52a6cbc15f3248:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52a6cbc15f3248
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52aa2df70e324e:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52aa2df70e324e
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52adc65f5d3254:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52adc65f5d3254
	case AppliedFacetsLocationHierarchy1ItemC498fba66f4e01b7b7931c0fd400ab04:
		*s = AppliedFacetsLocationHierarchy1ItemC498fba66f4e01b7b7931c0fd400ab04
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52b157d0d6325a:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52b157d0d6325a
	case AppliedFacetsLocationHierarchy1Item7bcfe8379f6b01ad4d347d1ca87689a6:
		*s = AppliedFacetsLocationHierarchy1Item7bcfe8379f6b01ad4d347d1ca87689a6
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52b82135ba3266:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52b82135ba3266
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52bbe14cf9326c:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52bbe14cf9326c
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52bf52796c3272:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52bf52796c3272
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52c29d2e923278:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52c29d2e923278
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52c61ded6e327e:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52c61ded6e327e
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52cd244532328a:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52cd244532328a
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52d0e0e4583290:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52d0e0e4583290
	case AppliedFacetsLocationHierarchy1Item970bf8c909a701f9c086d363d300fa06:
		*s = AppliedFacetsLocationHierarchy1Item970bf8c909a701f9c086d363d300fa06
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52d8783aa0329c:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52d8783aa0329c
	case AppliedFacetsLocationHierarchy1ItemE5375aecc8d9103bebfb513cb69200d4:
		*s = AppliedFacetsLocationHierarchy1ItemE5375aecc8d9103bebfb513cb69200d4
	case AppliedFacetsLocationHierarchy1ItemE4c3fe651a5b01ddbafb67d7d001b447:
		*s = AppliedFacetsLocationHierarchy1ItemE4c3fe651a5b01ddbafb67d7d001b447
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52df1adb7432a8:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52df1adb7432a8
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52e31a43e832ae:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52e31a43e832ae
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52e6c3067832b4:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52e6c3067832b4
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52e9ef1a0032ba:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52e9ef1a0032ba
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52ed162d4932c0:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52ed162d4932c0
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52f07ea4c732c6:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52f07ea4c732c6
	case AppliedFacetsLocationHierarchy1Item970bf8c909a7012c3733f063d3000107:
		*s = AppliedFacetsLocationHierarchy1Item970bf8c909a7012c3733f063d3000107
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52f3d5d2c232cc:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52f3d5d2c232cc
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52f785717432d2:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52f785717432d2
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52fb338f2932d8:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52fb338f2932d8
	case AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52fea3f8d732de:
		*s = AppliedFacetsLocationHierarchy1Item2fcb99c455831013ea52fea3f8d732de
	default:
		*s = AppliedFacetsLocationHierarchy1Item(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s AppliedFacetsLocationHierarchy1Item) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *AppliedFacetsLocationHierarchy1Item) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes AppliedFacetsLocationHierarchy2Item as json.
func (s AppliedFacetsLocationHierarchy2Item) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes AppliedFacetsLocationHierarchy2Item from json.
func (s *AppliedFacetsLocationHierarchy2Item) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode AppliedFacetsLocationHierarchy2Item to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch AppliedFacetsLocationHierarchy2Item(v) {
	case AppliedFacetsLocationHierarchy2Item0c3f5f117e9a0101f6422f0fe79d0000:
		*s = AppliedFacetsLocationHierarchy2Item0c3f5f117e9a0101f6422f0fe79d0000
	case AppliedFacetsLocationHierarchy2Item0c3f5f117e9a0101f63dc469c3010000:
		*s = AppliedFacetsLocationHierarchy2Item0c3f5f117e9a0101f63dc469c3010000
	default:
		*s = AppliedFacetsLocationHierarchy2Item(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s AppliedFacetsLocationHierarchy2Item) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *AppliedFacetsLocationHierarchy2Item) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes AppliedFacetsLocationsItem as json.
func (s AppliedFacetsLocationsItem) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes AppliedFacetsLocationsItem from json.
func (s *AppliedFacetsLocationsItem) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode AppliedFacetsLocationsItem to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch AppliedFacetsLocationsItem(v) {
	case AppliedFacetsLocationsItemC0ed409f79231000eaff724467330000:
		*s = AppliedFacetsLocationsItemC0ed409f79231000eaff724467330000
	case AppliedFacetsLocationsItem91336993fab910af6d70362ab49cc2f7:
		*s = AppliedFacetsLocationsItem91336993fab910af6d70362ab49cc2f7
	case AppliedFacetsLocationsItem0d86a8e04eda011538f0ac5d90019611:
		*s = AppliedFacetsLocationsItem0d86a8e04eda011538f0ac5d90019611
	case AppliedFacetsLocationsItem91336993fab910af6d7115f6c23cc357:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7115f6c23cc357
	case AppliedFacetsLocationsItem91336993fab910af6d7113d4a58cc352:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7113d4a58cc352
	case AppliedFacetsLocationsItem91336993fab910af6d7111b9ef64c34d:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7111b9ef64c34d
	case AppliedFacetsLocationsItem4205b8279d1110811b5e0a9820d6693a:
		*s = AppliedFacetsLocationsItem4205b8279d1110811b5e0a9820d6693a
	case AppliedFacetsLocationsItem91336993fab910af6d710912773cc339:
		*s = AppliedFacetsLocationsItem91336993fab910af6d710912773cc339
	case AppliedFacetsLocationsItemA91ba405af43014cbf6c6d9e38015a54:
		*s = AppliedFacetsLocationsItemA91ba405af43014cbf6c6d9e38015a54
	case AppliedFacetsLocationsItemB4fd8272c6061070475410ad248007f0:
		*s = AppliedFacetsLocationsItemB4fd8272c6061070475410ad248007f0
	case AppliedFacetsLocationsItem91336993fab910af6d710b3449b4c33e:
		*s = AppliedFacetsLocationsItem91336993fab910af6d710b3449b4c33e
	case AppliedFacetsLocationsItem91336993fab910af6d7106eea8f4c334:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7106eea8f4c334
	case AppliedFacetsLocationsItem91336993fab910af6d70ecbaa6f4c2fd:
		*s = AppliedFacetsLocationsItem91336993fab910af6d70ecbaa6f4c2fd
	case AppliedFacetsLocationsItemC498fba66f4e01c0944dde87d5005f05:
		*s = AppliedFacetsLocationsItemC498fba66f4e01c0944dde87d5005f05
	case AppliedFacetsLocationsItem91336993fab910af6d6fdb4a260cc22a:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fdb4a260cc22a
	case AppliedFacetsLocationsItem91336993fab910af6d6fd9177efcc225:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fd9177efcc225
	case AppliedFacetsLocationsItem91336993fab910af6d6fd25f3c44c216:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fd25f3c44c216
	case AppliedFacetsLocationsItem91336993fab910af6d6fd6c8476cc220:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fd6c8476cc220
	case AppliedFacetsLocationsItem91336993fab910af6d6fc2799054c1f3:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fc2799054c1f3
	case AppliedFacetsLocationsItem91336993fab910af6d6fc4f707bcc1f8:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fc4f707bcc1f8
	case AppliedFacetsLocationsItem91336993fab910af6d6fc96a405cc202:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fc96a405cc202
	case AppliedFacetsLocationsItem91336993fab910af6d6fc737d3e4c1fd:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fc737d3e4c1fd
	case AppliedFacetsLocationsItemD01f8704a10b0121fa6766dd38019c82:
		*s = AppliedFacetsLocationsItemD01f8704a10b0121fa6766dd38019c82
	case AppliedFacetsLocationsItem91336993fab910af6d6fc02e0a14c1ee:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fc02e0a14c1ee
	case AppliedFacetsLocationsItemFc94d97a3a280100b73f626fd1610000:
		*s = AppliedFacetsLocationsItemFc94d97a3a280100b73f626fd1610000
	case AppliedFacetsLocationsItem7bcfe8379f6b017176531c86a87649a7:
		*s = AppliedFacetsLocationsItem7bcfe8379f6b017176531c86a87649a7
	case AppliedFacetsLocationsItem91336993fab910af6d6fb9748af4c1df:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fb9748af4c1df
	case AppliedFacetsLocationsItemF28ae3c49d2601aff203e114d301695f:
		*s = AppliedFacetsLocationsItemF28ae3c49d2601aff203e114d301695f
	case AppliedFacetsLocationsItem91336993fab910af6d6fb2be0974c1d0:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fb2be0974c1d0
	case AppliedFacetsLocationsItem91336993fab910af6d6fabbb968cc1c1:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fabbb968cc1c1
	case AppliedFacetsLocationsItem91336993fab910af6d6fb0782884c1cb:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fb0782884c1cb
	case AppliedFacetsLocationsItem91336993fab910af6d6fb4ee7634c1d5:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fb4ee7634c1d5
	case AppliedFacetsLocationsItem970bf8c909a701bb080521ddd400ae07:
		*s = AppliedFacetsLocationsItem970bf8c909a701bb080521ddd400ae07
	case AppliedFacetsLocationsItem970bf8c909a7013ea54a57dcd4008107:
		*s = AppliedFacetsLocationsItem970bf8c909a7013ea54a57dcd4008107
	case AppliedFacetsLocationsItemC7769ee377291036b08490819096b8bf:
		*s = AppliedFacetsLocationsItemC7769ee377291036b08490819096b8bf
	case AppliedFacetsLocationsItem970bf8c909a7016a7d893ddcd4007c07:
		*s = AppliedFacetsLocationsItem970bf8c909a7016a7d893ddcd4007c07
	case AppliedFacetsLocationsItem970bf8c909a701c749f87bdcd4008607:
		*s = AppliedFacetsLocationsItem970bf8c909a701c749f87bdcd4008607
	case AppliedFacetsLocationsItem91336993fab910af6d6fa203fa6cc1ad:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fa203fa6cc1ad
	case AppliedFacetsLocationsItemB00b3256ed551015d42d2bebe06b02b7:
		*s = AppliedFacetsLocationsItemB00b3256ed551015d42d2bebe06b02b7
	case AppliedFacetsLocationsItem91336993fab910af6d6f9a47b91cc19e:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f9a47b91cc19e
	case AppliedFacetsLocationsItem91336993fab910af6d71963a259cc46f:
		*s = AppliedFacetsLocationsItem91336993fab910af6d71963a259cc46f
	case AppliedFacetsLocationsItem91336993fab910af6d6f3f56714cc112:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f3f56714cc112
	case AppliedFacetsLocationsItem91336993fab910af6d6f97e94b04c199:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f97e94b04c199
	case AppliedFacetsLocationsItem42289dda31210100f43ca5dad0ff0000:
		*s = AppliedFacetsLocationsItem42289dda31210100f43ca5dad0ff0000
	case AppliedFacetsLocationsItem5f84e8157c6a101b415772d270da2de1:
		*s = AppliedFacetsLocationsItem5f84e8157c6a101b415772d270da2de1
	case AppliedFacetsLocationsItem30350996b69b01a7dbccf4403c0174a8:
		*s = AppliedFacetsLocationsItem30350996b69b01a7dbccf4403c0174a8
	case AppliedFacetsLocationsItem91336993fab910af6d6f931ae68cc18f:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f931ae68cc18f
	case AppliedFacetsLocationsItem811700f7388d0103b8ceed030d490e48:
		*s = AppliedFacetsLocationsItem811700f7388d0103b8ceed030d490e48
	case AppliedFacetsLocationsItemBf8aa7d10cd61000fb56e1988f3b0000:
		*s = AppliedFacetsLocationsItemBf8aa7d10cd61000fb56e1988f3b0000
	case AppliedFacetsLocationsItem5f84e8157c6a101b435468d5d0e34bd9:
		*s = AppliedFacetsLocationsItem5f84e8157c6a101b435468d5d0e34bd9
	case AppliedFacetsLocationsItemE4c3fe651a5b01f48e294d9ad1015e4b:
		*s = AppliedFacetsLocationsItemE4c3fe651a5b01f48e294d9ad1015e4b
	case AppliedFacetsLocationsItem91336993fab910af6d6f8a1a368cc17b:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f8a1a368cc17b
	case AppliedFacetsLocationsItemC498fba66f4e01971ba26688d5008705:
		*s = AppliedFacetsLocationsItemC498fba66f4e01971ba26688d5008705
	case AppliedFacetsLocationsItem91336993fab910af6d6f87de293cc176:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f87de293cc176
	case AppliedFacetsLocationsItemC18da66b8c3f01e4f8939069de3534f8:
		*s = AppliedFacetsLocationsItemC18da66b8c3f01e4f8939069de3534f8
	case AppliedFacetsLocationsItem91336993fab910af6d6f859de1e4c171:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f859de1e4c171
	case AppliedFacetsLocationsItem91336993fab910af6d6f8342ac04c16c:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f8342ac04c16c
	case AppliedFacetsLocationsItem91336993fab910af6d6f7e35a07cc162:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f7e35a07cc162
	case AppliedFacetsLocationsItem91336993fab910af6d6f80c09504c167:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f80c09504c167
	case AppliedFacetsLocationsItem91336993fab910af6d6f7933b49cc158:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f7933b49cc158
	case AppliedFacetsLocationsItem91336993fab910af6d6f56c5409cc13f:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f56c5409cc13f
	case AppliedFacetsLocationsItem91336993fab910af6d6f5eaae3acc14e:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f5eaae3acc14e
	case AppliedFacetsLocationsItemF57d67c891a11057224421d76bc979ab:
		*s = AppliedFacetsLocationsItemF57d67c891a11057224421d76bc979ab
	case AppliedFacetsLocationsItem91336993fab910af6d6f516bf58cc135:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f516bf58cc135
	case AppliedFacetsLocationsItem970bf8c909a7015f56c618ded400e007:
		*s = AppliedFacetsLocationsItem970bf8c909a7015f56c618ded400e007
	case AppliedFacetsLocationsItem91336993fab910af6d6f41d01ff4c117:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f41d01ff4c117
	case AppliedFacetsLocationsItem91336993fab910af6d6f445436acc11c:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f445436acc11c
	case AppliedFacetsLocationsItem91336993fab910af6d6f4c211db4c12b:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f4c211db4c12b
	case AppliedFacetsLocationsItem91336993fab910af6d6f4954559cc126:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6f4954559cc126
	case AppliedFacetsLocationsItem970bf8c909a701acf1aa08ded400db07:
		*s = AppliedFacetsLocationsItem970bf8c909a701acf1aa08ded400db07
	case AppliedFacetsLocationsItem970bf8c909a70104bdbe3eddd400bd07:
		*s = AppliedFacetsLocationsItem970bf8c909a70104bdbe3eddd400bd07
	case AppliedFacetsLocationsItem91336993fab910af6d7140d48764c3b6:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7140d48764c3b6
	case AppliedFacetsLocationsItem91336993fab910af6d7170a1a684c41f:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7170a1a684c41f
	case AppliedFacetsLocationsItemDf27165dab550120b41aa51fc701619d:
		*s = AppliedFacetsLocationsItemDf27165dab550120b41aa51fc701619d
	case AppliedFacetsLocationsItem91336993fab910af6d7013ca699cc2a7:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7013ca699cc2a7
	case AppliedFacetsLocationsItem91336993fab910af6d716528e9d4c406:
		*s = AppliedFacetsLocationsItem91336993fab910af6d716528e9d4c406
	case AppliedFacetsLocationsItem895d7243647101d8c9619dd37377338f:
		*s = AppliedFacetsLocationsItem895d7243647101d8c9619dd37377338f
	case AppliedFacetsLocationsItem91336993fab910af6d702fae0bb4c2e8:
		*s = AppliedFacetsLocationsItem91336993fab910af6d702fae0bb4c2e8
	case AppliedFacetsLocationsItem91336993fab910af6d712ddeebf4c38e:
		*s = AppliedFacetsLocationsItem91336993fab910af6d712ddeebf4c38e
	case AppliedFacetsLocationsItem91336993fab910af6d716c1bb8d4c415:
		*s = AppliedFacetsLocationsItem91336993fab910af6d716c1bb8d4c415
	case AppliedFacetsLocationsItem91336993fab910af6d715e41b394c3f7:
		*s = AppliedFacetsLocationsItem91336993fab910af6d715e41b394c3f7
	case AppliedFacetsLocationsItem91336993fab910af6d713a0f5044c3a7:
		*s = AppliedFacetsLocationsItem91336993fab910af6d713a0f5044c3a7
	case AppliedFacetsLocationsItem851660e123f40195e5fbfb9dce1137a2:
		*s = AppliedFacetsLocationsItem851660e123f40195e5fbfb9dce1137a2
	case AppliedFacetsLocationsItem91336993fab910af6d7020bf3b14c2c5:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7020bf3b14c2c5
	case AppliedFacetsLocationsItem91336993fab910af6d6fe4b908fcc23e:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fe4b908fcc23e
	case AppliedFacetsLocationsItem3f056d7dcee210447f581d1002c2e672:
		*s = AppliedFacetsLocationsItem3f056d7dcee210447f581d1002c2e672
	case AppliedFacetsLocationsItem91336993fab910af6d714794d4b4c3c5:
		*s = AppliedFacetsLocationsItem91336993fab910af6d714794d4b4c3c5
	case AppliedFacetsLocationsItem91336993fab910af6d702d89918cc2e3:
		*s = AppliedFacetsLocationsItem91336993fab910af6d702d89918cc2e3
	case AppliedFacetsLocationsItem91336993fab910af6d7008ff1774c28e:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7008ff1774c28e
	case AppliedFacetsLocationsItem91336993fab910af6d719855647cc474:
		*s = AppliedFacetsLocationsItem91336993fab910af6d719855647cc474
	case AppliedFacetsLocationsItem91336993fab910af6d6fe9a03534c248:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fe9a03534c248
	case AppliedFacetsLocationsItem91336993fab910af6d700b282d4cc293:
		*s = AppliedFacetsLocationsItem91336993fab910af6d700b282d4cc293
	case AppliedFacetsLocationsItem91336993fab910af6d7130bb158cc393:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7130bb158cc393
	case AppliedFacetsLocationsItem91336993fab910af6d7022e347dcc2ca:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7022e347dcc2ca
	case AppliedFacetsLocationsItem91336993fab910af6d7006cdf31cc289:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7006cdf31cc289
	case AppliedFacetsLocationsItem91336993fab910af6d6ffd32b89cc275:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6ffd32b89cc275
	case AppliedFacetsLocationsItem91336993fab910af6d7152b6749cc3de:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7152b6749cc3de
	case AppliedFacetsLocationsItem91336993fab910af6d712b900a54c389:
		*s = AppliedFacetsLocationsItem91336993fab910af6d712b900a54c389
	case AppliedFacetsLocationsItem91336993fab910af6d7015dee21cc2ac:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7015dee21cc2ac
	case AppliedFacetsLocationsItemD2088e737cbb01293f745dc7ce017070:
		*s = AppliedFacetsLocationsItemD2088e737cbb01293f745dc7ce017070
	case AppliedFacetsLocationsItem91336993fab910af6d6ff2800b0cc25c:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6ff2800b0cc25c
	case AppliedFacetsLocationsItem91336993fab910af6d700d4fc83cc298:
		*s = AppliedFacetsLocationsItem91336993fab910af6d700d4fc83cc298
	case AppliedFacetsLocationsItem91336993fab910af6d7027195454c2d4:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7027195454c2d4
	case AppliedFacetsLocationsItem91336993fab910af6d6ff05591bcc257:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6ff05591bcc257
	case AppliedFacetsLocationsItem91336993fab910af6d700193f3c4c27f:
		*s = AppliedFacetsLocationsItem91336993fab910af6d700193f3c4c27f
	case AppliedFacetsLocationsItem16fc4607fc4310011e929f7115f90000:
		*s = AppliedFacetsLocationsItem16fc4607fc4310011e929f7115f90000
	case AppliedFacetsLocationsItem91336993fab910af6d6ffb099324c270:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6ffb099324c270
	case AppliedFacetsLocationsItem91336993fab910af6d7122ef682cc375:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7122ef682cc375
	case AppliedFacetsLocationsItem91336993fab910af6d702b631b94c2de:
		*s = AppliedFacetsLocationsItem91336993fab910af6d702b631b94c2de
	case AppliedFacetsLocationsItem10b0744835e11001030c2489586f0000:
		*s = AppliedFacetsLocationsItem10b0744835e11001030c2489586f0000
	case AppliedFacetsLocationsItem91336993fab910af6d702939a7fcc2d9:
		*s = AppliedFacetsLocationsItem91336993fab910af6d702939a7fcc2d9
	case AppliedFacetsLocationsItem91336993fab910af6d6fee30ae1cc252:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6fee30ae1cc252
	case AppliedFacetsLocationsItem91336993fab910af6d6ff8e9d004c26b:
		*s = AppliedFacetsLocationsItem91336993fab910af6d6ff8e9d004c26b
	case AppliedFacetsLocationsItemC498fba66f4e012b5a8a2e88d5007805:
		*s = AppliedFacetsLocationsItemC498fba66f4e012b5a8a2e88d5007805
	case AppliedFacetsLocationsItem91336993fab910af6d7159be65c4c3ed:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7159be65c4c3ed
	case AppliedFacetsLocationsItem91336993fab910af6d701e82d004c2c0:
		*s = AppliedFacetsLocationsItem91336993fab910af6d701e82d004c2c0
	case AppliedFacetsLocationsItem91336993fab910af6d7169a81124c410:
		*s = AppliedFacetsLocationsItem91336993fab910af6d7169a81124c410
	case AppliedFacetsLocationsItemD2088e737cbb01d5e2be9e52ce01926f:
		*s = AppliedFacetsLocationsItemD2088e737cbb01d5e2be9e52ce01926f
	case AppliedFacetsLocationsItemDd4916e138561000a8f8afa559f50000:
		*s = AppliedFacetsLocationsItemDd4916e138561000a8f8afa559f50000
	case AppliedFacetsLocationsItem229b3d23e3f91000aa5f712809fa0000:
		*s = AppliedFacetsLocationsItem229b3d23e3f91000aa5f712809fa0000
	case AppliedFacetsLocationsItem7ae28cf24c8b10874977c2d1387c19b0:
		*s = AppliedFacetsLocationsItem7ae28cf24c8b10874977c2d1387c19b0
	default:
		*s = AppliedFacetsLocationsItem(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s AppliedFacetsLocationsItem) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *AppliedFacetsLocationsItem) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes AppliedFacetsTimeTypeItem as json.
func (s AppliedFacetsTimeTypeItem) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes AppliedFacetsTimeTypeItem from json.
func (s *AppliedFacetsTimeTypeItem) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode AppliedFacetsTimeTypeItem to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch AppliedFacetsTimeTypeItem(v) {
	case AppliedFacetsTimeTypeItem5509c0b5959810ac0029943377d47364:
		*s = AppliedFacetsTimeTypeItem5509c0b5959810ac0029943377d47364
	case AppliedFacetsTimeTypeItem5509c0b5959810ac00299430e7947363:
		*s = AppliedFacetsTimeTypeItem5509c0b5959810ac00299430e7947363
	default:
		*s = AppliedFacetsTimeTypeItem(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s AppliedFacetsTimeTypeItem) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *AppliedFacetsTimeTypeItem) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes AppliedFacetsWorkerSubTypeItem as json.
func (s AppliedFacetsWorkerSubTypeItem) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes AppliedFacetsWorkerSubTypeItem from json.
func (s *AppliedFacetsWorkerSubTypeItem) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode AppliedFacetsWorkerSubTypeItem to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch AppliedFacetsWorkerSubTypeItem(v) {
	case AppliedFacetsWorkerSubTypeItem0c40f6bd1d8f10adf6dae161b1844a15:
		*s = AppliedFacetsWorkerSubTypeItem0c40f6bd1d8f10adf6dae161b1844a15
	case AppliedFacetsWorkerSubTypeItem0c40f6bd1d8f10adf6dae2cd57444a16:
		*s = AppliedFacetsWorkerSubTypeItem0c40f6bd1d8f10adf6dae2cd57444a16
	case AppliedFacetsWorkerSubTypeItemAb40a98049581037a3ada55b087049b7:
		*s = AppliedFacetsWorkerSubTypeItemAb40a98049581037a3ada55b087049b7
	case AppliedFacetsWorkerSubTypeItem0c40f6bd1d8f10adf6dae42e46d44a17:
		*s = AppliedFacetsWorkerSubTypeItem0c40f6bd1d8f10adf6dae42e46d44a17
	case AppliedFacetsWorkerSubTypeItemCc40d60d614c01809d56fe967144ce2c:
		*s = AppliedFacetsWorkerSubTypeItemCc40d60d614c01809d56fe967144ce2c
	case AppliedFacetsWorkerSubTypeItemEc9560ee6dc71001d6f3cf17ea640000:
		*s = AppliedFacetsWorkerSubTypeItemEc9560ee6dc71001d6f3cf17ea640000
	default:
		*s = AppliedFacetsWorkerSubTypeItem(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s AppliedFacetsWorkerSubTypeItem) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *AppliedFacetsWorkerSubTypeItem) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *ErrorResponse) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *ErrorResponse) encodeFields(e *jx.Encoder) {
	{
		if s.ErrorCode.Set {
			e.FieldStart("errorCode")
			s.ErrorCode.Encode(e)
		}
	}
	{
		if s.HttpStatus.Set {
			e.FieldStart("httpStatus")
			s.HttpStatus.Encode(e)
		}
	}
	{
		if s.Message.Set {
			e.FieldStart("message")
			s.Message.Encode(e)
		}
	}
	for k, elem := range s.AdditionalProps {
		e.FieldStart(k)

		if len(elem) != 0 {
			e.Raw(elem)
		}
	}
}

var jsonFieldsNameOfErrorResponse = [3]string{
	0: "errorCode",
	1: "httpStatus",
	2: "message",
}

// Decode decodes ErrorResponse from json.
func (s *ErrorResponse) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode ErrorResponse to nil")
	}
	s.AdditionalProps = map[string]jx.Raw{}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "errorCode":
			if err := func() error {
				s.ErrorCode.Reset()
				if err := s.ErrorCode.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"errorCode\"")
			}
		case "httpStatus":
			if err := func() error {
				s.HttpStatus.Reset()
				if err := s.HttpStatus.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"httpStatus\"")
			}
		case "message":
			if err := func() error {
				s.Message.Reset()
				if err := s.Message.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"message\"")
			}
		default:
			var elem jx.Raw
			if err := func() error {
				v, err := d.RawAppend(nil)
				elem = jx.Raw(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrapf(err, "decode field %q", k)
			}
			s.AdditionalProps[string(k)] = elem
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode ErrorResponse")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *ErrorResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ErrorResponse) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s ErrorResponseAdditional) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields implements json.Marshaler.
func (s ErrorResponseAdditional) encodeFields(e *jx.Encoder) {
	for k, elem := range s {
		e.FieldStart(k)

		if len(elem) != 0 {
			e.Raw(elem)
		}
	}
}

// Decode decodes ErrorResponseAdditional from json.
func (s *ErrorResponseAdditional) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode ErrorResponseAdditional to nil")
	}
	m := s.init()
	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		var elem jx.Raw
		if err := func() error {
			v, err := d.RawAppend(nil)
			elem = jx.Raw(v)
			if err != nil {
				return err
			}
			return nil
		}(); err != nil {
			return errors.Wrapf(err, "decode field %q", k)
		}
		m[string(k)] = elem
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode ErrorResponseAdditional")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s ErrorResponseAdditional) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ErrorResponseAdditional) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *JobDetailResponse) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *JobDetailResponse) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("jobPostingInfo")
		s.JobPostingInfo.Encode(e)
	}
}

var jsonFieldsNameOfJobDetailResponse = [1]string{
	0: "jobPostingInfo",
}

// Decode decodes JobDetailResponse from json.
func (s *JobDetailResponse) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode JobDetailResponse to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "jobPostingInfo":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				if err := s.JobPostingInfo.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"jobPostingInfo\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode JobDetailResponse")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00000001,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfJobDetailResponse) {
					name = jsonFieldsNameOfJobDetailResponse[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *JobDetailResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *JobDetailResponse) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *JobPostingInfo) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *JobPostingInfo) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("title")
		s.Title.Encode(e)
	}
	{
		e.FieldStart("jobDescription")
		s.JobDescription.Encode(e)
	}
	{
		if s.Location.Set {
			e.FieldStart("location")
			s.Location.Encode(e)
		}
	}
	{
		if s.AdditionalLocations != nil {
			e.FieldStart("additionalLocations")
			e.ArrStart()
			for _, elem := range s.AdditionalLocations {
				e.Str(elem)
			}
			e.ArrEnd()
		}
	}
	{
		if s.PostedOn.Set {
			e.FieldStart("postedOn")
			s.PostedOn.Encode(e)
		}
	}
	{
		if s.TimeType.Set {
			e.FieldStart("timeType")
			s.TimeType.Encode(e)
		}
	}
	{
		if s.JobReqId.Set {
			e.FieldStart("jobReqId")
			s.JobReqId.Encode(e)
		}
	}
	{
		if s.ExternalUrl.Set {
			e.FieldStart("externalUrl")
			s.ExternalUrl.Encode(e)
		}
	}
}

var jsonFieldsNameOfJobPostingInfo = [8]string{
	0: "title",
	1: "jobDescription",
	2: "location",
	3: "additionalLocations",
	4: "postedOn",
	5: "timeType",
	6: "jobReqId",
	7: "externalUrl",
}

// Decode decodes JobPostingInfo from json.
func (s *JobPostingInfo) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode JobPostingInfo to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "title":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				if err := s.Title.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"title\"")
			}
		case "jobDescription":
			requiredBitSet[0] |= 1 << 1
			if err := func() error {
				if err := s.JobDescription.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"jobDescription\"")
			}
		case "location":
			if err := func() error {
				s.Location.Reset()
				if err := s.Location.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"location\"")
			}
		case "additionalLocations":
			if err := func() error {
				s.AdditionalLocations = make([]string, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem string
					v, err := d.Str()
					elem = string(v)
					if err != nil {
						return err
					}
					s.AdditionalLocations = append(s.AdditionalLocations, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"additionalLocations\"")
			}
		case "postedOn":
			if err := func() error {
				s.PostedOn.Reset()
				if err := s.PostedOn.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"postedOn\"")
			}
		case "timeType":
			if err := func() error {
				s.TimeType.Reset()
				if err := s.TimeType.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"timeType\"")
			}
		case "jobReqId":
			if err := func() error {
				s.JobReqId.Reset()
				if err := s.JobReqId.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"jobReqId\"")
			}
		case "externalUrl":
			if err := func() error {
				s.ExternalUrl.Reset()
				if err := s.ExternalUrl.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"externalUrl\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode JobPostingInfo")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00000011,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfJobPostingInfo) {
					name = jsonFieldsNameOfJobPostingInfo[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *JobPostingInfo) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *JobPostingInfo) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *JobSummary) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *JobSummary) encodeFields(e *jx.Encoder) {
	{
		if s.Title.Set {
			e.FieldStart("title")
			s.Title.Encode(e)
		}
	}
	{
		if s.ExternalPath.Set {
			e.FieldStart("externalPath")
			s.ExternalPath.Encode(e)
		}
	}
	{
		if s.LocationsText.Set {
			e.FieldStart("locationsText")
			s.LocationsText.Encode(e)
		}
	}
	{
		if s.PostedOn.Set {
			e.FieldStart("postedOn")
			s.PostedOn.Encode(e)
		}
	}
}

var jsonFieldsNameOfJobSummary = [4]string{
	0: "title",
	1: "externalPath",
	2: "locationsText",
	3: "postedOn",
}

// Decode decodes JobSummary from json.
func (s *JobSummary) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode JobSummary to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "title":
			if err := func() error {
				s.Title.Reset()
				if err := s.Title.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"title\"")
			}
		case "externalPath":
			if err := func() error {
				s.ExternalPath.Reset()
				if err := s.ExternalPath.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"externalPath\"")
			}
		case "locationsText":
			if err := func() error {
				s.LocationsText.Reset()
				if err := s.LocationsText.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"locationsText\"")
			}
		case "postedOn":
			if err := func() error {
				s.PostedOn.Reset()
				if err := s.PostedOn.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"postedOn\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode JobSummary")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *JobSummary) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *JobSummary) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *JobsRequest) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *JobsRequest) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("appliedFacets")
		s.AppliedFacets.Encode(e)
	}
	{
		e.FieldStart("limit")
		e.Int(s.Limit)
	}
	{
		e.FieldStart("offset")
		e.Int(s.Offset)
	}
	{
		e.FieldStart("searchText")
		e.Str(s.SearchText)
	}
}

var jsonFieldsNameOfJobsRequest = [4]string{
	0: "appliedFacets",
	1: "limit",
	2: "offset",
	3: "searchText",
}

// Decode decodes JobsRequest from json.
func (s *JobsRequest) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode JobsRequest to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "appliedFacets":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				if err := s.AppliedFacets.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"appliedFacets\"")
			}
		case "limit":
			requiredBitSet[0] |= 1 << 1
			if err := func() error {
				v, err := d.Int()
				s.Limit = int(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"limit\"")
			}
		case "offset":
			requiredBitSet[0] |= 1 << 2
			if err := func() error {
				v, err := d.Int()
				s.Offset = int(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"offset\"")
			}
		case "searchText":
			requiredBitSet[0] |= 1 << 3
			if err := func() error {
				v, err := d.Str()
				s.SearchText = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"searchText\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode JobsRequest")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00001111,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfJobsRequest) {
					name = jsonFieldsNameOfJobsRequest[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *JobsRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *JobsRequest) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *JobsResponse) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *JobsResponse) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("total")
		s.Total.Encode(e)
	}
	{
		e.FieldStart("jobPostings")
		e.ArrStart()
		for _, elem := range s.JobPostings {
			elem.Encode(e)
		}
		e.ArrEnd()
	}
}

var jsonFieldsNameOfJobsResponse = [2]string{
	0: "total",
	1: "jobPostings",
}

// Decode decodes JobsResponse from json.
func (s *JobsResponse) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode JobsResponse to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "total":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				if err := s.Total.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"total\"")
			}
		case "jobPostings":
			requiredBitSet[0] |= 1 << 1
			if err := func() error {
				s.JobPostings = make([]JobSummary, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem JobSummary
					if err := elem.Decode(d); err != nil {
						return err
					}
					s.JobPostings = append(s.JobPostings, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"jobPostings\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode JobsResponse")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00000011,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfJobsResponse) {
					name = jsonFieldsNameOfJobsResponse[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *JobsResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *JobsResponse) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes int as json.
func (o NilInt) Encode(e *jx.Encoder) {
	if o.Null {
		e.Null()
		return
	}
	e.Int(int(o.Value))
}

// Decode decodes int from json.
func (o *NilInt) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode NilInt to nil")
	}
	if d.Next() == jx.Null {
		if err := d.Null(); err != nil {
			return err
		}

		var v int
		o.Value = v
		o.Null = true
		return nil
	}
	o.Null = false
	v, err := d.Int()
	if err != nil {
		return err
	}
	o.Value = int(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s NilInt) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *NilInt) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes string as json.
func (o NilString) Encode(e *jx.Encoder) {
	if o.Null {
		e.Null()
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes string from json.
func (o *NilString) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode NilString to nil")
	}
	if d.Next() == jx.Null {
		if err := d.Null(); err != nil {
			return err
		}

		var v string
		o.Value = v
		o.Null = true
		return nil
	}
	o.Null = false
	v, err := d.Str()
	if err != nil {
		return err
	}
	o.Value = string(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s NilString) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *NilString) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes int as json.
func (o OptNilInt) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	if o.Null {
		e.Null()
		return
	}
	e.Int(int(o.Value))
}

// Decode decodes int from json.
func (o *OptNilInt) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptNilInt to nil")
	}
	if d.Next() == jx.Null {
		if err := d.Null(); err != nil {
			return err
		}

		var v int
		o.Value = v
		o.Set = true
		o.Null = true
		return nil
	}
	o.Set = true
	o.Null = false
	v, err := d.Int()
	if err != nil {
		return err
	}
	o.Value = int(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilInt) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilInt) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes string as json.
func (o OptNilString) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	if o.Null {
		e.Null()
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes string from json.
func (o *OptNilString) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptNilString to nil")
	}
	if d.Next() == jx.Null {
		if err := d.Null(); err != nil {
			return err
		}

		var v string
		o.Value = v
		o.Set = true
		o.Null = true
		return nil
	}
	o.Set = true
	o.Null = false
	v, err := d.Str()
	if err != nil {
		return err
	}
	o.Value = string(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilString) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilString) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes string as json.
func (o OptString) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes string from json.
func (o *OptString) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptString to nil")
	}
	o.Set = true
	v, err := d.Str()
	if err != nil {
		return err
	}
	o.Value = string(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptString) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptString) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}
