// Code generated by ogen, DO NOT EDIT.

package freehire

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AgentSearchJobs implements agentSearchJobs operation.
//
// Identical query surface to `searchJobs`, but every result carries the job's full description, read
// verbatim from the database rather than the search index's preview, in the format selected by
// `description_format`.
//
// Responses are several times larger per hit than `searchJobs`, so prefer a small `limit`.
//
// GET /agent/jobs/search
func (UnimplementedHandler) AgentSearchJobs(ctx context.Context, params AgentSearchJobsParams) (r *JobListEnvelope, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCompany implements getCompany operation.
//
// Get company details and open jobs.
//
// GET /companies/{slug}
func (UnimplementedHandler) GetCompany(ctx context.Context, params GetCompanyParams) (r *GetCompanyOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetJob implements getJob operation.
//
// Full detail for one posting: the verbatim stored description (HTML) and the `ghost` signal, which
// `agentSearchJobs` does not carry. This is the only endpoint that serves a closed posting;
// `closed_at` is non-null when the role is no longer open.
//
// GET /jobs/{slug}
func (UnimplementedHandler) GetJob(ctx context.Context, params GetJobParams) (r *GetJobOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetJobFacets implements getJobFacets operation.
//
// Return facet values, counts, canonical skill slugs, and numeric ranges for the postings matching the
// same filter grammar the search endpoints take. Call this before applying any uncertain filter.
//
// A distribution is counted per facet and the wide-valued ones (`cities`, `skills`) dominate, so
// narrow with `facets=` whenever you read only a few. `company_slug` has no distribution — use
// `searchCompanies` for the company typeahead.
//
// GET /jobs/facets
func (UnimplementedHandler) GetJobFacets(ctx context.Context, params GetJobFacetsParams) (r *FacetsEnvelope, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSimilarJobs implements getSimilarJobs operation.
//
// Nearest neighbours from a precomputed semantic list, nearest first. The list is built offline, so a
// neighbour that has since closed is dropped silently — a response may hold fewer items than
// `limit`.
//
// GET /jobs/{slug}/similar
func (UnimplementedHandler) GetSimilarJobs(ctx context.Context, params GetSimilarJobsParams) (r *GetSimilarJobsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchCities implements searchCities operation.
//
// Typeahead over the city dictionary. The returned `value` is exactly what the `cities` job facet
// expects — resolve here before filtering, since the facet holds canonical display names ("London")
// and matches nothing on a near miss.
//
// City names are not unique: "London" exists in both `gb` and `ca`. The `cities` facet has no country
// qualifier, so combine it with `countries` only if you accept the OR-group widening described at the
// top of this schema.
//
// GET /geo/cities
func (UnimplementedHandler) SearchCities(ctx context.Context, params SearchCitiesParams) (r *SearchCitiesOK, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchCompanies implements searchCompanies operation.
//
// Companies that currently have at least one open role, most active first. Facet parameters are
// repeatable (OR within a facet, AND across facets) and compose with `q`.
//
// `meta.total` is exact whenever any filter is present. On a completely unfiltered request it is a
// planner estimate, because counting the whole catalogue exactly is too expensive to do per request.
//
// GET /companies
func (UnimplementedHandler) SearchCompanies(ctx context.Context, params SearchCompaniesParams) (r *SearchCompaniesOK, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchJobs implements searchJobs operation.
//
// Full-text and faceted search over open postings. Descriptions are the search index's truncated
// preview. Use `agentSearchJobs` when you need the full verbatim body of every hit, or `getJob` for
// the one posting the user picked.
//
// Closed postings are never in the index, so they never appear here.
//
// GET /jobs/search
func (UnimplementedHandler) SearchJobs(ctx context.Context, params SearchJobsParams) (r *JobListEnvelope, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
