// Code generated by ogen, DO NOT EDIT.

package freehire

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AgentSearchJobs implements agentSearchJobs operation.
	//
	// Agent-friendly job search. Every result carries the job's full description (verbatim from the
	// database, not the search-index preview), in the format selected by description_format.
	//
	// GET /agent/jobs/search
	AgentSearchJobs(ctx context.Context, params AgentSearchJobsParams) (*JobListEnvelope, error)
	// GetCompany implements getCompany operation.
	//
	// Get company details and open jobs.
	//
	// GET /companies/{slug}
	GetCompany(ctx context.Context, params GetCompanyParams) (*GetCompanyOK, error)
	// GetJob implements getJob operation.
	//
	// Get a job by slug.
	//
	// GET /jobs/{slug}
	GetJob(ctx context.Context, params GetJobParams) (*GetJobOK, error)
	// GetJobFacets implements getJobFacets operation.
	//
	// Return facet values, counts, canonical skill slugs, and numeric ranges. Use this before applying
	// uncertain filters such as skills, countries, company_slug, source, or category.
	//
	// GET /jobs/facets
	GetJobFacets(ctx context.Context, params GetJobFacetsParams) (*FacetsEnvelope, error)
	// GetSimilarJobs implements getSimilarJobs operation.
	//
	// Find jobs similar to a job.
	//
	// GET /jobs/{slug}/similar
	GetSimilarJobs(ctx context.Context, params GetSimilarJobsParams) (*JobListEnvelope, error)
	// SearchCompanies implements searchCompanies operation.
	//
	// Search companies.
	//
	// GET /companies
	SearchCompanies(ctx context.Context, params SearchCompaniesParams) (*SearchCompaniesOK, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
