// Code generated by ogen, DO NOT EDIT.

package recruitee

// GetOffersNotFound is response for GetOffers operation.
type GetOffersNotFound struct{}

func (*GetOffersNotFound) getOffersRes() {}

// Ref: #/components/schemas/Location
type Location struct {
	ID          OptNilInt    `json:"id"`
	Name        OptNilString `json:"name"`
	City        OptNilString `json:"city"`
	Country     OptNilString `json:"country"`
	CountryCode OptNilString `json:"country_code"`
}

// GetID returns the value of ID.
func (s *Location) GetID() OptNilInt {
	return s.ID
}

// GetName returns the value of Name.
func (s *Location) GetName() OptNilString {
	return s.Name
}

// GetCity returns the value of City.
func (s *Location) GetCity() OptNilString {
	return s.City
}

// GetCountry returns the value of Country.
func (s *Location) GetCountry() OptNilString {
	return s.Country
}

// GetCountryCode returns the value of CountryCode.
func (s *Location) GetCountryCode() OptNilString {
	return s.CountryCode
}

// SetID sets the value of ID.
func (s *Location) SetID(val OptNilInt) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Location) SetName(val OptNilString) {
	s.Name = val
}

// SetCity sets the value of City.
func (s *Location) SetCity(val OptNilString) {
	s.City = val
}

// SetCountry sets the value of Country.
func (s *Location) SetCountry(val OptNilString) {
	s.Country = val
}

// SetCountryCode sets the value of CountryCode.
func (s *Location) SetCountryCode(val OptNilString) {
	s.CountryCode = val
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Offer
type Offer struct {
	// Job ID.
	ID int `json:"id"`
	// Job title.
	Title NilString `json:"title"`
	// URL slug.
	Slug NilString `json:"slug"`
	// Listing status.
	Status   OptNilString `json:"status"`
	Position OptNilInt    `json:"position"`
	// UTC creation time string.
	CreatedAt OptNilString `json:"created_at"`
	// UTC publish time string.
	PublishedAt OptNilString `json:"published_at"`
	// Full description HTML.
	Description OptNilString `json:"description"`
	// Requirements HTML.
	Requirements OptNilString `json:"requirements"`
	// Public career site job posting URL.
	CareersURL NilString `json:"careers_url"`
	// Direct application URL.
	CareersApplyURL NilString `json:"careers_apply_url"`
	// Free-form location text.
	Location OptNilString `json:"location"`
	// List of location details.
	Locations          []Location   `json:"locations"`
	City               OptNilString `json:"city"`
	Country            OptNilString `json:"country"`
	CountryCode        OptNilString `json:"country_code"`
	StateCode          OptNilString `json:"state_code"`
	Remote             OptNilBool   `json:"remote"`
	Hybrid             OptNilBool   `json:"hybrid"`
	OnSite             OptNilBool   `json:"on_site"`
	EmploymentTypeCode OptNilString `json:"employment_type_code"`
	ExperienceCode     OptNilString `json:"experience_code"`
	EducationCode      OptNilString `json:"education_code"`
	CategoryCode       OptNilString `json:"category_code"`
	Department         OptNilString `json:"department"`
	Tags               []string     `json:"tags"`
	Salary             OptNilSalary `json:"salary"`
}

// GetID returns the value of ID.
func (s *Offer) GetID() int {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *Offer) GetTitle() NilString {
	return s.Title
}

// GetSlug returns the value of Slug.
func (s *Offer) GetSlug() NilString {
	return s.Slug
}

// GetStatus returns the value of Status.
func (s *Offer) GetStatus() OptNilString {
	return s.Status
}

// GetPosition returns the value of Position.
func (s *Offer) GetPosition() OptNilInt {
	return s.Position
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Offer) GetCreatedAt() OptNilString {
	return s.CreatedAt
}

// GetPublishedAt returns the value of PublishedAt.
func (s *Offer) GetPublishedAt() OptNilString {
	return s.PublishedAt
}

// GetDescription returns the value of Description.
func (s *Offer) GetDescription() OptNilString {
	return s.Description
}

// GetRequirements returns the value of Requirements.
func (s *Offer) GetRequirements() OptNilString {
	return s.Requirements
}

// GetCareersURL returns the value of CareersURL.
func (s *Offer) GetCareersURL() NilString {
	return s.CareersURL
}

// GetCareersApplyURL returns the value of CareersApplyURL.
func (s *Offer) GetCareersApplyURL() NilString {
	return s.CareersApplyURL
}

// GetLocation returns the value of Location.
func (s *Offer) GetLocation() OptNilString {
	return s.Location
}

// GetLocations returns the value of Locations.
func (s *Offer) GetLocations() []Location {
	return s.Locations
}

// GetCity returns the value of City.
func (s *Offer) GetCity() OptNilString {
	return s.City
}

// GetCountry returns the value of Country.
func (s *Offer) GetCountry() OptNilString {
	return s.Country
}

// GetCountryCode returns the value of CountryCode.
func (s *Offer) GetCountryCode() OptNilString {
	return s.CountryCode
}

// GetStateCode returns the value of StateCode.
func (s *Offer) GetStateCode() OptNilString {
	return s.StateCode
}

// GetRemote returns the value of Remote.
func (s *Offer) GetRemote() OptNilBool {
	return s.Remote
}

// GetHybrid returns the value of Hybrid.
func (s *Offer) GetHybrid() OptNilBool {
	return s.Hybrid
}

// GetOnSite returns the value of OnSite.
func (s *Offer) GetOnSite() OptNilBool {
	return s.OnSite
}

// GetEmploymentTypeCode returns the value of EmploymentTypeCode.
func (s *Offer) GetEmploymentTypeCode() OptNilString {
	return s.EmploymentTypeCode
}

// GetExperienceCode returns the value of ExperienceCode.
func (s *Offer) GetExperienceCode() OptNilString {
	return s.ExperienceCode
}

// GetEducationCode returns the value of EducationCode.
func (s *Offer) GetEducationCode() OptNilString {
	return s.EducationCode
}

// GetCategoryCode returns the value of CategoryCode.
func (s *Offer) GetCategoryCode() OptNilString {
	return s.CategoryCode
}

// GetDepartment returns the value of Department.
func (s *Offer) GetDepartment() OptNilString {
	return s.Department
}

// GetTags returns the value of Tags.
func (s *Offer) GetTags() []string {
	return s.Tags
}

// GetSalary returns the value of Salary.
func (s *Offer) GetSalary() OptNilSalary {
	return s.Salary
}

// SetID sets the value of ID.
func (s *Offer) SetID(val int) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *Offer) SetTitle(val NilString) {
	s.Title = val
}

// SetSlug sets the value of Slug.
func (s *Offer) SetSlug(val NilString) {
	s.Slug = val
}

// SetStatus sets the value of Status.
func (s *Offer) SetStatus(val OptNilString) {
	s.Status = val
}

// SetPosition sets the value of Position.
func (s *Offer) SetPosition(val OptNilInt) {
	s.Position = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Offer) SetCreatedAt(val OptNilString) {
	s.CreatedAt = val
}

// SetPublishedAt sets the value of PublishedAt.
func (s *Offer) SetPublishedAt(val OptNilString) {
	s.PublishedAt = val
}

// SetDescription sets the value of Description.
func (s *Offer) SetDescription(val OptNilString) {
	s.Description = val
}

// SetRequirements sets the value of Requirements.
func (s *Offer) SetRequirements(val OptNilString) {
	s.Requirements = val
}

// SetCareersURL sets the value of CareersURL.
func (s *Offer) SetCareersURL(val NilString) {
	s.CareersURL = val
}

// SetCareersApplyURL sets the value of CareersApplyURL.
func (s *Offer) SetCareersApplyURL(val NilString) {
	s.CareersApplyURL = val
}

// SetLocation sets the value of Location.
func (s *Offer) SetLocation(val OptNilString) {
	s.Location = val
}

// SetLocations sets the value of Locations.
func (s *Offer) SetLocations(val []Location) {
	s.Locations = val
}

// SetCity sets the value of City.
func (s *Offer) SetCity(val OptNilString) {
	s.City = val
}

// SetCountry sets the value of Country.
func (s *Offer) SetCountry(val OptNilString) {
	s.Country = val
}

// SetCountryCode sets the value of CountryCode.
func (s *Offer) SetCountryCode(val OptNilString) {
	s.CountryCode = val
}

// SetStateCode sets the value of StateCode.
func (s *Offer) SetStateCode(val OptNilString) {
	s.StateCode = val
}

// SetRemote sets the value of Remote.
func (s *Offer) SetRemote(val OptNilBool) {
	s.Remote = val
}

// SetHybrid sets the value of Hybrid.
func (s *Offer) SetHybrid(val OptNilBool) {
	s.Hybrid = val
}

// SetOnSite sets the value of OnSite.
func (s *Offer) SetOnSite(val OptNilBool) {
	s.OnSite = val
}

// SetEmploymentTypeCode sets the value of EmploymentTypeCode.
func (s *Offer) SetEmploymentTypeCode(val OptNilString) {
	s.EmploymentTypeCode = val
}

// SetExperienceCode sets the value of ExperienceCode.
func (s *Offer) SetExperienceCode(val OptNilString) {
	s.ExperienceCode = val
}

// SetEducationCode sets the value of EducationCode.
func (s *Offer) SetEducationCode(val OptNilString) {
	s.EducationCode = val
}

// SetCategoryCode sets the value of CategoryCode.
func (s *Offer) SetCategoryCode(val OptNilString) {
	s.CategoryCode = val
}

// SetDepartment sets the value of Department.
func (s *Offer) SetDepartment(val OptNilString) {
	s.Department = val
}

// SetTags sets the value of Tags.
func (s *Offer) SetTags(val []string) {
	s.Tags = val
}

// SetSalary sets the value of Salary.
func (s *Offer) SetSalary(val OptNilSalary) {
	s.Salary = val
}

// Ref: #/components/schemas/OffersResponse
type OffersResponse struct {
	Offers []Offer `json:"offers"`
}

// GetOffers returns the value of Offers.
func (s *OffersResponse) GetOffers() []Offer {
	return s.Offers
}

// SetOffers sets the value of Offers.
func (s *OffersResponse) SetOffers(val []Offer) {
	s.Offers = val
}

func (*OffersResponse) getOffersRes() {}

// NewOptNilBool returns new OptNilBool with value set to v.
func NewOptNilBool(v bool) OptNilBool {
	return OptNilBool{
		Value: v,
		Set:   true,
	}
}

// OptNilBool is optional nullable bool.
type OptNilBool struct {
	Value bool
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilBool was set.
func (o OptNilBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilBool) SetTo(v bool) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilBool) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilBool) SetToNull() {
	o.Set = true
	o.Null = true
	var v bool
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilBool) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilBool) Get() (v bool, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilInt returns new OptNilInt with value set to v.
func NewOptNilInt(v int) OptNilInt {
	return OptNilInt{
		Value: v,
		Set:   true,
	}
}

// OptNilInt is optional nullable int.
type OptNilInt struct {
	Value int
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt was set.
func (o OptNilInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt) SetTo(v int) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilInt) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilInt) SetToNull() {
	o.Set = true
	o.Null = true
	var v int
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilInt) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt) Get() (v int, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilSalary returns new OptNilSalary with value set to v.
func NewOptNilSalary(v Salary) OptNilSalary {
	return OptNilSalary{
		Value: v,
		Set:   true,
	}
}

// OptNilSalary is optional nullable Salary.
type OptNilSalary struct {
	Value Salary
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilSalary was set.
func (o OptNilSalary) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilSalary) Reset() {
	var v Salary
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilSalary) SetTo(v Salary) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilSalary) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilSalary) SetToNull() {
	o.Set = true
	o.Null = true
	var v Salary
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilSalary) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilSalary) Get() (v Salary, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilSalary) Or(d Salary) Salary {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilString) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Salary
type Salary struct {
	Min      OptNilString `json:"min"`
	Max      OptNilString `json:"max"`
	Period   OptNilString `json:"period"`
	Currency OptNilString `json:"currency"`
}

// GetMin returns the value of Min.
func (s *Salary) GetMin() OptNilString {
	return s.Min
}

// GetMax returns the value of Max.
func (s *Salary) GetMax() OptNilString {
	return s.Max
}

// GetPeriod returns the value of Period.
func (s *Salary) GetPeriod() OptNilString {
	return s.Period
}

// GetCurrency returns the value of Currency.
func (s *Salary) GetCurrency() OptNilString {
	return s.Currency
}

// SetMin sets the value of Min.
func (s *Salary) SetMin(val OptNilString) {
	s.Min = val
}

// SetMax sets the value of Max.
func (s *Salary) SetMax(val OptNilString) {
	s.Max = val
}

// SetPeriod sets the value of Period.
func (s *Salary) SetPeriod(val OptNilString) {
	s.Period = val
}

// SetCurrency sets the value of Currency.
func (s *Salary) SetCurrency(val OptNilString) {
	s.Currency = val
}
