// Code generated by ogen, DO NOT EDIT.

package recruitee

import (
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"go.opentelemetry.io/otel/trace"
)

func encodeGetOffersResponse(response GetOffersRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *OffersResponse:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *GetOffersNotFound:
		w.WriteHeader(404)

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}
