// Code generated by ogen, DO NOT EDIT.

package eightfold

import (
	"github.com/go-faster/jx"
)

// Ref: #/components/schemas/AllFilter
type AllFilter struct {
	// Same role as SmartFilter.filterName.
	FilterName string `json:"filterName"`
	Title      string `json:"title"`
	// Null for non-list facets, mirroring SmartFilter.options.
	Options []AllFilterOption `json:"options"`
}

// GetFilterName returns the value of FilterName.
func (s *AllFilter) GetFilterName() string {
	return s.FilterName
}

// GetTitle returns the value of Title.
func (s *AllFilter) GetTitle() string {
	return s.Title
}

// GetOptions returns the value of Options.
func (s *AllFilter) GetOptions() []AllFilterOption {
	return s.Options
}

// SetFilterName sets the value of FilterName.
func (s *AllFilter) SetFilterName(val string) {
	s.FilterName = val
}

// SetTitle sets the value of Title.
func (s *AllFilter) SetTitle(val string) {
	s.Title = val
}

// SetOptions sets the value of Options.
func (s *AllFilter) SetOptions(val []AllFilterOption) {
	s.Options = val
}

// Same intent as SmartFilterOption, but label is deliberately left untyped rather than string:
// "latlong" facets (observed on Eaton's and Qualcomm's latlong_non_remote, live-verified 2026-07-14)
// send an integer nearby-postings count as label instead of a name, and a plain `type: string` here
// would fail to decode the entire search response over one unusable facet. The adapter decodes label
// permissively and drops any option whose label isn't a JSON string.
// Ref: #/components/schemas/AllFilterOption
type AllFilterOption struct {
	Label jx.Raw `json:"label"`
	// The value to send back as filter_=.
	Value string `json:"value"`
}

// GetLabel returns the value of Label.
func (s *AllFilterOption) GetLabel() jx.Raw {
	return s.Label
}

// GetValue returns the value of Value.
func (s *AllFilterOption) GetValue() string {
	return s.Value
}

// SetLabel sets the value of Label.
func (s *AllFilterOption) SetLabel(val jx.Raw) {
	s.Label = val
}

// SetValue sets the value of Value.
func (s *AllFilterOption) SetValue(val string) {
	s.Value = val
}

// Ref: #/components/schemas/FilterDef
type FilterDef struct {
	SmartFilters []SmartFilter `json:"smartFilters"`
	// A second facet list, usually disjoint from smartFilters, that some tenants populate instead of (or
	// alongside) it — e.g. Eaton, Infineon, and Qualcomm return empty smartFilters but a populated
	// allFilters. Not required: tenants that populate smartFilters have been observed omitting it.
	AllFilters []AllFilter `json:"allFilters"`
}

// GetSmartFilters returns the value of SmartFilters.
func (s *FilterDef) GetSmartFilters() []SmartFilter {
	return s.SmartFilters
}

// GetAllFilters returns the value of AllFilters.
func (s *FilterDef) GetAllFilters() []AllFilter {
	return s.AllFilters
}

// SetSmartFilters sets the value of SmartFilters.
func (s *FilterDef) SetSmartFilters(val []SmartFilter) {
	s.SmartFilters = val
}

// SetAllFilters sets the value of AllFilters.
func (s *FilterDef) SetAllFilters(val []AllFilter) {
	s.AllFilters = val
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilString) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// DisplayJobId (the employer's human-facing requisition number, e.g. "JR040530") is deliberately not
// modeled here even though every tenant sends it — some send it as a JSON number instead of a
// string, and nothing in the adapter reads it, so declaring it just adds a way to fail decoding a
// field nobody uses.
// Ref: #/components/schemas/Position
type Position struct {
	// Numeric position ID; the value position_details and the /careers/job/{id} URL take.
	ID        int64    `json:"id"`
	Name      string   `json:"name"`
	Locations []string `json:"locations"`
	// Unix seconds. Typed as number, not integer, because some tenants send unposted/unknown as the float
	// `0.0` rather than an int `0`.
	PostedTs float64 `json:"postedTs"`
	// Null observed on some tenants' postings that have no department assigned.
	Department OptNilString `json:"department"`
	// Observed values: "onsite", "hybrid", "remote".
	WorkLocationOption OptString `json:"workLocationOption"`
	// Site-relative posting path, e.g. "/careers/job/549798931483".
	PositionUrl string `json:"positionUrl"`
}

// GetID returns the value of ID.
func (s *Position) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *Position) GetName() string {
	return s.Name
}

// GetLocations returns the value of Locations.
func (s *Position) GetLocations() []string {
	return s.Locations
}

// GetPostedTs returns the value of PostedTs.
func (s *Position) GetPostedTs() float64 {
	return s.PostedTs
}

// GetDepartment returns the value of Department.
func (s *Position) GetDepartment() OptNilString {
	return s.Department
}

// GetWorkLocationOption returns the value of WorkLocationOption.
func (s *Position) GetWorkLocationOption() OptString {
	return s.WorkLocationOption
}

// GetPositionUrl returns the value of PositionUrl.
func (s *Position) GetPositionUrl() string {
	return s.PositionUrl
}

// SetID sets the value of ID.
func (s *Position) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Position) SetName(val string) {
	s.Name = val
}

// SetLocations sets the value of Locations.
func (s *Position) SetLocations(val []string) {
	s.Locations = val
}

// SetPostedTs sets the value of PostedTs.
func (s *Position) SetPostedTs(val float64) {
	s.PostedTs = val
}

// SetDepartment sets the value of Department.
func (s *Position) SetDepartment(val OptNilString) {
	s.Department = val
}

// SetWorkLocationOption sets the value of WorkLocationOption.
func (s *Position) SetWorkLocationOption(val OptString) {
	s.WorkLocationOption = val
}

// SetPositionUrl sets the value of PositionUrl.
func (s *Position) SetPositionUrl(val string) {
	s.PositionUrl = val
}

// Merged schema.
// Ref: #/components/schemas/PositionDetail
type PositionDetail struct {
	// Numeric position ID; the value position_details and the /careers/job/{id} URL take.
	ID        int64    `json:"id"`
	Name      string   `json:"name"`
	Locations []string `json:"locations"`
	// Unix seconds. Typed as number, not integer, because some tenants send unposted/unknown as the float
	// `0.0` rather than an int `0`.
	PostedTs float64 `json:"postedTs"`
	// Null observed on some tenants' postings that have no department assigned.
	Department OptNilString `json:"department"`
	// Observed values: "onsite", "hybrid", "remote".
	WorkLocationOption OptString `json:"workLocationOption"`
	// Site-relative posting path, e.g. "/careers/job/549798931483".
	PositionUrl string `json:"positionUrl"`
	// Full posting description as HTML.
	JobDescription string `json:"jobDescription"`
	// Absolute, human-clickable posting URL.
	PublicUrl string `json:"publicUrl"`
}

// GetID returns the value of ID.
func (s *PositionDetail) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *PositionDetail) GetName() string {
	return s.Name
}

// GetLocations returns the value of Locations.
func (s *PositionDetail) GetLocations() []string {
	return s.Locations
}

// GetPostedTs returns the value of PostedTs.
func (s *PositionDetail) GetPostedTs() float64 {
	return s.PostedTs
}

// GetDepartment returns the value of Department.
func (s *PositionDetail) GetDepartment() OptNilString {
	return s.Department
}

// GetWorkLocationOption returns the value of WorkLocationOption.
func (s *PositionDetail) GetWorkLocationOption() OptString {
	return s.WorkLocationOption
}

// GetPositionUrl returns the value of PositionUrl.
func (s *PositionDetail) GetPositionUrl() string {
	return s.PositionUrl
}

// GetJobDescription returns the value of JobDescription.
func (s *PositionDetail) GetJobDescription() string {
	return s.JobDescription
}

// GetPublicUrl returns the value of PublicUrl.
func (s *PositionDetail) GetPublicUrl() string {
	return s.PublicUrl
}

// SetID sets the value of ID.
func (s *PositionDetail) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *PositionDetail) SetName(val string) {
	s.Name = val
}

// SetLocations sets the value of Locations.
func (s *PositionDetail) SetLocations(val []string) {
	s.Locations = val
}

// SetPostedTs sets the value of PostedTs.
func (s *PositionDetail) SetPostedTs(val float64) {
	s.PostedTs = val
}

// SetDepartment sets the value of Department.
func (s *PositionDetail) SetDepartment(val OptNilString) {
	s.Department = val
}

// SetWorkLocationOption sets the value of WorkLocationOption.
func (s *PositionDetail) SetWorkLocationOption(val OptString) {
	s.WorkLocationOption = val
}

// SetPositionUrl sets the value of PositionUrl.
func (s *PositionDetail) SetPositionUrl(val string) {
	s.PositionUrl = val
}

// SetJobDescription sets the value of JobDescription.
func (s *PositionDetail) SetJobDescription(val string) {
	s.JobDescription = val
}

// SetPublicUrl sets the value of PublicUrl.
func (s *PositionDetail) SetPublicUrl(val string) {
	s.PublicUrl = val
}

// Ref: #/components/schemas/PositionDetailsResponse
type PositionDetailsResponse struct {
	Status int            `json:"status"`
	Data   PositionDetail `json:"data"`
}

// GetStatus returns the value of Status.
func (s *PositionDetailsResponse) GetStatus() int {
	return s.Status
}

// GetData returns the value of Data.
func (s *PositionDetailsResponse) GetData() PositionDetail {
	return s.Data
}

// SetStatus sets the value of Status.
func (s *PositionDetailsResponse) SetStatus(val int) {
	s.Status = val
}

// SetData sets the value of Data.
func (s *PositionDetailsResponse) SetData(val PositionDetail) {
	s.Data = val
}

func (*PositionDetailsResponse) positionDetailsRes() {}

// Ref: #/components/schemas/PositionErrorInfo
type PositionErrorInfo struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *PositionErrorInfo) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *PositionErrorInfo) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/PositionNotFoundResponse
type PositionNotFoundResponse struct {
	Status int               `json:"status"`
	Error  PositionErrorInfo `json:"error"`
}

// GetStatus returns the value of Status.
func (s *PositionNotFoundResponse) GetStatus() int {
	return s.Status
}

// GetError returns the value of Error.
func (s *PositionNotFoundResponse) GetError() PositionErrorInfo {
	return s.Error
}

// SetStatus sets the value of Status.
func (s *PositionNotFoundResponse) SetStatus(val int) {
	s.Status = val
}

// SetError sets the value of Error.
func (s *PositionNotFoundResponse) SetError(val PositionErrorInfo) {
	s.Error = val
}

func (*PositionNotFoundResponse) positionDetailsRes() {}

// Ref: #/components/schemas/SearchData
type SearchData struct {
	Positions []Position `json:"positions"`
	// Total matching positions across all pages, not just this page's length.
	Count     int       `json:"count"`
	FilterDef FilterDef `json:"filterDef"`
}

// GetPositions returns the value of Positions.
func (s *SearchData) GetPositions() []Position {
	return s.Positions
}

// GetCount returns the value of Count.
func (s *SearchData) GetCount() int {
	return s.Count
}

// GetFilterDef returns the value of FilterDef.
func (s *SearchData) GetFilterDef() FilterDef {
	return s.FilterDef
}

// SetPositions sets the value of Positions.
func (s *SearchData) SetPositions(val []Position) {
	s.Positions = val
}

// SetCount sets the value of Count.
func (s *SearchData) SetCount(val int) {
	s.Count = val
}

// SetFilterDef sets the value of FilterDef.
func (s *SearchData) SetFilterDef(val FilterDef) {
	s.FilterDef = val
}

// Ref: #/components/schemas/SearchResponse
type SearchResponse struct {
	Status int        `json:"status"`
	Data   SearchData `json:"data"`
}

// GetStatus returns the value of Status.
func (s *SearchResponse) GetStatus() int {
	return s.Status
}

// GetData returns the value of Data.
func (s *SearchResponse) GetData() SearchData {
	return s.Data
}

// SetStatus sets the value of Status.
func (s *SearchResponse) SetStatus(val int) {
	s.Status = val
}

// SetData sets the value of Data.
func (s *SearchResponse) SetData(val SearchData) {
	s.Data = val
}

// Ref: #/components/schemas/SmartFilter
type SmartFilter struct {
	// The facet key, used as the filter_ query parameter name. Tenant-specific — e.g. "businessarea",
	// "employmenttype", "city" on Morgan Stanley.
	FilterName string `json:"filterName"`
	// Display label for the facet, e.g. "Business Area".
	Title string `json:"title"`
	// Null for non-list facets (observed: a "toggle" filter like include_remote, which carries a boolean
	// rather than a value list). The adapter skips any SmartFilter with null options — FilterSet only
	// exposes pick-a-value facets.
	Options []SmartFilterOption `json:"options"`
}

// GetFilterName returns the value of FilterName.
func (s *SmartFilter) GetFilterName() string {
	return s.FilterName
}

// GetTitle returns the value of Title.
func (s *SmartFilter) GetTitle() string {
	return s.Title
}

// GetOptions returns the value of Options.
func (s *SmartFilter) GetOptions() []SmartFilterOption {
	return s.Options
}

// SetFilterName sets the value of FilterName.
func (s *SmartFilter) SetFilterName(val string) {
	s.FilterName = val
}

// SetTitle sets the value of Title.
func (s *SmartFilter) SetTitle(val string) {
	s.Title = val
}

// SetOptions sets the value of Options.
func (s *SmartFilter) SetOptions(val []SmartFilterOption) {
	s.Options = val
}

// Ref: #/components/schemas/SmartFilterOption
type SmartFilterOption struct {
	Label string `json:"label"`
	// The value to send back as filter_=.
	Value string `json:"value"`
}

// GetLabel returns the value of Label.
func (s *SmartFilterOption) GetLabel() string {
	return s.Label
}

// GetValue returns the value of Value.
func (s *SmartFilterOption) GetValue() string {
	return s.Value
}

// SetLabel sets the value of Label.
func (s *SmartFilterOption) SetLabel(val string) {
	s.Label = val
}

// SetValue sets the value of Value.
func (s *SmartFilterOption) SetValue(val string) {
	s.Value = val
}

// Ref: #/components/schemas/V2ErrorResponse
type V2ErrorResponse struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *V2ErrorResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *V2ErrorResponse) SetMessage(val string) {
	s.Message = val
}

func (*V2ErrorResponse) positionDetailsV2Res() {}

// Deliberately narrower than the raw v2 payload (which also carries posting_name, hot, department,
// business_unit, t_update, ats_job_id, display_job_id, type, id_locale, stars, medallionProgram,
// location_flexibility, work_location_option, isPrivate, ...) — only the fields the adapter actually
// reads are modeled, since v2's field typing is looser per-tenant than pcsx's (e.g. department has
// been observed both as a string and as null here too).
// Ref: #/components/schemas/V2Position
type V2Position struct {
	ID        int64    `json:"id"`
	Name      string   `json:"name"`
	Locations []string `json:"locations"`
	// Unix seconds; the closest v2 analog to pcsx's postedTs.
	TCreate int64 `json:"t_create"`
	// Absolute posting URL, unlike pcsx's site-relative positionUrl.
	CanonicalPositionUrl string `json:"canonicalPositionUrl"`
}

// GetID returns the value of ID.
func (s *V2Position) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *V2Position) GetName() string {
	return s.Name
}

// GetLocations returns the value of Locations.
func (s *V2Position) GetLocations() []string {
	return s.Locations
}

// GetTCreate returns the value of TCreate.
func (s *V2Position) GetTCreate() int64 {
	return s.TCreate
}

// GetCanonicalPositionUrl returns the value of CanonicalPositionUrl.
func (s *V2Position) GetCanonicalPositionUrl() string {
	return s.CanonicalPositionUrl
}

// SetID sets the value of ID.
func (s *V2Position) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *V2Position) SetName(val string) {
	s.Name = val
}

// SetLocations sets the value of Locations.
func (s *V2Position) SetLocations(val []string) {
	s.Locations = val
}

// SetTCreate sets the value of TCreate.
func (s *V2Position) SetTCreate(val int64) {
	s.TCreate = val
}

// SetCanonicalPositionUrl sets the value of CanonicalPositionUrl.
func (s *V2Position) SetCanonicalPositionUrl(val string) {
	s.CanonicalPositionUrl = val
}

// Merged schema.
// Ref: #/components/schemas/V2PositionDetail
type V2PositionDetail struct {
	ID        int64    `json:"id"`
	Name      string   `json:"name"`
	Locations []string `json:"locations"`
	// Unix seconds; the closest v2 analog to pcsx's postedTs.
	TCreate int64 `json:"t_create"`
	// Absolute posting URL, unlike pcsx's site-relative positionUrl.
	CanonicalPositionUrl string `json:"canonicalPositionUrl"`
	// Full posting description as HTML.
	JobDescription string `json:"job_description"`
}

// GetID returns the value of ID.
func (s *V2PositionDetail) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *V2PositionDetail) GetName() string {
	return s.Name
}

// GetLocations returns the value of Locations.
func (s *V2PositionDetail) GetLocations() []string {
	return s.Locations
}

// GetTCreate returns the value of TCreate.
func (s *V2PositionDetail) GetTCreate() int64 {
	return s.TCreate
}

// GetCanonicalPositionUrl returns the value of CanonicalPositionUrl.
func (s *V2PositionDetail) GetCanonicalPositionUrl() string {
	return s.CanonicalPositionUrl
}

// GetJobDescription returns the value of JobDescription.
func (s *V2PositionDetail) GetJobDescription() string {
	return s.JobDescription
}

// SetID sets the value of ID.
func (s *V2PositionDetail) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *V2PositionDetail) SetName(val string) {
	s.Name = val
}

// SetLocations sets the value of Locations.
func (s *V2PositionDetail) SetLocations(val []string) {
	s.Locations = val
}

// SetTCreate sets the value of TCreate.
func (s *V2PositionDetail) SetTCreate(val int64) {
	s.TCreate = val
}

// SetCanonicalPositionUrl sets the value of CanonicalPositionUrl.
func (s *V2PositionDetail) SetCanonicalPositionUrl(val string) {
	s.CanonicalPositionUrl = val
}

// SetJobDescription sets the value of JobDescription.
func (s *V2PositionDetail) SetJobDescription(val string) {
	s.JobDescription = val
}

func (*V2PositionDetail) positionDetailsV2Res() {}

// Ref: #/components/schemas/V2SearchResponse
type V2SearchResponse struct {
	Positions []V2Position `json:"positions"`
	// Total matching positions across all pages, not just this page's length.
	Count int `json:"count"`
}

// GetPositions returns the value of Positions.
func (s *V2SearchResponse) GetPositions() []V2Position {
	return s.Positions
}

// GetCount returns the value of Count.
func (s *V2SearchResponse) GetCount() int {
	return s.Count
}

// SetPositions sets the value of Positions.
func (s *V2SearchResponse) SetPositions(val []V2Position) {
	s.Positions = val
}

// SetCount sets the value of Count.
func (s *V2SearchResponse) SetCount(val int) {
	s.Count = val
}
