// Code generated by ogen, DO NOT EDIT.

package delta

import (
	"math/bits"
	"strconv"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/validate"
)

// Encode implements json.Marshaler.
func (s *AreaItem) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *AreaItem) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("Value")
		e.Str(s.Value)
	}
	{
		e.FieldStart("Text")
		e.Str(s.Text)
	}
	{
		if s.Count.Set {
			e.FieldStart("Count")
			s.Count.Encode(e)
		}
	}
}

var jsonFieldsNameOfAreaItem = [3]string{
	0: "Value",
	1: "Text",
	2: "Count",
}

// Decode decodes AreaItem from json.
func (s *AreaItem) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode AreaItem to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "Value":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				v, err := d.Str()
				s.Value = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"Value\"")
			}
		case "Text":
			requiredBitSet[0] |= 1 << 1
			if err := func() error {
				v, err := d.Str()
				s.Text = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"Text\"")
			}
		case "Count":
			if err := func() error {
				s.Count.Reset()
				if err := s.Count.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"Count\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode AreaItem")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00000011,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfAreaItem) {
					name = jsonFieldsNameOfAreaItem[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *AreaItem) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *AreaItem) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes AreaList as json.
func (s AreaList) Encode(e *jx.Encoder) {
	unwrapped := []AreaItem(s)

	e.ArrStart()
	for _, elem := range unwrapped {
		elem.Encode(e)
	}
	e.ArrEnd()
}

// Decode decodes AreaList from json.
func (s *AreaList) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode AreaList to nil")
	}
	var unwrapped []AreaItem
	if err := func() error {
		unwrapped = make([]AreaItem, 0)
		if err := d.Arr(func(d *jx.Decoder) error {
			var elem AreaItem
			if err := elem.Decode(d); err != nil {
				return err
			}
			unwrapped = append(unwrapped, elem)
			return nil
		}); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return errors.Wrap(err, "alias")
	}
	*s = AreaList(unwrapped)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s AreaList) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *AreaList) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *JobDetail) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *JobDetail) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("EmpAddID")
		e.Str(s.EmpAddID)
	}
	{
		e.FieldStart("JobCode")
		e.Str(s.JobCode)
	}
	{
		e.FieldStart("JobName")
		e.Str(s.JobName)
	}
	{
		if s.Education.Set {
			e.FieldStart("Education")
			s.Education.Encode(e)
		}
	}
	{
		if s.JobExperience.Set {
			e.FieldStart("JobExperience")
			s.JobExperience.Encode(e)
		}
	}
	{
		if s.JobPlace.Set {
			e.FieldStart("JobPlace")
			s.JobPlace.Encode(e)
		}
	}
	{
		if s.NeedNum.Set {
			e.FieldStart("NeedNum")
			s.NeedNum.Encode(e)
		}
	}
	{
		if s.BeginDate.Set {
			e.FieldStart("BeginDate")
			s.BeginDate.Encode(e)
		}
	}
	{
		if s.JobResponsibility.Set {
			e.FieldStart("JobResponsibility")
			s.JobResponsibility.Encode(e)
		}
	}
	{
		if s.JobSkill.Set {
			e.FieldStart("JobSkill")
			s.JobSkill.Encode(e)
		}
	}
	{
		if s.LanguageAbility.Set {
			e.FieldStart("LanguageAbility")
			s.LanguageAbility.Encode(e)
		}
	}
	{
		if s.MainJob.Set {
			e.FieldStart("MainJob")
			s.MainJob.Encode(e)
		}
	}
	{
		if s.AreaName.Set {
			e.FieldStart("AreaName")
			s.AreaName.Encode(e)
		}
	}
	{
		if s.ApplyID.Set {
			e.FieldStart("ApplyID")
			s.ApplyID.Encode(e)
		}
	}
}

var jsonFieldsNameOfJobDetail = [14]string{
	0:  "EmpAddID",
	1:  "JobCode",
	2:  "JobName",
	3:  "Education",
	4:  "JobExperience",
	5:  "JobPlace",
	6:  "NeedNum",
	7:  "BeginDate",
	8:  "JobResponsibility",
	9:  "JobSkill",
	10: "LanguageAbility",
	11: "MainJob",
	12: "AreaName",
	13: "ApplyID",
}

// Decode decodes JobDetail from json.
func (s *JobDetail) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode JobDetail to nil")
	}
	var requiredBitSet [2]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "EmpAddID":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				v, err := d.Str()
				s.EmpAddID = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"EmpAddID\"")
			}
		case "JobCode":
			requiredBitSet[0] |= 1 << 1
			if err := func() error {
				v, err := d.Str()
				s.JobCode = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"JobCode\"")
			}
		case "JobName":
			requiredBitSet[0] |= 1 << 2
			if err := func() error {
				v, err := d.Str()
				s.JobName = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"JobName\"")
			}
		case "Education":
			if err := func() error {
				s.Education.Reset()
				if err := s.Education.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"Education\"")
			}
		case "JobExperience":
			if err := func() error {
				s.JobExperience.Reset()
				if err := s.JobExperience.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"JobExperience\"")
			}
		case "JobPlace":
			if err := func() error {
				s.JobPlace.Reset()
				if err := s.JobPlace.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"JobPlace\"")
			}
		case "NeedNum":
			if err := func() error {
				s.NeedNum.Reset()
				if err := s.NeedNum.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"NeedNum\"")
			}
		case "BeginDate":
			if err := func() error {
				s.BeginDate.Reset()
				if err := s.BeginDate.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"BeginDate\"")
			}
		case "JobResponsibility":
			if err := func() error {
				s.JobResponsibility.Reset()
				if err := s.JobResponsibility.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"JobResponsibility\"")
			}
		case "JobSkill":
			if err := func() error {
				s.JobSkill.Reset()
				if err := s.JobSkill.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"JobSkill\"")
			}
		case "LanguageAbility":
			if err := func() error {
				s.LanguageAbility.Reset()
				if err := s.LanguageAbility.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"LanguageAbility\"")
			}
		case "MainJob":
			if err := func() error {
				s.MainJob.Reset()
				if err := s.MainJob.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"MainJob\"")
			}
		case "AreaName":
			if err := func() error {
				s.AreaName.Reset()
				if err := s.AreaName.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"AreaName\"")
			}
		case "ApplyID":
			if err := func() error {
				s.ApplyID.Reset()
				if err := s.ApplyID.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"ApplyID\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode JobDetail")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [2]uint8{
		0b00000111,
		0b00000000,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfJobDetail) {
					name = jsonFieldsNameOfJobDetail[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *JobDetail) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *JobDetail) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *JobDetailResponse) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *JobDetailResponse) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("JobDetails")
		e.ArrStart()
		for _, elem := range s.JobDetails {
			elem.Encode(e)
		}
		e.ArrEnd()
	}
	{
		if s.RelatedJob != nil {
			e.FieldStart("RelatedJob")
			e.ArrStart()
			for _, elem := range s.RelatedJob {
				elem.Encode(e)
			}
			e.ArrEnd()
		}
	}
}

var jsonFieldsNameOfJobDetailResponse = [2]string{
	0: "JobDetails",
	1: "RelatedJob",
}

// Decode decodes JobDetailResponse from json.
func (s *JobDetailResponse) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode JobDetailResponse to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "JobDetails":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				s.JobDetails = make([]JobDetail, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem JobDetail
					if err := elem.Decode(d); err != nil {
						return err
					}
					s.JobDetails = append(s.JobDetails, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"JobDetails\"")
			}
		case "RelatedJob":
			if err := func() error {
				s.RelatedJob = make([]JobDetail, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem JobDetail
					if err := elem.Decode(d); err != nil {
						return err
					}
					s.RelatedJob = append(s.RelatedJob, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"RelatedJob\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode JobDetailResponse")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00000001,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfJobDetailResponse) {
					name = jsonFieldsNameOfJobDetailResponse[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *JobDetailResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *JobDetailResponse) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes JobList as json.
func (s JobList) Encode(e *jx.Encoder) {
	unwrapped := []JobSummary(s)

	e.ArrStart()
	for _, elem := range unwrapped {
		elem.Encode(e)
	}
	e.ArrEnd()
}

// Decode decodes JobList from json.
func (s *JobList) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode JobList to nil")
	}
	var unwrapped []JobSummary
	if err := func() error {
		unwrapped = make([]JobSummary, 0)
		if err := d.Arr(func(d *jx.Decoder) error {
			var elem JobSummary
			if err := elem.Decode(d); err != nil {
				return err
			}
			unwrapped = append(unwrapped, elem)
			return nil
		}); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return errors.Wrap(err, "alias")
	}
	*s = JobList(unwrapped)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s JobList) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *JobList) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *JobSummary) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *JobSummary) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("EmpAddID")
		e.Str(s.EmpAddID)
	}
	{
		e.FieldStart("JobCode")
		e.Str(s.JobCode)
	}
	{
		e.FieldStart("JobName")
		e.Str(s.JobName)
	}
	{
		if s.Education.Set {
			e.FieldStart("Education")
			s.Education.Encode(e)
		}
	}
	{
		if s.Experience.Set {
			e.FieldStart("Experience")
			s.Experience.Encode(e)
		}
	}
	{
		if s.AreaName.Set {
			e.FieldStart("AreaName")
			s.AreaName.Encode(e)
		}
	}
	{
		if s.NeedNum.Set {
			e.FieldStart("NeedNum")
			s.NeedNum.Encode(e)
		}
	}
	{
		if s.ModifyDate.Set {
			e.FieldStart("ModifyDate")
			s.ModifyDate.Encode(e)
		}
	}
	{
		if s.AddJobPublisGuid.Set {
			e.FieldStart("AddJobPublisGuid")
			s.AddJobPublisGuid.Encode(e)
		}
	}
	{
		if s.ApplyID.Set {
			e.FieldStart("ApplyID")
			s.ApplyID.Encode(e)
		}
	}
	{
		if s.JobPlaceName.Set {
			e.FieldStart("JobPlaceName")
			s.JobPlaceName.Encode(e)
		}
	}
}

var jsonFieldsNameOfJobSummary = [11]string{
	0:  "EmpAddID",
	1:  "JobCode",
	2:  "JobName",
	3:  "Education",
	4:  "Experience",
	5:  "AreaName",
	6:  "NeedNum",
	7:  "ModifyDate",
	8:  "AddJobPublisGuid",
	9:  "ApplyID",
	10: "JobPlaceName",
}

// Decode decodes JobSummary from json.
func (s *JobSummary) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode JobSummary to nil")
	}
	var requiredBitSet [2]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "EmpAddID":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				v, err := d.Str()
				s.EmpAddID = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"EmpAddID\"")
			}
		case "JobCode":
			requiredBitSet[0] |= 1 << 1
			if err := func() error {
				v, err := d.Str()
				s.JobCode = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"JobCode\"")
			}
		case "JobName":
			requiredBitSet[0] |= 1 << 2
			if err := func() error {
				v, err := d.Str()
				s.JobName = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"JobName\"")
			}
		case "Education":
			if err := func() error {
				s.Education.Reset()
				if err := s.Education.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"Education\"")
			}
		case "Experience":
			if err := func() error {
				s.Experience.Reset()
				if err := s.Experience.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"Experience\"")
			}
		case "AreaName":
			if err := func() error {
				s.AreaName.Reset()
				if err := s.AreaName.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"AreaName\"")
			}
		case "NeedNum":
			if err := func() error {
				s.NeedNum.Reset()
				if err := s.NeedNum.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"NeedNum\"")
			}
		case "ModifyDate":
			if err := func() error {
				s.ModifyDate.Reset()
				if err := s.ModifyDate.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"ModifyDate\"")
			}
		case "AddJobPublisGuid":
			if err := func() error {
				s.AddJobPublisGuid.Reset()
				if err := s.AddJobPublisGuid.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"AddJobPublisGuid\"")
			}
		case "ApplyID":
			if err := func() error {
				s.ApplyID.Reset()
				if err := s.ApplyID.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"ApplyID\"")
			}
		case "JobPlaceName":
			if err := func() error {
				s.JobPlaceName.Reset()
				if err := s.JobPlaceName.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"JobPlaceName\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode JobSummary")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [2]uint8{
		0b00000111,
		0b00000000,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfJobSummary) {
					name = jsonFieldsNameOfJobSummary[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *JobSummary) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *JobSummary) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes int as json.
func (o OptNilInt) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	if o.Null {
		e.Null()
		return
	}
	e.Int(int(o.Value))
}

// Decode decodes int from json.
func (o *OptNilInt) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptNilInt to nil")
	}
	if d.Next() == jx.Null {
		if err := d.Null(); err != nil {
			return err
		}

		var v int
		o.Value = v
		o.Set = true
		o.Null = true
		return nil
	}
	o.Set = true
	o.Null = false
	v, err := d.Int()
	if err != nil {
		return err
	}
	o.Value = int(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilInt) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilInt) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes string as json.
func (o OptNilString) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	if o.Null {
		e.Null()
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes string from json.
func (o *OptNilString) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptNilString to nil")
	}
	if d.Next() == jx.Null {
		if err := d.Null(); err != nil {
			return err
		}

		var v string
		o.Value = v
		o.Set = true
		o.Null = true
		return nil
	}
	o.Set = true
	o.Null = false
	v, err := d.Str()
	if err != nil {
		return err
	}
	o.Value = string(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilString) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilString) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}
