// Code generated by ogen, DO NOT EDIT.

package mokahr

// Ref: #/components/schemas/FilterAggregations
type FilterAggregations struct {
	SystemFieldsAggregations OptSystemFieldsAggregations `json:"systemFieldsAggregations"`
}

// GetSystemFieldsAggregations returns the value of SystemFieldsAggregations.
func (s *FilterAggregations) GetSystemFieldsAggregations() OptSystemFieldsAggregations {
	return s.SystemFieldsAggregations
}

// SetSystemFieldsAggregations sets the value of SystemFieldsAggregations.
func (s *FilterAggregations) SetSystemFieldsAggregations(val OptSystemFieldsAggregations) {
	s.SystemFieldsAggregations = val
}

// Merged schema.
// Ref: #/components/schemas/FilterAggregationsResponse
type FilterAggregationsResponse struct {
	// 0 on success; see the document description for known failures.
	Code     int    `json:"code"`
	CodeType OptInt `json:"codeType"`
	// Human-readable status, in Chinese ("成功" on success).
	Msg     OptString             `json:"msg"`
	Success bool                  `json:"success"`
	Data    OptFilterAggregations `json:"data"`
}

// GetCode returns the value of Code.
func (s *FilterAggregationsResponse) GetCode() int {
	return s.Code
}

// GetCodeType returns the value of CodeType.
func (s *FilterAggregationsResponse) GetCodeType() OptInt {
	return s.CodeType
}

// GetMsg returns the value of Msg.
func (s *FilterAggregationsResponse) GetMsg() OptString {
	return s.Msg
}

// GetSuccess returns the value of Success.
func (s *FilterAggregationsResponse) GetSuccess() bool {
	return s.Success
}

// GetData returns the value of Data.
func (s *FilterAggregationsResponse) GetData() OptFilterAggregations {
	return s.Data
}

// SetCode sets the value of Code.
func (s *FilterAggregationsResponse) SetCode(val int) {
	s.Code = val
}

// SetCodeType sets the value of CodeType.
func (s *FilterAggregationsResponse) SetCodeType(val OptInt) {
	s.CodeType = val
}

// SetMsg sets the value of Msg.
func (s *FilterAggregationsResponse) SetMsg(val OptString) {
	s.Msg = val
}

// SetSuccess sets the value of Success.
func (s *FilterAggregationsResponse) SetSuccess(val bool) {
	s.Success = val
}

// SetData sets the value of Data.
func (s *FilterAggregationsResponse) SetData(val OptFilterAggregations) {
	s.Data = val
}

// Merged schema.
// Ref: #/components/schemas/GetJobRequest
type GetJobRequest struct {
	// Tenant slug, the first path segment of the careers URL (e.g. "high-flyer").
	OrgId string `json:"orgId"`
	// Careers-site id, the second path segment. A tenant can own several sites with different job sets,
	// and the site a bare /social-recruitment/ redirects to is not necessarily the largest one, so it is
	// never inferred.
	SiteId string `json:"siteId"`
	// Language for place names only. This client always sends "en-US"; see the document description.
	Locale OptString `json:"locale"`
	// A `Job.id` from `listJobs`.
	JobId string `json:"jobId"`
}

// GetOrgId returns the value of OrgId.
func (s *GetJobRequest) GetOrgId() string {
	return s.OrgId
}

// GetSiteId returns the value of SiteId.
func (s *GetJobRequest) GetSiteId() string {
	return s.SiteId
}

// GetLocale returns the value of Locale.
func (s *GetJobRequest) GetLocale() OptString {
	return s.Locale
}

// GetJobId returns the value of JobId.
func (s *GetJobRequest) GetJobId() string {
	return s.JobId
}

// SetOrgId sets the value of OrgId.
func (s *GetJobRequest) SetOrgId(val string) {
	s.OrgId = val
}

// SetSiteId sets the value of SiteId.
func (s *GetJobRequest) SetSiteId(val string) {
	s.SiteId = val
}

// SetLocale sets the value of Locale.
func (s *GetJobRequest) SetLocale(val OptString) {
	s.Locale = val
}

// SetJobId sets the value of JobId.
func (s *GetJobRequest) SetJobId(val string) {
	s.JobId = val
}

// Merged schema.
// Ref: #/components/schemas/GetJobResponse
type GetJobResponse struct {
	// 0 on success; see the document description for known failures.
	Code     int    `json:"code"`
	CodeType OptInt `json:"codeType"`
	// Human-readable status, in Chinese ("成功" on success).
	Msg     OptString    `json:"msg"`
	Success bool         `json:"success"`
	Data    OptJobDetail `json:"data"`
}

// GetCode returns the value of Code.
func (s *GetJobResponse) GetCode() int {
	return s.Code
}

// GetCodeType returns the value of CodeType.
func (s *GetJobResponse) GetCodeType() OptInt {
	return s.CodeType
}

// GetMsg returns the value of Msg.
func (s *GetJobResponse) GetMsg() OptString {
	return s.Msg
}

// GetSuccess returns the value of Success.
func (s *GetJobResponse) GetSuccess() bool {
	return s.Success
}

// GetData returns the value of Data.
func (s *GetJobResponse) GetData() OptJobDetail {
	return s.Data
}

// SetCode sets the value of Code.
func (s *GetJobResponse) SetCode(val int) {
	s.Code = val
}

// SetCodeType sets the value of CodeType.
func (s *GetJobResponse) SetCodeType(val OptInt) {
	s.CodeType = val
}

// SetMsg sets the value of Msg.
func (s *GetJobResponse) SetMsg(val OptString) {
	s.Msg = val
}

// SetSuccess sets the value of Success.
func (s *GetJobResponse) SetSuccess(val bool) {
	s.Success = val
}

// SetData sets the value of Data.
func (s *GetJobResponse) SetData(val OptJobDetail) {
	s.Data = val
}

// One posting as the list endpoint returns it.
// Ref: #/components/schemas/Job
type Job struct {
	// UUID; the `jobId` accepted by `getJob`.
	ID    string `json:"id"`
	Title string `json:"title"`
	// Observed only as "open" on public sites.
	Status OptString `json:"status"`
	// Full description as HTML.
	JobDescription OptString `json:"jobDescription"`
	// Null on tenants that keep workplaces off the list endpoint; see the document description. `getJob`
	// still reports them.
	Locations []Location  `json:"locations"`
	Zhineng   OptNamedRef `json:"zhineng"`
	OrgId     OptString   `json:"orgId"`
	// Department id. The list endpoint carries the id only; the department's name comes from `getJob`.
	DeptId     OptInt `json:"deptId"`
	HireMode   OptInt `json:"hireMode"`
	SalaryUnit OptInt `json:"salaryUnit"`
	// Whether the site presents this posting as campus recruitment.
	ShowIsCampus OptBool `json:"showIsCampus"`
	// A JSON string, not an object, e.g. '{"mainLocale":"zh-CN","secondLocale":""}'.
	MultiLocale OptString `json:"multiLocale"`
	// Local wall clock, no zone ("2026-06-25T14:23:06").
	CreatedAt OptString `json:"createdAt"`
	// Local wall clock, no zone.
	UpdatedAt OptString `json:"updatedAt"`
	// Local wall clock, minute precision and no zone ("2026-06-25T00:00").
	OpenedAt OptString `json:"openedAt"`
}

// GetID returns the value of ID.
func (s *Job) GetID() string {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *Job) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *Job) GetStatus() OptString {
	return s.Status
}

// GetJobDescription returns the value of JobDescription.
func (s *Job) GetJobDescription() OptString {
	return s.JobDescription
}

// GetLocations returns the value of Locations.
func (s *Job) GetLocations() []Location {
	return s.Locations
}

// GetZhineng returns the value of Zhineng.
func (s *Job) GetZhineng() OptNamedRef {
	return s.Zhineng
}

// GetOrgId returns the value of OrgId.
func (s *Job) GetOrgId() OptString {
	return s.OrgId
}

// GetDeptId returns the value of DeptId.
func (s *Job) GetDeptId() OptInt {
	return s.DeptId
}

// GetHireMode returns the value of HireMode.
func (s *Job) GetHireMode() OptInt {
	return s.HireMode
}

// GetSalaryUnit returns the value of SalaryUnit.
func (s *Job) GetSalaryUnit() OptInt {
	return s.SalaryUnit
}

// GetShowIsCampus returns the value of ShowIsCampus.
func (s *Job) GetShowIsCampus() OptBool {
	return s.ShowIsCampus
}

// GetMultiLocale returns the value of MultiLocale.
func (s *Job) GetMultiLocale() OptString {
	return s.MultiLocale
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Job) GetCreatedAt() OptString {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Job) GetUpdatedAt() OptString {
	return s.UpdatedAt
}

// GetOpenedAt returns the value of OpenedAt.
func (s *Job) GetOpenedAt() OptString {
	return s.OpenedAt
}

// SetID sets the value of ID.
func (s *Job) SetID(val string) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *Job) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *Job) SetStatus(val OptString) {
	s.Status = val
}

// SetJobDescription sets the value of JobDescription.
func (s *Job) SetJobDescription(val OptString) {
	s.JobDescription = val
}

// SetLocations sets the value of Locations.
func (s *Job) SetLocations(val []Location) {
	s.Locations = val
}

// SetZhineng sets the value of Zhineng.
func (s *Job) SetZhineng(val OptNamedRef) {
	s.Zhineng = val
}

// SetOrgId sets the value of OrgId.
func (s *Job) SetOrgId(val OptString) {
	s.OrgId = val
}

// SetDeptId sets the value of DeptId.
func (s *Job) SetDeptId(val OptInt) {
	s.DeptId = val
}

// SetHireMode sets the value of HireMode.
func (s *Job) SetHireMode(val OptInt) {
	s.HireMode = val
}

// SetSalaryUnit sets the value of SalaryUnit.
func (s *Job) SetSalaryUnit(val OptInt) {
	s.SalaryUnit = val
}

// SetShowIsCampus sets the value of ShowIsCampus.
func (s *Job) SetShowIsCampus(val OptBool) {
	s.ShowIsCampus = val
}

// SetMultiLocale sets the value of MultiLocale.
func (s *Job) SetMultiLocale(val OptString) {
	s.MultiLocale = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Job) SetCreatedAt(val OptString) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Job) SetUpdatedAt(val OptString) {
	s.UpdatedAt = val
}

// SetOpenedAt sets the value of OpenedAt.
func (s *Job) SetOpenedAt(val OptString) {
	s.OpenedAt = val
}

// A posting as the detail endpoint returns it: every `Job` field plus the ones the list omits.
// Ref: #/components/schemas/JobDetail
type JobDetail struct {
	ID             string      `json:"id"`
	Title          string      `json:"title"`
	Status         OptString   `json:"status"`
	JobDescription OptString   `json:"jobDescription"`
	Locations      []Location  `json:"locations"`
	Zhineng        OptNamedRef `json:"zhineng"`
	OrgId          OptString   `json:"orgId"`
	// Employment type, in the tenant's own language ("全职", "实习"). Not localized by `locale`.
	Commitment OptString   `json:"commitment"`
	Department OptNamedRef `json:"department"`
	// Every department the posting belongs to; `department` is the primary one.
	Departments  []NamedRef `json:"departments"`
	DepartmentId OptInt     `json:"departmentId"`
	HireMode     OptInt     `json:"hireMode"`
	SalaryUnit   OptInt     `json:"salaryUnit"`
	ShowIsCampus OptBool    `json:"showIsCampus"`
	MultiLocale  OptString  `json:"multiLocale"`
	BrandMessage OptString  `json:"brandMessage"`
	CreatedAt    OptString  `json:"createdAt"`
	UpdatedAt    OptString  `json:"updatedAt"`
	OpenedAt     OptString  `json:"openedAt"`
	// When the posting went live on the careers site. Absent from the list endpoint.
	PublishedAt OptString `json:"publishedAt"`
}

// GetID returns the value of ID.
func (s *JobDetail) GetID() string {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *JobDetail) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *JobDetail) GetStatus() OptString {
	return s.Status
}

// GetJobDescription returns the value of JobDescription.
func (s *JobDetail) GetJobDescription() OptString {
	return s.JobDescription
}

// GetLocations returns the value of Locations.
func (s *JobDetail) GetLocations() []Location {
	return s.Locations
}

// GetZhineng returns the value of Zhineng.
func (s *JobDetail) GetZhineng() OptNamedRef {
	return s.Zhineng
}

// GetOrgId returns the value of OrgId.
func (s *JobDetail) GetOrgId() OptString {
	return s.OrgId
}

// GetCommitment returns the value of Commitment.
func (s *JobDetail) GetCommitment() OptString {
	return s.Commitment
}

// GetDepartment returns the value of Department.
func (s *JobDetail) GetDepartment() OptNamedRef {
	return s.Department
}

// GetDepartments returns the value of Departments.
func (s *JobDetail) GetDepartments() []NamedRef {
	return s.Departments
}

// GetDepartmentId returns the value of DepartmentId.
func (s *JobDetail) GetDepartmentId() OptInt {
	return s.DepartmentId
}

// GetHireMode returns the value of HireMode.
func (s *JobDetail) GetHireMode() OptInt {
	return s.HireMode
}

// GetSalaryUnit returns the value of SalaryUnit.
func (s *JobDetail) GetSalaryUnit() OptInt {
	return s.SalaryUnit
}

// GetShowIsCampus returns the value of ShowIsCampus.
func (s *JobDetail) GetShowIsCampus() OptBool {
	return s.ShowIsCampus
}

// GetMultiLocale returns the value of MultiLocale.
func (s *JobDetail) GetMultiLocale() OptString {
	return s.MultiLocale
}

// GetBrandMessage returns the value of BrandMessage.
func (s *JobDetail) GetBrandMessage() OptString {
	return s.BrandMessage
}

// GetCreatedAt returns the value of CreatedAt.
func (s *JobDetail) GetCreatedAt() OptString {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *JobDetail) GetUpdatedAt() OptString {
	return s.UpdatedAt
}

// GetOpenedAt returns the value of OpenedAt.
func (s *JobDetail) GetOpenedAt() OptString {
	return s.OpenedAt
}

// GetPublishedAt returns the value of PublishedAt.
func (s *JobDetail) GetPublishedAt() OptString {
	return s.PublishedAt
}

// SetID sets the value of ID.
func (s *JobDetail) SetID(val string) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *JobDetail) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *JobDetail) SetStatus(val OptString) {
	s.Status = val
}

// SetJobDescription sets the value of JobDescription.
func (s *JobDetail) SetJobDescription(val OptString) {
	s.JobDescription = val
}

// SetLocations sets the value of Locations.
func (s *JobDetail) SetLocations(val []Location) {
	s.Locations = val
}

// SetZhineng sets the value of Zhineng.
func (s *JobDetail) SetZhineng(val OptNamedRef) {
	s.Zhineng = val
}

// SetOrgId sets the value of OrgId.
func (s *JobDetail) SetOrgId(val OptString) {
	s.OrgId = val
}

// SetCommitment sets the value of Commitment.
func (s *JobDetail) SetCommitment(val OptString) {
	s.Commitment = val
}

// SetDepartment sets the value of Department.
func (s *JobDetail) SetDepartment(val OptNamedRef) {
	s.Department = val
}

// SetDepartments sets the value of Departments.
func (s *JobDetail) SetDepartments(val []NamedRef) {
	s.Departments = val
}

// SetDepartmentId sets the value of DepartmentId.
func (s *JobDetail) SetDepartmentId(val OptInt) {
	s.DepartmentId = val
}

// SetHireMode sets the value of HireMode.
func (s *JobDetail) SetHireMode(val OptInt) {
	s.HireMode = val
}

// SetSalaryUnit sets the value of SalaryUnit.
func (s *JobDetail) SetSalaryUnit(val OptInt) {
	s.SalaryUnit = val
}

// SetShowIsCampus sets the value of ShowIsCampus.
func (s *JobDetail) SetShowIsCampus(val OptBool) {
	s.ShowIsCampus = val
}

// SetMultiLocale sets the value of MultiLocale.
func (s *JobDetail) SetMultiLocale(val OptString) {
	s.MultiLocale = val
}

// SetBrandMessage sets the value of BrandMessage.
func (s *JobDetail) SetBrandMessage(val OptString) {
	s.BrandMessage = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *JobDetail) SetCreatedAt(val OptString) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *JobDetail) SetUpdatedAt(val OptString) {
	s.UpdatedAt = val
}

// SetOpenedAt sets the value of OpenedAt.
func (s *JobDetail) SetOpenedAt(val OptString) {
	s.OpenedAt = val
}

// SetPublishedAt sets the value of PublishedAt.
func (s *JobDetail) SetPublishedAt(val OptString) {
	s.PublishedAt = val
}

// Ref: #/components/schemas/JobList
type JobList struct {
	Jobs     []Job       `json:"jobs"`
	JobStats OptJobStats `json:"jobStats"`
}

// GetJobs returns the value of Jobs.
func (s *JobList) GetJobs() []Job {
	return s.Jobs
}

// GetJobStats returns the value of JobStats.
func (s *JobList) GetJobStats() OptJobStats {
	return s.JobStats
}

// SetJobs sets the value of Jobs.
func (s *JobList) SetJobs(val []Job) {
	s.Jobs = val
}

// SetJobStats sets the value of JobStats.
func (s *JobList) SetJobStats(val OptJobStats) {
	s.JobStats = val
}

// Present only when the request set `needStat: true`.
// Ref: #/components/schemas/JobStats
type JobStats struct {
	OrgId OptString `json:"orgId"`
	// Total jobs matching the request, ignoring limit/offset.
	Total OptInt `json:"total"`
}

// GetOrgId returns the value of OrgId.
func (s *JobStats) GetOrgId() OptString {
	return s.OrgId
}

// GetTotal returns the value of Total.
func (s *JobStats) GetTotal() OptInt {
	return s.Total
}

// SetOrgId sets the value of OrgId.
func (s *JobStats) SetOrgId(val OptString) {
	s.OrgId = val
}

// SetTotal sets the value of Total.
func (s *JobStats) SetTotal(val OptInt) {
	s.Total = val
}

// Merged schema.
// Ref: #/components/schemas/ListJobsRequest
type ListJobsRequest struct {
	// Tenant slug, the first path segment of the careers URL (e.g. "high-flyer").
	OrgId string `json:"orgId"`
	// Careers-site id, the second path segment. A tenant can own several sites with different job sets,
	// and the site a bare /social-recruitment/ redirects to is not necessarily the largest one, so it is
	// never inferred.
	SiteId string `json:"siteId"`
	// Language for place names only. This client always sends "en-US"; see the document description.
	Locale OptString `json:"locale"`
	// Page size. Values above 50 are rejected with code 102.
	Limit OptInt `json:"limit"`
	// Zero-based offset of the first returned job.
	Offset OptInt `json:"offset"`
	// Populate `jobStats`. Without it the total is unavailable.
	NeedStat OptBool `json:"needStat"`
	// Title substring match. Does not search descriptions; see the document description.
	Keyword OptString `json:"keyword"`
	// Location ids from `locationAggregation.locationList[].locationRows[].id`. Multiple ids are ORed.
	LocationIds []int `json:"locationIds"`
	// 职能 (job-function) ids from `zhinengAggregation.zhinengList[].id`. Multiple ids are ORed.
	ZhinengIds []int `json:"zhinengIds"`
}

// GetOrgId returns the value of OrgId.
func (s *ListJobsRequest) GetOrgId() string {
	return s.OrgId
}

// GetSiteId returns the value of SiteId.
func (s *ListJobsRequest) GetSiteId() string {
	return s.SiteId
}

// GetLocale returns the value of Locale.
func (s *ListJobsRequest) GetLocale() OptString {
	return s.Locale
}

// GetLimit returns the value of Limit.
func (s *ListJobsRequest) GetLimit() OptInt {
	return s.Limit
}

// GetOffset returns the value of Offset.
func (s *ListJobsRequest) GetOffset() OptInt {
	return s.Offset
}

// GetNeedStat returns the value of NeedStat.
func (s *ListJobsRequest) GetNeedStat() OptBool {
	return s.NeedStat
}

// GetKeyword returns the value of Keyword.
func (s *ListJobsRequest) GetKeyword() OptString {
	return s.Keyword
}

// GetLocationIds returns the value of LocationIds.
func (s *ListJobsRequest) GetLocationIds() []int {
	return s.LocationIds
}

// GetZhinengIds returns the value of ZhinengIds.
func (s *ListJobsRequest) GetZhinengIds() []int {
	return s.ZhinengIds
}

// SetOrgId sets the value of OrgId.
func (s *ListJobsRequest) SetOrgId(val string) {
	s.OrgId = val
}

// SetSiteId sets the value of SiteId.
func (s *ListJobsRequest) SetSiteId(val string) {
	s.SiteId = val
}

// SetLocale sets the value of Locale.
func (s *ListJobsRequest) SetLocale(val OptString) {
	s.Locale = val
}

// SetLimit sets the value of Limit.
func (s *ListJobsRequest) SetLimit(val OptInt) {
	s.Limit = val
}

// SetOffset sets the value of Offset.
func (s *ListJobsRequest) SetOffset(val OptInt) {
	s.Offset = val
}

// SetNeedStat sets the value of NeedStat.
func (s *ListJobsRequest) SetNeedStat(val OptBool) {
	s.NeedStat = val
}

// SetKeyword sets the value of Keyword.
func (s *ListJobsRequest) SetKeyword(val OptString) {
	s.Keyword = val
}

// SetLocationIds sets the value of LocationIds.
func (s *ListJobsRequest) SetLocationIds(val []int) {
	s.LocationIds = val
}

// SetZhinengIds sets the value of ZhinengIds.
func (s *ListJobsRequest) SetZhinengIds(val []int) {
	s.ZhinengIds = val
}

// Merged schema.
// Ref: #/components/schemas/ListJobsResponse
type ListJobsResponse struct {
	// 0 on success; see the document description for known failures.
	Code     int    `json:"code"`
	CodeType OptInt `json:"codeType"`
	// Human-readable status, in Chinese ("成功" on success).
	Msg     OptString  `json:"msg"`
	Success bool       `json:"success"`
	Data    OptJobList `json:"data"`
}

// GetCode returns the value of Code.
func (s *ListJobsResponse) GetCode() int {
	return s.Code
}

// GetCodeType returns the value of CodeType.
func (s *ListJobsResponse) GetCodeType() OptInt {
	return s.CodeType
}

// GetMsg returns the value of Msg.
func (s *ListJobsResponse) GetMsg() OptString {
	return s.Msg
}

// GetSuccess returns the value of Success.
func (s *ListJobsResponse) GetSuccess() bool {
	return s.Success
}

// GetData returns the value of Data.
func (s *ListJobsResponse) GetData() OptJobList {
	return s.Data
}

// SetCode sets the value of Code.
func (s *ListJobsResponse) SetCode(val int) {
	s.Code = val
}

// SetCodeType sets the value of CodeType.
func (s *ListJobsResponse) SetCodeType(val OptInt) {
	s.CodeType = val
}

// SetMsg sets the value of Msg.
func (s *ListJobsResponse) SetMsg(val OptString) {
	s.Msg = val
}

// SetSuccess sets the value of Success.
func (s *ListJobsResponse) SetSuccess(val bool) {
	s.Success = val
}

// SetData sets the value of Data.
func (s *ListJobsResponse) SetData(val OptJobList) {
	s.Data = val
}

// One workplace. `id` is what `listJobs` takes as a `locationIds` element and what the location facet
// is keyed by. Which of the name fields are present, and in which language, varies by endpoint and by
// tenant — see the document description; only `id` is dependable.
// Ref: #/components/schemas/Location
type Location struct {
	ID OptInt `json:"id"`
	// National division code of the district, not the city — 110108 is Haidian, inside Beijing.
	CityId OptInt `json:"cityId"`
	// District, not city ("Haidian", "Gongshu"). Absent from `getJob` on some tenants.
	CityName OptString `json:"cityName"`
	// Returned by `listJobs` only.
	ProvinceId OptInt `json:"provinceId"`
	// Absent from `getJob` on some tenants.
	ProvinceName OptString `json:"provinceName"`
	// English under `locale=en-US` on `listJobs`, but Chinese on `getJob`; prefer `countryDescription`
	// when it is present.
	Country OptString `json:"country"`
	// The country in the requested locale. `getJob` only.
	CountryDescription OptString `json:"countryDescription"`
	// Street address. `getJob` only, and only on some tenants.
	Address OptString `json:"address"`
}

// GetID returns the value of ID.
func (s *Location) GetID() OptInt {
	return s.ID
}

// GetCityId returns the value of CityId.
func (s *Location) GetCityId() OptInt {
	return s.CityId
}

// GetCityName returns the value of CityName.
func (s *Location) GetCityName() OptString {
	return s.CityName
}

// GetProvinceId returns the value of ProvinceId.
func (s *Location) GetProvinceId() OptInt {
	return s.ProvinceId
}

// GetProvinceName returns the value of ProvinceName.
func (s *Location) GetProvinceName() OptString {
	return s.ProvinceName
}

// GetCountry returns the value of Country.
func (s *Location) GetCountry() OptString {
	return s.Country
}

// GetCountryDescription returns the value of CountryDescription.
func (s *Location) GetCountryDescription() OptString {
	return s.CountryDescription
}

// GetAddress returns the value of Address.
func (s *Location) GetAddress() OptString {
	return s.Address
}

// SetID sets the value of ID.
func (s *Location) SetID(val OptInt) {
	s.ID = val
}

// SetCityId sets the value of CityId.
func (s *Location) SetCityId(val OptInt) {
	s.CityId = val
}

// SetCityName sets the value of CityName.
func (s *Location) SetCityName(val OptString) {
	s.CityName = val
}

// SetProvinceId sets the value of ProvinceId.
func (s *Location) SetProvinceId(val OptInt) {
	s.ProvinceId = val
}

// SetProvinceName sets the value of ProvinceName.
func (s *Location) SetProvinceName(val OptString) {
	s.ProvinceName = val
}

// SetCountry sets the value of Country.
func (s *Location) SetCountry(val OptString) {
	s.Country = val
}

// SetCountryDescription sets the value of CountryDescription.
func (s *Location) SetCountryDescription(val OptString) {
	s.CountryDescription = val
}

// SetAddress sets the value of Address.
func (s *Location) SetAddress(val OptString) {
	s.Address = val
}

// Ref: #/components/schemas/LocationAggregation
type LocationAggregation struct {
	LocationList []LocationFacet `json:"locationList"`
}

// GetLocationList returns the value of LocationList.
func (s *LocationAggregation) GetLocationList() []LocationFacet {
	return s.LocationList
}

// SetLocationList sets the value of LocationList.
func (s *LocationAggregation) SetLocationList(val []LocationFacet) {
	s.LocationList = val
}

// One city. `label` is the display value; the `locationIds` to filter on are in `locationRows`,
// because one city can cover several districts.
// Ref: #/components/schemas/LocationFacet
type LocationFacet struct {
	// The city's label, repeated — a string here, unlike the integer ids in `locationRows`.
	ID     OptString `json:"id"`
	Label  OptString `json:"label"`
	CityId OptInt    `json:"cityId"`
	// Returned under `provinceAggregation` only, and observed as 0.
	JobCount     OptInt        `json:"jobCount"`
	LocationRows []LocationRow `json:"locationRows"`
}

// GetID returns the value of ID.
func (s *LocationFacet) GetID() OptString {
	return s.ID
}

// GetLabel returns the value of Label.
func (s *LocationFacet) GetLabel() OptString {
	return s.Label
}

// GetCityId returns the value of CityId.
func (s *LocationFacet) GetCityId() OptInt {
	return s.CityId
}

// GetJobCount returns the value of JobCount.
func (s *LocationFacet) GetJobCount() OptInt {
	return s.JobCount
}

// GetLocationRows returns the value of LocationRows.
func (s *LocationFacet) GetLocationRows() []LocationRow {
	return s.LocationRows
}

// SetID sets the value of ID.
func (s *LocationFacet) SetID(val OptString) {
	s.ID = val
}

// SetLabel sets the value of Label.
func (s *LocationFacet) SetLabel(val OptString) {
	s.Label = val
}

// SetCityId sets the value of CityId.
func (s *LocationFacet) SetCityId(val OptInt) {
	s.CityId = val
}

// SetJobCount sets the value of JobCount.
func (s *LocationFacet) SetJobCount(val OptInt) {
	s.JobCount = val
}

// SetLocationRows sets the value of LocationRows.
func (s *LocationFacet) SetLocationRows(val []LocationRow) {
	s.LocationRows = val
}

// Ref: #/components/schemas/LocationRow
type LocationRow struct {
	// A `Location.id`, accepted as a `locationIds` element.
	ID     OptInt `json:"id"`
	CityId OptInt `json:"cityId"`
}

// GetID returns the value of ID.
func (s *LocationRow) GetID() OptInt {
	return s.ID
}

// GetCityId returns the value of CityId.
func (s *LocationRow) GetCityId() OptInt {
	return s.CityId
}

// SetID sets the value of ID.
func (s *LocationRow) SetID(val OptInt) {
	s.ID = val
}

// SetCityId sets the value of CityId.
func (s *LocationRow) SetCityId(val OptInt) {
	s.CityId = val
}

// An id/name pair, used for 职能 (job function) and departments.
// Ref: #/components/schemas/NamedRef
type NamedRef struct {
	ID   OptInt    `json:"id"`
	Name OptString `json:"name"`
}

// GetID returns the value of ID.
func (s *NamedRef) GetID() OptInt {
	return s.ID
}

// GetName returns the value of Name.
func (s *NamedRef) GetName() OptString {
	return s.Name
}

// SetID sets the value of ID.
func (s *NamedRef) SetID(val OptInt) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *NamedRef) SetName(val OptString) {
	s.Name = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFilterAggregations returns new OptFilterAggregations with value set to v.
func NewOptFilterAggregations(v FilterAggregations) OptFilterAggregations {
	return OptFilterAggregations{
		Value: v,
		Set:   true,
	}
}

// OptFilterAggregations is optional FilterAggregations.
type OptFilterAggregations struct {
	Value FilterAggregations
	Set   bool
}

// IsSet returns true if OptFilterAggregations was set.
func (o OptFilterAggregations) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFilterAggregations) Reset() {
	var v FilterAggregations
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFilterAggregations) SetTo(v FilterAggregations) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFilterAggregations) Get() (v FilterAggregations, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFilterAggregations) Or(d FilterAggregations) FilterAggregations {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptJobDetail returns new OptJobDetail with value set to v.
func NewOptJobDetail(v JobDetail) OptJobDetail {
	return OptJobDetail{
		Value: v,
		Set:   true,
	}
}

// OptJobDetail is optional JobDetail.
type OptJobDetail struct {
	Value JobDetail
	Set   bool
}

// IsSet returns true if OptJobDetail was set.
func (o OptJobDetail) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptJobDetail) Reset() {
	var v JobDetail
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptJobDetail) SetTo(v JobDetail) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptJobDetail) Get() (v JobDetail, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptJobDetail) Or(d JobDetail) JobDetail {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptJobList returns new OptJobList with value set to v.
func NewOptJobList(v JobList) OptJobList {
	return OptJobList{
		Value: v,
		Set:   true,
	}
}

// OptJobList is optional JobList.
type OptJobList struct {
	Value JobList
	Set   bool
}

// IsSet returns true if OptJobList was set.
func (o OptJobList) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptJobList) Reset() {
	var v JobList
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptJobList) SetTo(v JobList) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptJobList) Get() (v JobList, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptJobList) Or(d JobList) JobList {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptJobStats returns new OptJobStats with value set to v.
func NewOptJobStats(v JobStats) OptJobStats {
	return OptJobStats{
		Value: v,
		Set:   true,
	}
}

// OptJobStats is optional JobStats.
type OptJobStats struct {
	Value JobStats
	Set   bool
}

// IsSet returns true if OptJobStats was set.
func (o OptJobStats) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptJobStats) Reset() {
	var v JobStats
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptJobStats) SetTo(v JobStats) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptJobStats) Get() (v JobStats, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptJobStats) Or(d JobStats) JobStats {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptLocationAggregation returns new OptLocationAggregation with value set to v.
func NewOptLocationAggregation(v LocationAggregation) OptLocationAggregation {
	return OptLocationAggregation{
		Value: v,
		Set:   true,
	}
}

// OptLocationAggregation is optional LocationAggregation.
type OptLocationAggregation struct {
	Value LocationAggregation
	Set   bool
}

// IsSet returns true if OptLocationAggregation was set.
func (o OptLocationAggregation) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptLocationAggregation) Reset() {
	var v LocationAggregation
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptLocationAggregation) SetTo(v LocationAggregation) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptLocationAggregation) Get() (v LocationAggregation, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptLocationAggregation) Or(d LocationAggregation) LocationAggregation {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNamedRef returns new OptNamedRef with value set to v.
func NewOptNamedRef(v NamedRef) OptNamedRef {
	return OptNamedRef{
		Value: v,
		Set:   true,
	}
}

// OptNamedRef is optional NamedRef.
type OptNamedRef struct {
	Value NamedRef
	Set   bool
}

// IsSet returns true if OptNamedRef was set.
func (o OptNamedRef) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNamedRef) Reset() {
	var v NamedRef
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptNamedRef) SetTo(v NamedRef) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNamedRef) Get() (v NamedRef, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNamedRef) Or(d NamedRef) NamedRef {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptProvinceAggregation returns new OptProvinceAggregation with value set to v.
func NewOptProvinceAggregation(v ProvinceAggregation) OptProvinceAggregation {
	return OptProvinceAggregation{
		Value: v,
		Set:   true,
	}
}

// OptProvinceAggregation is optional ProvinceAggregation.
type OptProvinceAggregation struct {
	Value ProvinceAggregation
	Set   bool
}

// IsSet returns true if OptProvinceAggregation was set.
func (o OptProvinceAggregation) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptProvinceAggregation) Reset() {
	var v ProvinceAggregation
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptProvinceAggregation) SetTo(v ProvinceAggregation) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptProvinceAggregation) Get() (v ProvinceAggregation, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptProvinceAggregation) Or(d ProvinceAggregation) ProvinceAggregation {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSystemFieldsAggregations returns new OptSystemFieldsAggregations with value set to v.
func NewOptSystemFieldsAggregations(v SystemFieldsAggregations) OptSystemFieldsAggregations {
	return OptSystemFieldsAggregations{
		Value: v,
		Set:   true,
	}
}

// OptSystemFieldsAggregations is optional SystemFieldsAggregations.
type OptSystemFieldsAggregations struct {
	Value SystemFieldsAggregations
	Set   bool
}

// IsSet returns true if OptSystemFieldsAggregations was set.
func (o OptSystemFieldsAggregations) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSystemFieldsAggregations) Reset() {
	var v SystemFieldsAggregations
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSystemFieldsAggregations) SetTo(v SystemFieldsAggregations) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSystemFieldsAggregations) Get() (v SystemFieldsAggregations, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSystemFieldsAggregations) Or(d SystemFieldsAggregations) SystemFieldsAggregations {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptZhinengAggregation returns new OptZhinengAggregation with value set to v.
func NewOptZhinengAggregation(v ZhinengAggregation) OptZhinengAggregation {
	return OptZhinengAggregation{
		Value: v,
		Set:   true,
	}
}

// OptZhinengAggregation is optional ZhinengAggregation.
type OptZhinengAggregation struct {
	Value ZhinengAggregation
	Set   bool
}

// IsSet returns true if OptZhinengAggregation was set.
func (o OptZhinengAggregation) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptZhinengAggregation) Reset() {
	var v ZhinengAggregation
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptZhinengAggregation) SetTo(v ZhinengAggregation) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptZhinengAggregation) Get() (v ZhinengAggregation, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptZhinengAggregation) Or(d ZhinengAggregation) ZhinengAggregation {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/ProvinceAggregation
type ProvinceAggregation struct {
	ProvinceList []ProvinceFacet `json:"provinceList"`
}

// GetProvinceList returns the value of ProvinceList.
func (s *ProvinceAggregation) GetProvinceList() []ProvinceFacet {
	return s.ProvinceList
}

// SetProvinceList sets the value of ProvinceList.
func (s *ProvinceAggregation) SetProvinceList(val []ProvinceFacet) {
	s.ProvinceList = val
}

// One province, and the cities under it. Municipalities repeat themselves — Shanghai is both the
// province label and its only city.
// Ref: #/components/schemas/ProvinceFacet
type ProvinceFacet struct {
	ID         OptString `json:"id"`
	Label      OptString `json:"label"`
	ProvinceId OptInt    `json:"provinceId"`
	// Every `Location.id` in the province, across all its cities.
	LocationRows []LocationRow   `json:"locationRows"`
	CityRows     []LocationFacet `json:"cityRows"`
}

// GetID returns the value of ID.
func (s *ProvinceFacet) GetID() OptString {
	return s.ID
}

// GetLabel returns the value of Label.
func (s *ProvinceFacet) GetLabel() OptString {
	return s.Label
}

// GetProvinceId returns the value of ProvinceId.
func (s *ProvinceFacet) GetProvinceId() OptInt {
	return s.ProvinceId
}

// GetLocationRows returns the value of LocationRows.
func (s *ProvinceFacet) GetLocationRows() []LocationRow {
	return s.LocationRows
}

// GetCityRows returns the value of CityRows.
func (s *ProvinceFacet) GetCityRows() []LocationFacet {
	return s.CityRows
}

// SetID sets the value of ID.
func (s *ProvinceFacet) SetID(val OptString) {
	s.ID = val
}

// SetLabel sets the value of Label.
func (s *ProvinceFacet) SetLabel(val OptString) {
	s.Label = val
}

// SetProvinceId sets the value of ProvinceId.
func (s *ProvinceFacet) SetProvinceId(val OptInt) {
	s.ProvinceId = val
}

// SetLocationRows sets the value of LocationRows.
func (s *ProvinceFacet) SetLocationRows(val []LocationRow) {
	s.LocationRows = val
}

// SetCityRows sets the value of CityRows.
func (s *ProvinceFacet) SetCityRows(val []LocationFacet) {
	s.CityRows = val
}

// The (tenant, careers site) pair every endpoint requires.
// Ref: #/components/schemas/SiteRef
type SiteRef struct {
	// Tenant slug, the first path segment of the careers URL (e.g. "high-flyer").
	OrgId string `json:"orgId"`
	// Careers-site id, the second path segment. A tenant can own several sites with different job sets,
	// and the site a bare /social-recruitment/ redirects to is not necessarily the largest one, so it is
	// never inferred.
	SiteId string `json:"siteId"`
	// Language for place names only. This client always sends "en-US"; see the document description.
	Locale OptString `json:"locale"`
}

// GetOrgId returns the value of OrgId.
func (s *SiteRef) GetOrgId() string {
	return s.OrgId
}

// GetSiteId returns the value of SiteId.
func (s *SiteRef) GetSiteId() string {
	return s.SiteId
}

// GetLocale returns the value of Locale.
func (s *SiteRef) GetLocale() OptString {
	return s.Locale
}

// SetOrgId sets the value of OrgId.
func (s *SiteRef) SetOrgId(val string) {
	s.OrgId = val
}

// SetSiteId sets the value of SiteId.
func (s *SiteRef) SetSiteId(val string) {
	s.SiteId = val
}

// SetLocale sets the value of Locale.
func (s *SiteRef) SetLocale(val OptString) {
	s.Locale = val
}

// Empty for tenants that publish no filter dimensions at all — the same ones whose postings tend to
// carry no `locations`. `customFieldsAggregations` is returned but unused.
// Ref: #/components/schemas/SystemFieldsAggregations
type SystemFieldsAggregations struct {
	LocationAggregation OptLocationAggregation `json:"locationAggregation"`
	ProvinceAggregation OptProvinceAggregation `json:"provinceAggregation"`
	ZhinengAggregation  OptZhinengAggregation  `json:"zhinengAggregation"`
}

// GetLocationAggregation returns the value of LocationAggregation.
func (s *SystemFieldsAggregations) GetLocationAggregation() OptLocationAggregation {
	return s.LocationAggregation
}

// GetProvinceAggregation returns the value of ProvinceAggregation.
func (s *SystemFieldsAggregations) GetProvinceAggregation() OptProvinceAggregation {
	return s.ProvinceAggregation
}

// GetZhinengAggregation returns the value of ZhinengAggregation.
func (s *SystemFieldsAggregations) GetZhinengAggregation() OptZhinengAggregation {
	return s.ZhinengAggregation
}

// SetLocationAggregation sets the value of LocationAggregation.
func (s *SystemFieldsAggregations) SetLocationAggregation(val OptLocationAggregation) {
	s.LocationAggregation = val
}

// SetProvinceAggregation sets the value of ProvinceAggregation.
func (s *SystemFieldsAggregations) SetProvinceAggregation(val OptProvinceAggregation) {
	s.ProvinceAggregation = val
}

// SetZhinengAggregation sets the value of ZhinengAggregation.
func (s *SystemFieldsAggregations) SetZhinengAggregation(val OptZhinengAggregation) {
	s.ZhinengAggregation = val
}

// Ref: #/components/schemas/ZhinengAggregation
type ZhinengAggregation struct {
	ZhinengList []ZhinengFacet `json:"zhinengList"`
}

// GetZhinengList returns the value of ZhinengList.
func (s *ZhinengAggregation) GetZhinengList() []ZhinengFacet {
	return s.ZhinengList
}

// SetZhinengList sets the value of ZhinengList.
func (s *ZhinengAggregation) SetZhinengList(val []ZhinengFacet) {
	s.ZhinengList = val
}

// One 职能 (job function) the site groups postings under. The list is a two-level tree; a parent's
// `jobCount` includes its children's.
// Ref: #/components/schemas/ZhinengFacet
type ZhinengFacet struct {
	// Accepted as a `zhinengIds` element.
	ID    OptInt    `json:"id"`
	Label OptString `json:"label"`
	// 0 for top-level entries.
	ParentId OptInt `json:"parentId"`
	JobCount OptInt `json:"jobCount"`
	// The tenant's display order.
	Sort     OptInt         `json:"sort"`
	Children []ZhinengFacet `json:"children"`
}

// GetID returns the value of ID.
func (s *ZhinengFacet) GetID() OptInt {
	return s.ID
}

// GetLabel returns the value of Label.
func (s *ZhinengFacet) GetLabel() OptString {
	return s.Label
}

// GetParentId returns the value of ParentId.
func (s *ZhinengFacet) GetParentId() OptInt {
	return s.ParentId
}

// GetJobCount returns the value of JobCount.
func (s *ZhinengFacet) GetJobCount() OptInt {
	return s.JobCount
}

// GetSort returns the value of Sort.
func (s *ZhinengFacet) GetSort() OptInt {
	return s.Sort
}

// GetChildren returns the value of Children.
func (s *ZhinengFacet) GetChildren() []ZhinengFacet {
	return s.Children
}

// SetID sets the value of ID.
func (s *ZhinengFacet) SetID(val OptInt) {
	s.ID = val
}

// SetLabel sets the value of Label.
func (s *ZhinengFacet) SetLabel(val OptString) {
	s.Label = val
}

// SetParentId sets the value of ParentId.
func (s *ZhinengFacet) SetParentId(val OptInt) {
	s.ParentId = val
}

// SetJobCount sets the value of JobCount.
func (s *ZhinengFacet) SetJobCount(val OptInt) {
	s.JobCount = val
}

// SetSort sets the value of Sort.
func (s *ZhinengFacet) SetSort(val OptInt) {
	s.Sort = val
}

// SetChildren sets the value of Children.
func (s *ZhinengFacet) SetChildren(val []ZhinengFacet) {
	s.Children = val
}
