// Code generated by ogen, DO NOT EDIT.

package herp

// OperationName is the ogen operation name
type OperationName = string

const (
	GetCompanyOperation OperationName = "GetCompany"
	ListJobsOperation   OperationName = "ListJobs"
)
