POST https://recruiting.ultipro.com/TEC1006TESER/JobBoard/18180d88-ced0-4361-bd09-d5eef66dab24/JobBoardView/LoadSearchResults
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Content-Type: application/json; charset=UTF-8
X-Requested-With: XMLHttpRequest
{
  "opportunitySearch": {
    "Top": 20,
    "Skip": 0,
    "QueryString": "",
    "OrderBy": [
      {"Value": "postedDateDesc", "PropertyName": "PostedDate", "Ascending": false}
    ],
    "Filters": [
      {"t": "TermsSearchFilterDto", "fieldName": 4, "extra": null, "values": []},
      {"t": "TermsSearchFilterDto", "fieldName": 5, "extra": null, "values": []},
      {"t": "TermsSearchFilterDto", "fieldName": 6, "extra": null, "values": []},
      {"t": "TermsSearchFilterDto", "fieldName": 37, "extra": null, "values": []}
    ]
  },
  "matchCriteria": {
    "PreferredJobs": [],
    "Educations": [],
    "LicenseAndCertifications": [],
    "Skills": [],
    "hasNoLicenses": false,
    "SkippedSkills": []
  }
}

HTTP 200
