// Code generated by ogen, DO NOT EDIT.

package flowxtra

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetJobDetailParams is parameters of getJobDetail operation.
type GetJobDetailParams struct {
	// Public hashed job id (`has_id` on every list row).
	HasId string
}

func unpackGetJobDetailParams(packed middleware.Parameters) (params GetJobDetailParams) {
	{
		key := middleware.ParameterKey{
			Name: "hasId",
			In:   "path",
		}
		params.HasId = packed[key].(string)
	}
	return params
}

func decodeGetJobDetailParams(args [1]string, argsEscaped bool, r *http.Request) (params GetJobDetailParams, _ error) {
	// Decode path: hasId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "hasId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.HasId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "hasId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListJobsParams is parameters of listJobs operation.
type ListJobsParams struct {
	// Free-text job-title search (server-side LIKE).
	SearchKey OptString `json:",omitempty,omitzero"`
	// Location search — matches company city, state, or country (server-side LIKE), e.g. "Spain" or
	// "Barcelona".
	Location OptString `json:",omitempty,omitzero"`
	// Exact workplace match. Live rows carry "On-site" and "Remote"; the site's own filter UI also offers
	// "Hybrid".
	Workplace OptListJobsWorkplace `json:",omitempty,omitzero"`
	// Company-name search (server-side LIKE).
	CompanyName OptString `json:",omitempty,omitzero"`
	// 1-based page number.
	Page OptInt `json:",omitempty,omitzero"`
	// Page size (100 verified working live).
	PerPage OptInt `json:",omitempty,omitzero"`
}

func unpackListJobsParams(packed middleware.Parameters) (params ListJobsParams) {
	{
		key := middleware.ParameterKey{
			Name: "search-key",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.SearchKey = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "location",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Location = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "workplace",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Workplace = v.(OptListJobsWorkplace)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "company_name",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.CompanyName = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "page",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Page = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "per_page",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.PerPage = v.(OptInt)
		}
	}
	return params
}

func decodeListJobsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListJobsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: search-key.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "search-key",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSearchKeyVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSearchKeyVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.SearchKey.SetTo(paramsDotSearchKeyVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "search-key",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: location.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "location",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLocationVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotLocationVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Location.SetTo(paramsDotLocationVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "location",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: workplace.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "workplace",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotWorkplaceVal ListJobsWorkplace
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotWorkplaceVal = ListJobsWorkplace(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Workplace.SetTo(paramsDotWorkplaceVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Workplace.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workplace",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: company_name.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "company_name",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCompanyNameVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCompanyNameVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.CompanyName.SetTo(paramsDotCompanyNameVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "company_name",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: page.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "page",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotPageVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotPageVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Page.SetTo(paramsDotPageVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Page.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "page",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: per_page.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "per_page",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotPerPageVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotPerPageVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.PerPage.SetTo(paramsDotPerPageVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.PerPage.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "per_page",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
