// Code generated by ogen, DO NOT EDIT.

package flowxtra

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetJobDetail implements getJobDetail operation.
	//
	// Full posting detail: HTML description, company profile, employment types, office location, and the
	// company's career-page apply URL.
	//
	// GET /candidate/jobs/{hasId}
	GetJobDetail(ctx context.Context, params GetJobDetailParams) (GetJobDetailRes, error)
	// ListJobs implements listJobs operation.
	//
	// Laravel-paginated cross-tenant list, newest-first by date_share. All narrowing parameters are
	// server-side (total drops); combine freely. Omitting every parameter returns the newest postings on
	// the whole board.
	//
	// GET /central/jobs
	ListJobs(ctx context.Context, params ListJobsParams) (*JobListEnvelope, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
