// Code generated by ogen, DO NOT EDIT.

package flowxtra

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetJobDetail implements getJobDetail operation.
//
// Full posting detail: HTML description, company profile, employment types, office location, and the
// company's career-page apply URL.
//
// GET /candidate/jobs/{hasId}
func (UnimplementedHandler) GetJobDetail(ctx context.Context, params GetJobDetailParams) (r GetJobDetailRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListJobs implements listJobs operation.
//
// Laravel-paginated cross-tenant list, newest-first by date_share. All narrowing parameters are
// server-side (total drops); combine freely. Omitting every parameter returns the newest postings on
// the whole board.
//
// GET /central/jobs
func (UnimplementedHandler) ListJobs(ctx context.Context, params ListJobsParams) (r *JobListEnvelope, _ error) {
	return r, ht.ErrNotImplemented
}
