// Code generated by ogen, DO NOT EDIT.

package dayforce

// OperationName is the ogen operation name
type OperationName = string

const (
	GetCsrfOperation           OperationName = "GetCsrf"
	GetJobPostingOperation     OperationName = "GetJobPosting"
	ListDepartmentsOperation   OperationName = "ListDepartments"
	ListPayClassesOperation    OperationName = "ListPayClasses"
	ListPayTypesOperation      OperationName = "ListPayTypes"
	SearchJobPostingsOperation OperationName = "SearchJobPostings"
)
