package workable

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/urfave/cli/v3"

	provider "github.com/amikai/openings-mcp/internal/provider/workable"
)

// TestNormalizeCompany covers the roster lookup: unknown accounts are
// rejected and known ones resolve to the roster's stored casing.
func TestNormalizeCompany(t *testing.T) {
	t.Run("unknown company", func(t *testing.T) {
		_, err := normalizeCompany(provider.MockUnknownCompany)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "not found; run 'openings-cli workable companies' to see supported companies")
	})

	t.Run("mixed-case input resolves to roster casing", func(t *testing.T) {
		account, err := normalizeCompany("BLUEGROUND")
		require.NoError(t, err)
		assert.Equal(t, "blueground", account)
	})
}

// runCLI runs the command against a fresh *cli.Command, returning captured
// stdout/stderr and the run error.
func runCLI(t *testing.T, baseURL string, args ...string) (stdout, stderr string, err error) {
	t.Helper()
	var out, errOut bytes.Buffer
	cmd := NewCmd()
	cmd.Writer = &out
	cmd.ErrWriter = &errOut
	full := append([]string{"workable", "--base-url", baseURL}, args...)
	err = cmd.Run(context.Background(), full)
	return out.String(), errOut.String(), err
}

// upstreamFixture reads one of the responses internal/provider/workable
// captured from the live API with hurl — the same bytes NewMockServer
// replays. The CLI passes the API response straight through, so these are the
// expectation: no golden file of our own to drift, and the bytes were recorded
// from Workable rather than generated by the code under test.
func upstreamFixture(t *testing.T, name string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("..", "..", "..", "provider", "workable", "testdata", name))
	require.NoError(t, err)
	return string(b)
}

func TestEndToEnd(t *testing.T) {
	srv := provider.NewMockServer()
	defer srv.Close()

	t.Run("search no filters", func(t *testing.T) {
		out, _, err := runCLI(t, srv.URL, "search", "--company", "blueground")
		require.NoError(t, err)
		assert.JSONEq(t, upstreamFixture(t, "jobs_rsp.json"), out)
	})

	t.Run("search keyword", func(t *testing.T) {
		out, _, err := runCLI(t, srv.URL, "search", "--company", "blueground", "--keyword", "engineer")
		require.NoError(t, err)
		assert.JSONEq(t, upstreamFixture(t, "jobs_filtered_rsp.json"), out)
	})

	t.Run("search page 2", func(t *testing.T) {
		out, _, err := runCLI(t, srv.URL, "search", "--company", "blueground", "--page-token", provider.MockPage2Token)
		require.NoError(t, err)
		assert.JSONEq(t, upstreamFixture(t, "jobs_page2_rsp.json"), out)
	})

	t.Run("detail", func(t *testing.T) {
		out, _, err := runCLI(t, srv.URL, "detail", "--company", "blueground", "--shortcode", "B02DA69C8F")
		require.NoError(t, err)
		assert.JSONEq(t, upstreamFixture(t, "job_detail_rsp.json"), out)
	})

	t.Run("filters", func(t *testing.T) {
		out, _, err := runCLI(t, srv.URL, "filters", "--company", "blueground")
		require.NoError(t, err)
		assert.JSONEq(t, upstreamFixture(t, "jobs_filters_rsp.json"), out)
	})

	// companies makes no network call, emits plain slugs rather than JSON, and
	// its roster is ~3900 entries, so it gets a bounded assertion instead of a
	// golden file: one slug per line, nothing else on the line, in roster
	// order. Asserting the exact line content is what keeps this honest — a
	// switch back to JSON, or to printing display names, fails here.
	t.Run("companies", func(t *testing.T) {
		out, _, err := runCLI(t, srv.URL, "companies")
		require.NoError(t, err)

		lines := strings.Split(strings.TrimSuffix(out, "\n"), "\n")
		require.NotEmpty(t, provider.Companies)
		require.Len(t, lines, len(provider.Companies))
		assert.Equal(t, provider.Companies[0].Account, lines[0])
		assert.Equal(t, provider.Companies[len(provider.Companies)-1].Account, lines[len(lines)-1])
	})
}

// TestMounted runs NewCmd() the way cmd/openings-cli does — as a subcommand of
// a parent — because that changes what cmd.Root() resolves to and which help
// the "a subcommand is required" path prints. The other tests drive NewCmd()
// standalone, so without this the mounted arrangement would go untested.
func TestMounted(t *testing.T) {
	srv := provider.NewMockServer()
	defer srv.Close()

	run := func(args ...string) (string, string, error) {
		var out, errOut bytes.Buffer
		root := &cli.Command{
			Name:      "openings-cli",
			Writer:    &out,
			ErrWriter: &errOut,
			Commands:  []*cli.Command{NewCmd()},
		}
		err := root.Run(context.Background(), append([]string{"openings-cli"}, args...))
		return out.String(), errOut.String(), err
	}

	t.Run("leaf runs and writes to the root's writer", func(t *testing.T) {
		out, _, err := run("workable", "--base-url", srv.URL, "search", "--company", "blueground")
		require.NoError(t, err)
		assert.JSONEq(t, upstreamFixture(t, "jobs_rsp.json"), out)
	})

	t.Run("provider flags reach the leaf from either side of it", func(t *testing.T) {
		out, _, err := run("workable", "search", "--base-url", srv.URL, "--company", "blueground")
		require.NoError(t, err)
		assert.JSONEq(t, upstreamFixture(t, "jobs_rsp.json"), out)
	})

	t.Run("provider without a subcommand errors and prints its own help", func(t *testing.T) {
		out, _, err := run("workable")
		require.Error(t, err)
		assert.EqualError(t, err, "a subcommand (companies, search, detail, or filters) is required")
		assert.Contains(t, out, "openings-cli workable", "should print workable's help, not the root's")
		assert.Contains(t, out, "companies")
	})
}

func TestErrorCases(t *testing.T) {
	srv := provider.NewMockServer()
	defer srv.Close()

	t.Run("unknown shortcode", func(t *testing.T) {
		_, _, err := runCLI(t, srv.URL, "detail", "--company", "blueground", "--shortcode", "0000000000")
		require.Error(t, err)
		assert.EqualError(t, err, `job "0000000000" not found for company "blueground"`)
	})

	t.Run("company not in roster is rejected before any HTTP call", func(t *testing.T) {
		_, _, err := runCLI(t, srv.URL, "search", "--company", provider.MockUnknownCompany)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "not found; run 'openings-cli workable companies' to see supported companies")
	})

	t.Run("--workplace bogus", func(t *testing.T) {
		_, _, err := runCLI(t, srv.URL, "search", "--company", "blueground", "--workplace", "bogus")
		require.Error(t, err)
		assert.EqualError(t, err, `--workplace must be on_site, hybrid, or remote, got "bogus"`)
	})

	t.Run("--department-id -1", func(t *testing.T) {
		_, _, err := runCLI(t, srv.URL, "search", "--company", "blueground", "--department-id", "-1")
		require.Error(t, err)
		assert.EqualError(t, err, "--department-id must be a positive facet id, got -1")
	})

	t.Run("missing --company", func(t *testing.T) {
		_, _, err := runCLI(t, srv.URL, "search")
		require.Error(t, err)
		assert.EqualError(t, err, "--company is required")
	})

	t.Run("missing --shortcode", func(t *testing.T) {
		_, _, err := runCLI(t, srv.URL, "detail", "--company", "blueground")
		require.Error(t, err)
		assert.Contains(t, err.Error(), `Required flag "shortcode" not set`)
	})

	t.Run("stray positional arg on detail", func(t *testing.T) {
		_, _, err := runCLI(t, srv.URL, "detail", "--company", "blueground", "--shortcode", "B02DA69C8F", "extra")
		require.Error(t, err)
		assert.EqualError(t, err, `detail takes no positional arguments, got [extra]`)
	})

	t.Run("stray positional arg on companies", func(t *testing.T) {
		_, _, err := runCLI(t, srv.URL, "companies", "extra")
		require.Error(t, err)
		assert.EqualError(t, err, `companies takes no positional arguments, got [extra]`)
	})

	t.Run("root with no subcommand", func(t *testing.T) {
		_, _, err := runCLI(t, srv.URL)
		require.Error(t, err)
		assert.EqualError(t, err, "a subcommand (companies, search, detail, or filters) is required")
	})
}
