// Code generated by ogen, DO NOT EDIT.

package foxconn

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetJobVacancyParams is parameters of getJobVacancy operation.
type GetJobVacancyParams struct {
	// The opaque `id` field from a list result (a hex-ish string, e.g. 08de75d7bd7611a790b20d5b47c2f1bb)
	// — NOT the human-readable `job_no` (e.g. PP26022700001).
	ID string
}

func unpackGetJobVacancyParams(packed middleware.Parameters) (params GetJobVacancyParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	return params
}

func decodeGetJobVacancyParams(args [1]string, argsEscaped bool, r *http.Request) (params GetJobVacancyParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListJobVacanciesParams is parameters of listJobVacancies operation.
type ListJobVacanciesParams struct {
	// Location filter, e.g. TA (Taiwan), CH (China), VM (Vietnam). Full enum is the Labels/Workplace/Codes
	// reference data (codes.go). An unknown value yields HTTP 200 with an empty array, not a 404.
	WorkplaceCode OptString `json:",omitempty,omitzero"`
	// Recruitment-track filter, e.g. MA (新幹班/management associate), TALENTS (一般招募), INTERN,
	// PT, DR (身障友善). Full enum is the Labels/TalentZone/Codes reference data (codes.go). An
	// unknown value yields HTTP 200 with an empty array, not a 404.
	TalentZoneCode OptString `json:",omitempty,omitzero"`
	// Case-insensitive free-text search across the title AND body text (not the title alone). Accepts
	// URL-encoded Chinese. A keyword with zero matches yields HTTP 200 with an empty array.
	Keywords OptString `json:",omitempty,omitzero"`
}

func unpackListJobVacanciesParams(packed middleware.Parameters) (params ListJobVacanciesParams) {
	{
		key := middleware.ParameterKey{
			Name: "workplaceCode",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.WorkplaceCode = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "talentZoneCode",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.TalentZoneCode = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "keywords",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Keywords = v.(OptString)
		}
	}
	return params
}

func decodeListJobVacanciesParams(args [0]string, argsEscaped bool, r *http.Request) (params ListJobVacanciesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: workplaceCode.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "workplaceCode",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotWorkplaceCodeVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotWorkplaceCodeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.WorkplaceCode.SetTo(paramsDotWorkplaceCodeVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workplaceCode",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: talentZoneCode.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "talentZoneCode",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotTalentZoneCodeVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotTalentZoneCodeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.TalentZoneCode.SetTo(paramsDotTalentZoneCodeVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "talentZoneCode",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: keywords.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "keywords",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotKeywordsVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotKeywordsVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Keywords.SetTo(paramsDotKeywordsVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "keywords",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
