// Code generated by ogen, DO NOT EDIT.

package foxconn

// OperationName is the ogen operation name
type OperationName = string

const (
	GetJobVacancyOperation    OperationName = "GetJobVacancy"
	ListJobVacanciesOperation OperationName = "ListJobVacancies"
)
